parameters:
    BASE_URL: 'https://static2.touristtube.com'
    invoice_reference_prefix: H-
    emails:
        subject:
            account_invoice: "Tourist Tube: Invoice"
        header:
            name: "Tourist Tube"
            address: "Dubai Internet City Bldg 12, Floor 1 Dubai, United Arab Emirates"
            licensed: "License No. 93706"
            logo: /media/images/index/touristtubelogo.png
        email_sent_from: noreply@touristtube.com