_rest_currency_get_fbc_sbc_lang:
    path:      "/{_locale}/api/currencies/fbcsbc"
    defaults: { _controller: RestBundle:currency\Currency:getFbcSbc, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_currency_get_currency_list_lang:
    path:      "/{_locale}/api/currencies"
    defaults: { _controller: RestBundle:currency\Currency:getCurrencyList, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_currency_currency_conversion_rate_lang:
    path:      "/{_locale}/api/currencies/rate/{fromCurrency}/{toCurrency}"
    defaults: { _controller: RestBundle:currency\Currency:currencyConversionRate, _locale: "%locale%", fromCurrency: "", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_currency_exchange_amount_lang:
    path:      "/{_locale}/api/currencies/exchange"
    defaults: { _controller: RestBundle:currency\Currency:exchangeAmount, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST