RestaurantBundle\Entity\Restaurant:
    type: entity
    table: restaurant
    repositoryClass: RestaurantBundle\Repository\RestaurantRepository
    indexes:
        city_id:
            columns:
                - city_id
        hotel_id:
            columns:
                - hotel_id
        division_id:
            columns:
                - division_id
        is_featured:
            columns:
                - is_featured
        sort_order:
            columns:
                - sort_order
        published:
            columns:
                - published
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        cityId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: city_id
        countryCode:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: country_code
        address:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        latitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
        longitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
        hotelId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: hotel_id
        divisionId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: division_id
        isFeatured:
            type: integer
            nullable: false
            options:
                default: '0'
            column: is_featured
        sortOrder:
            type: integer
            nullable: false
            options:
                default: '1'
            column: sort_order
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
