<?php

_('[ActionOwner] uploaded %count$s new videos [TargetName]');
_('[ActionOwner] uploaded %count$s new photos [TargetName]');
_('[ActionOwner] uploaded %count$s new videos to the album [TargetName]');
_('[ActionOwner] uploaded %count$s new photo to the album [TargetName]');
_("[ActionOwner] uploaded a new video to the album [TargetName]");
_("[ActionOwner] uploaded a new photo to the album [TargetName]");
_("[ActionOwner] added a new album [TargetName]");
_("[ActionOwner] created a new event [TargetName]");
_("[ActionOwner] added a news");
_("[ActionOwner] added a new brochure [TargetName]");
_("[ActionOwner] added the following review");
_("[ActionOwner] posted the following on his TT page:");
_("[ActionOwner] posted the following on her TT page:");
_("[ActionOwner] posted the following:");
_("[ActionOwner] posted the following on your TT page:");
_("[ActionOwner] posted the following on [Owner]'s TT page:");
_("[ActionOwner] echoed the following");
_("[ActionOwner] uploaded a new album [TargetName]");
_("[ActionOwner] uploaded his own album [TargetName]");  
_("[ActionOwner] uploaded her own album [TargetName]");  
_("[ActionOwner] uploaded a [Owner]'s album [TargetName]");
_("[ActionOwner] uploaded your album [TargetName]");
_("[ActionOwner] updated their slogan");
_("[ActionOwner] updated their info");
_("[ActionOwner] updated their cover photo");
_("[ActionOwner] updated their profile image");
_("[ActionOwner] updated his profile image");      
_("[ActionOwner] updated her profile image");      
_("[ActionOwner] changed their event location [TargetName]");
_("[ActionOwner] updated his event location [TargetName]");      
_("[ActionOwner] updated her event location [TargetName]"); 
_("[ActionOwner] changed their event date [TargetName]");
_("[ActionOwner] changed his event date [TargetName]");
_("[ActionOwner] changed her event date [TargetName]");
_("[ActionOwner] changed their event time [TargetName]");
_("[ActionOwner] changed his event time [TargetName]");
_("[ActionOwner] changed her event time [TargetName]");    
_("[ActionOwner] cancelled their event [TargetName]");
_("[ActionOwner] cancelled his own event [TargetName]"); 
_("[ActionOwner] cancelled her own event [TargetName]");      
_("[ActionOwner] is now connected to [TargetName]'s channel");
_("[ActionOwner] and [Others] are now connected to [TargetName]'s channel");
_("[ActionOwner] and [Other] are now connected to [TargetName]'s channel");
_("[ActionOwner] is now following [Owner]");
_("[ActionOwner] and [Others] are now following [Owner]");
_("[ActionOwner] and [Other] are now following [Owner]");
_("[ActionOwner] is now friends with [Owner]");
_("[ActionOwner] and [Others] are now friends with [Owner]");
_("[ActionOwner] and [Other] are now friends with [Owner]");
_("[ActionOwner] sponsored the channel [TargetName]");
_("[ActionOwner] and [Others] sponsored the channel [TargetName]");
_("[ActionOwner] and [Other] sponsored the channel [TargetName]");
_("[ActionOwner] sponsored the event [TargetName]");                    
_("[ActionOwner] and [Others] sponsored the event [TargetName]");    
_("[ActionOwner] and [Other] sponsored the event [TargetName]");      
_("[ActionOwner] has accepted [Owner] as a sub channel");
_("[ActionOwner] and [Others] have accepted [Owner] as a sub channel");
_("[ActionOwner] and [Other] have accepted [Owner] as a sub channel");
_("[ActionOwner] is now a sub channel to [Owner]");
_("[ActionOwner] and [Others] are now a sub channel to [Owner]");
_("[ActionOwner] and [Other] are now a sub channel to [Owner]");
_("[ActionOwner] joined [Owner]'s event [TargetName]");
_("[ActionOwner] and [Others] joined [Owner]'s event [TargetName]");
_("[ActionOwner] and [Other] joined [Owner]'s event [TargetName]");
_("[ActionOwner] liked [Owner]'s comment on a photo [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on a photo [TargetName]");
_("[ActionOwner] and [Other] liked  [Owner]'s comment on a photo [TargetName]");
_("[ActionOwner] liked [Owner]'s comment on a video [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on a video [TargetName]");
_("[ActionOwner] and [Other] liked  [Owner]'s comment on a video [TargetName]");
_("[ActionOwner] liked the video [TargetName]");                       
_("[ActionOwner] and [Others] liked the video [TargetName]");           
_("[ActionOwner] and [Other] liked the video [TargetName]");  
_("[ActionOwner] liked his own video [TargetName]");
_("[ActionOwner] and [Others] liked his own video [TargetName]");
_("[ActionOwner] and [Other] liked his own video [TargetName]");            
_("[ActionOwner] liked her own photo [TargetName]");
_("[ActionOwner] and [Others] liked her own photo [TargetName]");
_("[ActionOwner] and [Other] liked her own photo [TargetName]");
_("[ActionOwner] liked their video [TargetName]");             
_("[ActionOwner] and [Others] liked their video [TargetName]");         
_("[ActionOwner] and [Other] liked their video [TargetName]");  
_("[ActionOwner] liked their photo [TargetName]");              
_("[ActionOwner] and [Others] liked their photo [TargetName]");           
_("[ActionOwner] and [Other] liked their photo [TargetName]");  
_("[ActionOwner] liked [Owner]'s video [TargetName]");         
_("[ActionOwner] and [Others] liked [Owner]'s video [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s video [TargetName]");
_("[ActionOwner] liked your video [TargetName]");
_("[ActionOwner] and [Others] liked your video [TargetName]");
_("[ActionOwner] and [Other] liked your video [TargetName]");
_("[ActionOwner] liked [Owner]'s photo [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s photo [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s photo [TargetName]");
_("[ActionOwner] liked your photo [TargetName]");
_("[ActionOwner] and [Others] liked your photo [TargetName]");
_("[ActionOwner] and [Other] liked your photo [TargetName]");
_("[ActionOwner] liked your video [TargetName]");
_("[ActionOwner] and [Others] liked your video [TargetName]");
_("[ActionOwner] and [Other] liked your video [TargetName]");
_("[ActionOwner] liked [Owner]'s comment on an album [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on an album [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s comment on an album [TargetName]");
_("[ActionOwner] liked the album [TargetName]");
_("[ActionOwner] and [Others] liked the album [TargetName]");
_("[ActionOwner] and [Other] liked the album [TargetName]");
_("[ActionOwner] liked his own album [TargetName]");                              
_("[ActionOwner] and [Others] liked his own album [TargetName]");           
_("[ActionOwner] and [Other] liked his own album [TargetName]");          
_("[ActionOwner] liked her own album [TargetName]");                               
_("[ActionOwner] and [Others] liked her own album [TargetName]");           
_("[ActionOwner] and [Other] liked her own album [TargetName]"); 
_("[ActionOwner] liked their album [TargetName]");
_("[ActionOwner] and [Others] liked their album [TargetName]");
_("[ActionOwner] and [Other] liked their album [TargetName]");
_("[ActionOwner] liked [Owner]'s album [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s album [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s album [TargetName]");
_("[ActionOwner] liked your album [TargetName]");
_("[ActionOwner] and [Others] liked your album [TargetName]");
_("[ActionOwner] and [Other] liked your album [TargetName]");
_("[ActionOwner] liked [Owner]'s comment on the channel [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on the channel [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s comment on the channel [TargetName]");
_("[ActionOwner] liked [TargetName]'s channel");
_("[ActionOwner] and [Others] liked [TargetName]'s channel");
_("[ActionOwner] and [Other] liked [TargetName]'s channel");
_("[ActionOwner] liked [Owner]'s comment on news");
_("[ActionOwner] and [Others] liked [Owner]'s comment on news");
_("[ActionOwner] and [Other] liked [Owner]'s comment on news");
_("[ActionOwner] liked [Owner]'s news");
_("[ActionOwner] and [Others] liked [Owner]'s news");
_("[ActionOwner] and [Other] liked [Owner]'s news");
_("[ActionOwner] liked [Owner]'s comment on brochure [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on brochure [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s comment on brochure [TargetName]");
_("[ActionOwner] liked [Owner]'s brochure");
_("[ActionOwner] and [Others] liked [Owner]'s brochure");
_("[ActionOwner] and [Other] liked [Owner]'s brochure");
_("[ActionOwner] liked [Owner]'s comment on an event [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on an event [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s comment on an event [TargetName]");
_("[ActionOwner] liked [Owner]'s event [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s event [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s event [TargetName]");
_("[ActionOwner] liked [Owner]'s comment on slogan");
_("[ActionOwner] and [Others] liked [Owner]'s comment on slogan");
_("[ActionOwner] and [Other] liked [Owner]'s comment on slogan");
_("[ActionOwner] liked their slogan");
_("[ActionOwner] and [Others] liked their slogan");
_("[ActionOwner] and [Other] liked their slogan");
_("[ActionOwner] liked [Owner]'s slogan");
_("[ActionOwner] and [Others] liked [Owner]'s slogan");
_("[ActionOwner] and [Other] liked [Owner]'s slogan");
_("[ActionOwner] liked [Owner]'s comment on info");
_("[ActionOwner] and [Others] liked [Owner]'s comment on info");
_("[ActionOwner] and [Other] liked [Owner]'s comment on info");
_("[ActionOwner] liked their info");
_("[ActionOwner] and [Others] liked their info");
_("[ActionOwner] and [Other] liked their info");
_("[ActionOwner] liked [Owner]'s info");
_("[ActionOwner] and [Others] liked [Owner]'s info");
_("[ActionOwner] and [Other] liked [Owner]'s info");
_("[ActionOwner] liked [Owner]'s comment on a cover photo");
_("[ActionOwner] and [Others] liked [Owner]'s comment on a cover photo");
_("[ActionOwner] and [Other] liked [Owner]'s comment on a cover photo");
_("[ActionOwner] liked their cover photo");
_("[ActionOwner] and [Others] liked their cover photo");
_("[ActionOwner] and [Other] liked their cover photo");
_("[ActionOwner] liked [Owner]'s cover photo");
_("[ActionOwner] and [Others] liked [Owner]'s cover photo");
_("[ActionOwner] and [Other] liked [Owner]'s cover photo");
_("[ActionOwner] liked [Owner]'s comment on a profile image");
_("[ActionOwner] and [Others] liked [Owner]'s comment on a profile image");
_("[ActionOwner] and [Other] liked [Owner]'s comment on a profile image");
_("[ActionOwner] liked their profile image");
_("[ActionOwner] and [Others] liked their profile image");
_("[ActionOwner] and [Other] liked their profile image");
_("[ActionOwner] liked [Owner]'s profile image");
_("[ActionOwner] and [Others] liked [Owner]'s profile image");
_("[ActionOwner] and [Other] liked [Owner]'s profile image");
_("[ActionOwner] liked the comment");
_("[ActionOwner] and [Others] liked the comment");
_("[ActionOwner] and [Other] liked the comment");
_("[ActionOwner] liked the comment on the following echo");
_("[ActionOwner] and [Others] liked the comment on the following echo");
_("[ActionOwner] and [Other] liked the comment on the following echo");
_("[ActionOwner] liked the profile image");
_("[ActionOwner] and [Others] liked the profile image");
_("[ActionOwner] and [Other] liked the profile image");
_("[ActionOwner] liked her own profile image");
_("[ActionOwner] and [Others] liked her own profile image");
_("[ActionOwner] and [Other] liked her own profile image");
_("[ActionOwner] liked his own profile image");
_("[ActionOwner] and [Others] liked his own profile image");
_("[ActionOwner] and [Other] liked his own profile image");
_("[ActionOwner] liked [Owner]'s comment on a profile image");
_("[ActionOwner] and [Others] liked [Owner]'s comment on a profile image");
_("[ActionOwner] and [Other] liked [Owner]'s comment on a profile image");
_("[ActionOwner] liked your profile image");
_("[ActionOwner] and [Others] liked your profile image");
_("[ActionOwner] and [Other] liked your profile image");
_("[ActionOwner] liked [Owner]'s profile image");
_("[ActionOwner] and [Others] liked [Owner]'s profile image");
_("[ActionOwner] and [Other] liked [Owner]'s profile image");
_("[ActionOwner] liked [Owner]'s comment on review");
_("[ActionOwner] and [Others] liked [Owner]'s comment on review");
_("[ActionOwner] and [Other] liked [Owner]'s comment on review");
_("[ActionOwner] liked the review");
_("[ActionOwner] and [Others] liked the review");
_("[ActionOwner] and [Other] liked the review");
_("[ActionOwner] liked his own review");                              
_("[ActionOwner] and [Others] liked his own review");        
_("[ActionOwner] and [Other] liked his own review");          
_("[ActionOwner] liked her own review");                             
_("[ActionOwner] and [Others] liked her own review");       
_("[ActionOwner] and [Other] liked her own review");  
_("[ActionOwner] liked your review");
_("[ActionOwner] and [Others] liked your review");
_("[ActionOwner] and [Other] liked your review");
_("[ActionOwner] liked [Owner]'s review");
_("[ActionOwner] and [Others] liked [Owner]'s review");
_("[ActionOwner] and [Other] liked [Owner]'s review");
_("[ActionOwner] liked [Owner]'s comment on a post");
_("[ActionOwner] and [Others] liked [Owner]'s comment on a post");
_("[ActionOwner] and [Other] liked [Owner]'s comment on a post");
_("[ActionOwner] liked the post");
_("[ActionOwner] and [Others] liked the post");
_("[ActionOwner] and [Other] liked the post");
_("[ActionOwner] liked his own post");                                   
_("[ActionOwner] and [Others] liked his own post");              
_("[ActionOwner] and [Other] liked his own post");                 
_("[ActionOwner] liked her own post");                               
_("[ActionOwner] and [Others] liked her own post");            
_("[ActionOwner] and [Other] liked her own post");                
_("[ActionOwner] liked their post");
_("[ActionOwner] and [Others] liked their post");
_("[ActionOwner] and [Other] liked their post");
_("[ActionOwner] liked [Owner]'s post");
_("[ActionOwner] and [Others] liked [Owner]'s post");
_("[ActionOwner] and [Other] liked [Owner]'s post");
_("[ActionOwner] liked your post");
_("[ActionOwner] and [Others] liked your post");
_("[ActionOwner] and [Other] liked your post");
_("[ActionOwner] liked [Owner]'s comment on echo");
_("[ActionOwner] and [Others] liked [Owner]'s comment on echo");
_("[ActionOwner] and [Other] liked [Owner]'s comment on echo");
_("[ActionOwner] liked the echo");
_("[ActionOwner] and [Others] liked the echo");
_("[ActionOwner] and [Other] liked the echo");
_("[ActionOwner] liked his own echo");                         
_("[ActionOwner] and [Others] liked his own echo");          
_("[ActionOwner] and [Other] liked his own echo");       
_("[ActionOwner] liked her own echo");                         
_("[ActionOwner] and [Others] liked her own echo");            
_("[ActionOwner] and [Other] liked her own echo");    
_("[ActionOwner] liked their echo");
_("[ActionOwner] and [Others] liked their echo");
_("[ActionOwner] and [Other] liked their echo");
_("[ActionOwner] liked [Owner]'s echo");
_("[ActionOwner] and [Others] liked [Owner]'s echo");
_("[ActionOwner] and [Other] liked [Owner]'s echo");
_("[ActionOwner] liked your echo");
_("[ActionOwner] and [Others] liked your echo");
_("[ActionOwner] and [Other] liked your echo");
_("[ActionOwner] liked [Owner]'s comment on an event [TargetName]");
_("[ActionOwner] and [Others] liked [Owner]'s comment on an event [TargetName]");
_("[ActionOwner] and [Other] liked [Owner]'s comment on an event [TargetName]");
_("[ActionOwner] liked the event [TargetName]");
_("[ActionOwner] and [Others] liked the event [TargetName]");
_("[ActionOwner] and [Other] liked the event [TargetName]");
_("[ActionOwner] liked his own event [TargetName]");                         
_("[ActionOwner] and [Others] liked his own event [TargetName]");            
_("[ActionOwner] and [Other] liked his own event [TargetName]");   
_("[ActionOwner] liked her own event [TargetName]");                          
_("[ActionOwner] and [Others] liked her own event [TargetName]");            
_("[ActionOwner] and [Other] liked her own event [TargetName]");      
_("[ActionOwner] liked your event [TargetName]");
_("[ActionOwner] and [Others] liked your event [TargetName]");
_("[ActionOwner] and [Other] liked your event [TargetName]");
_("[ActionOwner] rated the video [TargetName]");                     
_("[ActionOwner] and [Others] rated the video [TargetName]");                  
_("[ActionOwner] and [Other] rated the video [TargetName]"); 
_("[ActionOwner] rated the photo [TargetName]");                     
_("[ActionOwner] and [Others] rated the photo [TargetName]");                  
_("[ActionOwner] and [Other] rated the photo [TargetName]");                         
_("[ActionOwner] rated his own video [TargetName]");             
_("[ActionOwner] and [Others] rated his own video [TargetName]");           
_("[ActionOwner] and [Other] rated his own video [TargetName]");  
_("[ActionOwner] rated her own video [TargetName]");             
_("[ActionOwner] and [Others] rated her own video [TargetName]");           
_("[ActionOwner] and [Other] rated her own video [TargetName]");       
_("[ActionOwner] rated their video [TargetName]");                      
_("[ActionOwner] and [Others] rated their video [TargetName]");                      
_("[ActionOwner] and [Other] rated their video [TargetName]");                    
_("[ActionOwner] rated [Owner]'s video [TargetName]");           
_("[ActionOwner] and [Others] rated [Owner]'s video [TargetName]");           
_("[ActionOwner] and [Other] rated [Owner]'s video [TargetName]");             
_("[ActionOwner] rated your video [TargetName]");                     
_("[ActionOwner] and [Others] rated your video [TargetName]");                      
_("[ActionOwner] and [Other] rated your video [TargetName]");  
_("[ActionOwner] rated your photo [TargetName]");                     
_("[ActionOwner] and [Others] rated your photo [TargetName]");                      
_("[ActionOwner] and [Other] rated your photo [TargetName]");                  
_("[ActionOwner] rated his own photo [TargetName]");             
_("[ActionOwner] and [Others] rated his own photo [TargetName]");           
_("[ActionOwner] and [Other] rated his own photo [TargetName]"); 
_("[ActionOwner] rated her own photo [TargetName]");             
_("[ActionOwner] and [Others] rated her own photo [TargetName]");           
_("[ActionOwner] and [Other] rated her own photo [TargetName]");          
_("[ActionOwner] rated their photo [TargetName]");                      
_("[ActionOwner] and [Others] rated their photo [TargetName]");                      
_("[ActionOwner] and [Other] rated their photo [TargetName]");              
_("[ActionOwner] rated [Owner]'s photo [TargetName]");           
_("[ActionOwner] and [Others] rated [Owner]'s photo [TargetName]");           
_("[ActionOwner] and [Other] rated [Owner]'s photo [TargetName]");              
_("[ActionOwner] rated your photo [TargetName]");                     
_("[ActionOwner] and [Others] rated your photo [TargetName]");                      
_("[ActionOwner] and [Other] rated your photo [TargetName]");                   
_("[ActionOwner] rated the album [TargetName]");
_("[ActionOwner] and [Others] rated the album [TargetName]");
_("[ActionOwner] and [Other] rated the album [TargetName]");
_("[ActionOwner] rated his own album [TargetName]");                 
_("[ActionOwner] and [Others] rated his own album [TargetName]");        
_("[ActionOwner] and [Other] rated his own album [TargetName]");     
_("[ActionOwner] rated her own album [TargetName]");                   
_("[ActionOwner] and [Others] rated her own album [TargetName]");       
_("[ActionOwner] and [Other] rated her own album [TargetName]");  
_("[ActionOwner] rated their album [TargetName]");
_("[ActionOwner] and [Others] rated their album [TargetName]");
_("[ActionOwner] and [Other] rated their album [TargetName]");
_("[ActionOwner] rated [Owner]'s album [TargetName]");
_("[ActionOwner] and [Others] rated [Owner]'s album [TargetName]");
_("[ActionOwner] and [Other] rated [Owner]'s album [TargetName]");
_("[ActionOwner] rated your album [TargetName]");
_("[ActionOwner] and [Others] rated your album [TargetName]");
_("[ActionOwner] and [Other] rated your album [TargetName]");
_("[ActionOwner] rated the post");
_("[ActionOwner] and [Others] rated the post");
_("[ActionOwner] and [Other] rated the post");
_("[ActionOwner] rated his own post");                      
_("[ActionOwner] and [Others] rated his own post");       
_("[ActionOwner] and [Other] rated his own post");          
_("[ActionOwner] rated her own post");                    
_("[ActionOwner] and [Others] rated her own post");       
_("[ActionOwner] and [Other] rated her own post");         
_("[ActionOwner] rated their post");
_("[ActionOwner] and [Others] rated their post");
_("[ActionOwner] and [Other] rated their post");
_("[ActionOwner] rated [Owner]'s post");
_("[ActionOwner] and [Others] rated [Owner]'s post");
_("[ActionOwner] and [Other] rated [Owner]'s post");
_("[ActionOwner] rated your post");
_("[ActionOwner] and [Others] rated your post");
_("[ActionOwner] and [Other] rated your post");
_("[ActionOwner] commented on the echo");
_("[ActionOwner] and [Others] commented on the echo");
_("[ActionOwner] and [Other] commented on the echo");
_("[ActionOwner] commented on his own echo");            
_("[ActionOwner] and [Others] commented on his own echo");              
_("[ActionOwner] and [Other] commented on his own echo");            
_("[ActionOwner] commented on her own echo");           
_("[ActionOwner] and [Others] commented on her own echo");              
_("[ActionOwner] and [Other] commented on her own echo");       
_("[ActionOwner] commented on their echo");
_("[ActionOwner] and [Others] commented on their echo");
_("[ActionOwner] and [Other] commented on their echo");
_("[ActionOwner] commented on [Owner]'s echo [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s echo [TargetName]");
_("[ActionOwner] and [Other] commented on [Owner]'s echo [TargetName]");
_("[ActionOwner] commented on your own echo");
_("[ActionOwner] and [Others] commented on your own echo");
_("[ActionOwner] and [Other] commented on your own echo");
_("[ActionOwner] commented on the video [TargetName]");
_("[ActionOwner] and [Others] commented on the video [TargetName]");
_("[ActionOwner] and [Other] commented on the video [TargetName]");
_("[ActionOwner] commented on his own video [TargetName]");   
_("[ActionOwner] and [Others] commented on his own video [TargetName]"); 
_("[ActionOwner] and [Other] commented on his own video [TargetName]"); 
_("[ActionOwner] commented on her own video [TargetName]");   
_("[ActionOwner] and [Others] commented on her own video [TargetName]"); 
_("[ActionOwner] and [Other] commented on her own video [TargetName]"); 
_("[ActionOwner] commented on their video [TargetName]"); 
_("[ActionOwner] and [Others] commented on their video [TargetName]"); 
_("[ActionOwner] and [Other] commented on their video [TargetName]");
_("[ActionOwner] commented on [Owner]'s video [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s video [TargetName]");  
_("[ActionOwner] and [Other] commented on [Owner]'s video [TargetName]"); 
_("[ActionOwner] commented on your video [TargetName]");
_("[ActionOwner] and [Others] commented on your video [TargetName]");
_("[ActionOwner] and [Other] commented on your video [TargetName]");
_("[ActionOwner] commented on [Owner]'s video [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s video [TargetName]");
_("[ActionOwner] and [Other] commented on [Owner]'s video [TargetName]");
_("[ActionOwner] commented on the photo [TargetName]");
_("[ActionOwner] and [Others] commented on the photo [TargetName]");
_("[ActionOwner] and [Other] commented on the photo [TargetName]");
_("[ActionOwner] commented on his own photo [TargetName]");   
_("[ActionOwner] and [Others] commented on his own photo [TargetName]"); 
_("[ActionOwner] and [Other] commented on his own photo [TargetName]"); 
_("[ActionOwner] commented on her own photo [TargetName]");   
_("[ActionOwner] and [Others] commented on her own photo [TargetName]"); 
_("[ActionOwner] and [Other] commented on her own photo [TargetName]"); 
_("[ActionOwner] commented on their photo [TargetName]"); 
_("[ActionOwner] and [Others] commented on their photo [TargetName]"); 
_("[ActionOwner] and [Other] commented on their photo [TargetName]");
_("[ActionOwner] commented on [Owner]'s photo [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s photo [TargetName]");  
_("[ActionOwner] and [Other] commented on [Owner]'s photo [TargetName]"); 
_("[ActionOwner] commented on your photo [TargetName]");
_("[ActionOwner] and [Others] commented on your photo [TargetName]");
_("[ActionOwner] and [Other] commented on your photo [TargetName]");
_("[ActionOwner] commented on [Owner]'s photo [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s photo [TargetName]");
_("[ActionOwner] and [Other] commented on [Owner]'s photo [TargetName]");
_("[ActionOwner] commented on your echo");
_("[ActionOwner] and [Others] commented on your echo");
_("[ActionOwner] and [Other] commented on your echo");
_("[ActionOwner] commented on the album [TargetName]");
_("[ActionOwner] and [Others] commented on the album [TargetName]");
_("[ActionOwner] and [Other] commented on the album [TargetName]");
_("[ActionOwner] commented on his own album [TargetName]");       
_("[ActionOwner] and [Others] commented on his own album [TargetName]");    
_("[ActionOwner] and [Other] commented on his own album [TargetName]");    
_("[ActionOwner] commented on her own album [TargetName]");       
_("[ActionOwner] and [Others] commented on her own album [TargetName]");    
_("[ActionOwner] and [Other] commented on her own album [TargetName]");  
_("[ActionOwner] commented on their album [TargetName]"); 
_("[ActionOwner] and [Others] commented on their album [TargetName]");
_("[ActionOwner] and [Other] commented on their album [TargetName]");
_("[ActionOwner] commented on [Owner]'s album [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s album [TargetName]");
_("[ActionOwner] and [Other] commented on [Owner]'s album [TargetName]");
_("[ActionOwner] commented on your album [TargetName]");
_("[ActionOwner] and [Others] commented on your album [TargetName]");
_("[ActionOwner] and [Other] commented on your album [TargetName]");
_("[ActionOwner] commented on the profile image");
_("[ActionOwner] and [Others] commented on the profile image");
_("[ActionOwner] and [Other] commented on the profile image");
_("[ActionOwner] commented on his own profile image");   
_("[ActionOwner] and [Others] commented on his own profile image");   
_("[ActionOwner] and [Other] commented on his own profile image");   
_("[ActionOwner] commented on her own profile image");    
_("[ActionOwner] and [Others] commented on her own profile image");  
_("[ActionOwner] and [Other] commented on her own profile image");  
_("[ActionOwner] commented on your profile image");
_("[ActionOwner] and [Others] commented on your profile image");
_("[ActionOwner] and [Other] commented on your profile image");
_("[ActionOwner] commented on [Owner]'s profile image");
_("[ActionOwner] and [Others] commented on [Owner]'s profile image");
_("[ActionOwner] and [Other] commented on [Owner]'s profile image");
_("[ActionOwner] commented on their channel");
_("[ActionOwner] and [Others] commented on their channel");
_("[ActionOwner] and [Other] commented on their channel");
_("[ActionOwner] commented on [TargetName]'s channel");
_("[ActionOwner] and [Others] commented on [TargetName]'s channel");
_("[ActionOwner] and [Other] commented on [TargetName]'s channel");
_("[ActionOwner] commented on their news");
_("[ActionOwner] and [Others] commented on their news");
_("[ActionOwner] and [Other] commented on their news");
_("[ActionOwner] commented on [Owner]'s news");
_("[ActionOwner] and [Others] commented on [Owner]'s news");
_("[ActionOwner] and [Other] commented on [Owner]'s news");
_("[ActionOwner] commented on their brochure");
_("[ActionOwner] and [Others] commented on their brochure");
_("[ActionOwner] and [Other] commented on their brochure");
_("[ActionOwner] commented on [Owner]'s brochure");
_("[ActionOwner] and [Others] commented on [Owner]'s brochure");
_("[ActionOwner] and [Other] commented on [Owner]'s brochure");
_("[ActionOwner] commented on their event [TargetName]");
_("[ActionOwner] and [Others] commented on their event [TargetName]");
_("[ActionOwner] and [Other] commented on their event [TargetName]");
_("[ActionOwner] commented on [Owner]'s event [TargetName]");
_("[ActionOwner] and [Others] commented on [Owner]'s event [TargetName]");
_("[ActionOwner] and [Other] commented on [Owner]'s event [TargetName]");
_("[ActionOwner] commented on their slogan");
_("[ActionOwner] and [Others] commented on their slogan");
_("[ActionOwner] and [Other] commented on their slogan");
_("[ActionOwner] commented on [Owner]'s slogan");
_("[ActionOwner] and [Others] commented on [Owner]'s slogan");
_("[ActionOwner] and [Other] commented on [Owner]'s slogan");
_("[ActionOwner] commented on their info");
_("[ActionOwner] and [Others] commented on their info");
_("[ActionOwner] and [Other] commented on their info");
_("[ActionOwner] commented on [Owner]'s info");
_("[ActionOwner] and [Others] commented on [Owner]'s info");
_("[ActionOwner] and [Other] commented on [Owner]'s info");
_("[ActionOwner] commented on their cover photo");
_("[ActionOwner] and [Others] commented on their cover photo");
_("[ActionOwner] and [Other] commented on their cover photo");
_("[ActionOwner] commented on [TargetName]'s cover photo");
_("[ActionOwner] and [Others] commented on [TargetName]'s cover photo");
_("[ActionOwner] and [Other] commented on [TargetName]'s cover photo");
_("[ActionOwner] commented on their profile image");
_("[ActionOwner] and [Others] commented on their profile image");
_("[ActionOwner] and [Other] commented on their profile image");
_("[ActionOwner] commented on the review");
_("[ActionOwner] and [Others] commented on the review");
_("[ActionOwner] and [Other] commented on the review");
_("[ActionOwner] commented on his own review");      
_("[ActionOwner] and [Others] commented on his own review");   
_("[ActionOwner] and [Other] commented on his own review");    
_("[ActionOwner] commented on her own review");    
_("[ActionOwner] and [Others] commented on her own review");   
_("[ActionOwner] and [Other] commented on her own review");   
_("[ActionOwner] commented on your review");
_("[ActionOwner] and [Others] commented on your review");
_("[ActionOwner] and [Other] commented on your review");
_("[ActionOwner] commented on [Owner]'s review");
_("[ActionOwner] and [Others] commented on [Owner]'s review");
_("[ActionOwner] and [Other] commented on [Owner]'s review");
_("[ActionOwner] commented on the post");
_("[ActionOwner] and [Others] commented on the post");
_("[ActionOwner] and [Other] commented on the post");
_("[ActionOwner] commented on his own post");      
_("[ActionOwner] and [Others] commented on his own post");
_("[ActionOwner] and [Other] commented on his own post");
_("[ActionOwner] commented on her own post");
_("[ActionOwner] and [Others] commented on her own post");
_("[ActionOwner] and [Other] commented on her own post"); 
_("[ActionOwner] commented on their post");
_("[ActionOwner] and [Others] commented on their post");
_("[ActionOwner] and [Other] commented on their post");
_("[ActionOwner] commented on [Owner]'s post");
_("[ActionOwner] and [Others] commented on [Owner]'s post");
_("[ActionOwner] and [Other] commented on [Owner]'s post");
_("[ActionOwner] commented on your post");
_("[ActionOwner] and [Others] commented on your post");
_("[ActionOwner] and [Other] commented on your post");
_("[ActionOwner] commented on the event [TargetName]");
_("[ActionOwner] and [Others] commented on the event [TargetName]");
_("[ActionOwner] and [Other] commented on the event [TargetName]");
_("[ActionOwner] commented on his own event [TargetName]");
_("[ActionOwner] and [Others] commented on his own event [TargetName]");
_("[ActionOwner] and [Other] commented on his own event [TargetName]");
_("[ActionOwner] commented on her own event [TargetName]");
_("[ActionOwner] and [Others] commented on her own event [TargetName]");
_("[ActionOwner] and [Other] commented on her own event [TargetName]");
_("[ActionOwner] commented on your event [TargetName]");
_("[ActionOwner] and [Others] commented on your event [TargetName]");
_("[ActionOwner] and [Other] commented on your event [TargetName]");
_("[ActionOwner] invited people to connect to your channel [TargetName]");
_("[ActionOwner] and [Others] invited people to connect to your channel [TargetName]");
_("[ActionOwner] and [Other] invited people to connect to your channel [TargetName]");
_("[ActionOwner] invited you to join his own event [TargetName]");    
_("[ActionOwner] and [Others] invited you to join his own event [TargetName]");   
_("[ActionOwner] and [Other] invited you to join his own event [TargetName]");   
_("[ActionOwner] invited you to join her own event [TargetName]");   
_("[ActionOwner] and [Others] invited you to join her own event [TargetName]");  
_("[ActionOwner] and [Other] invited you to join her own event [TargetName]"); 
_("[ActionOwner] invited you to join the event [TargetName]");
_("[ActionOwner] and [Others] invited you to join the event [TargetName]");
_("[ActionOwner] and [Other] invited you to join the event [TargetName]");
_("[ActionOwner] invited you to join their own event [TargetName]");
_("[ActionOwner] and [Others] invited you to join their own event [TargetName]");
_("[ActionOwner] and [Other] invited you to join their own event [TargetName]");
_("[ActionOwner] invited you to connect to the channel [TargetName]");
_("[ActionOwner] and [Others] invited you to connect to the channel [TargetName]");
_("[ActionOwner] and [Other] invited you to connect to the channel [TargetName]");
_("[ActionOwner] invited you to connect to his own channel [TargetName]");  
_("[ActionOwner] and [Others] invited you to connect to his own channel [TargetName]"); 
_("[ActionOwner] and [Other] invited you to connect to his own channel [TargetName]"); 
_("[ActionOwner] invited you to connect to her own channel [TargetName]"); 
_("[ActionOwner] and [Others] invited you to connect to her own channel [TargetName]");
_("[ActionOwner] and [Other] invited you to connect to her own channel [TargetName]"); 
_("[ActionOwner] invited people to join your event [TargetName]");
_("[ActionOwner] and [Others] invited people to join your event [TargetName]");
_("[ActionOwner] and [Other] invited people to join your event [TargetName]");
_("[ActionOwner] invited people to connect to your channel [TargetName]");
_("[ActionOwner] and [Others] invited people to connect to your channel [TargetName]");
_("[ActionOwner] and [Other] invited people to connect to your channel [TargetName]");
_("[ActionOwner] invited people to join [Owner]'s event [TargetName]");
_("[ActionOwner] and [Others] invited people to join [Owner]'s event [TargetName]");
_("[ActionOwner] and [Other] invited people to join [Owner]'s event [TargetName]");
_("[ActionOwner] invited people to connect to [Owner]'s channel");
_("[ActionOwner] and [Others] invited people to connect to [Owner]'s channel");
_("[ActionOwner] and [Other] invited people to connect to [Owner]'s channel");
_("[ActionOwner] invited people to his own event [TargetName]");
_("[ActionOwner] and [Others] invited people to his own event [TargetName]");
_("[ActionOwner] and [Other] invited people to his own event [TargetName]");
_("[ActionOwner] invited people to her own event [TargetName]");
_("[ActionOwner] and [Others] invited people to her own event [TargetName]");
_("[ActionOwner] and [Other] invited people to her own event [TargetName]");
_("[ActionOwner] invited people to their event [TargetName]");
_("[ActionOwner] and [Others] invited people to their event [TargetName]");
_("[ActionOwner] and [Other] invited people to their event [TargetName]");
_("[ActionOwner] invited people to connect to their channel [TargetName]");
_("[ActionOwner] and [Others] invited people to connect to their channel [TargetName]");
_("[ActionOwner] and [Other] invited people to connect to their channel [TargetName]");
_("[ActionOwner] shared the video [TargetName]"); 
_("[ActionOwner] and [Others] shared the video [TargetName]"); 
_("[ActionOwner] and [Other] shared the video [TargetName]");  
_("[ActionOwner] shared his own video [TargetName]");         
_("[ActionOwner] and [Others] shared his own video [TargetName]");  
_("[ActionOwner] and [Other] shared his own video [TargetName]"); 
_("[ActionOwner] shared her own video [TargetName]");         
_("[ActionOwner] and [Others] shared her own video [TargetName]");  
_("[ActionOwner] and [Other] shared her own video [TargetName]"); 
_("[ActionOwner] shared their video [TargetName]"); 
_("[ActionOwner] and [Others] shared their video [TargetName]");  
_("[ActionOwner] and [Other] shared their video [TargetName]"); 
_("[ActionOwner] shared [Owner]'s video [TargetName]");       
_("[ActionOwner] and [Others] shared [Owner]'s video [TargetName]");    
_("[ActionOwner] and [Other] shared [Owner]'s video [TargetName]");
_("[ActionOwner] shared your video [TargetName]");        
_("[ActionOwner] and [Others] shared your video [TargetName]");    
_("[ActionOwner] and [Other] shared your video [TargetName]");
_("[ActionOwner] shared the photo [TargetName]"); 
_("[ActionOwner] and [Others] shared the photo [TargetName]"); 
_("[ActionOwner] and [Other] shared the photo [TargetName]");  
_("[ActionOwner] shared his own photo [TargetName]");         
_("[ActionOwner] and [Others] shared his own photo [TargetName]");  
_("[ActionOwner] and [Other] shared his own photo [TargetName]"); 
_("[ActionOwner] shared her own photo [TargetName]");         
_("[ActionOwner] and [Others] shared her own photo [TargetName]");  
_("[ActionOwner] and [Other] shared her own photo [TargetName]");
_("[ActionOwner] shared their photo [TargetName]"); 
_("[ActionOwner] and [Others] shared their photo [TargetName]");  
_("[ActionOwner] and [Other] shared their photo [TargetName]"); 
_("[ActionOwner] shared [Owner]'s photo [TargetName]");       
_("[ActionOwner] and [Others] shared [Owner]'s photo [TargetName]");    
_("[ActionOwner] and [Other] shared [Owner]'s photo [TargetName]");   
_("[ActionOwner] shared your photo [TargetName]");        
_("[ActionOwner] and [Others] shared your photo [TargetName]");    
_("[ActionOwner] and [Other] shared your photo [TargetName]");    
_("[ActionOwner] shared the album [TargetName]");
_("[ActionOwner] and [Others] shared the album [TargetName]");
_("[ActionOwner] and [Other] shared the album [TargetName]");
_("[ActionOwner] shared his own album [TargetName]");         
_("[ActionOwner] and [Others] shared his own album [TargetName]");  
_("[ActionOwner] and [Other] shared his own album [TargetName]");        
_("[ActionOwner] shared her own album [TargetName]");        
_("[ActionOwner] and [Others] shared her own album [TargetName]");   
_("[ActionOwner] and [Other] shared her own album [TargetName]");   
_("[ActionOwner] shared their album [TargetName]");
_("[ActionOwner] and [Others] shared their album [TargetName]");
_("[ActionOwner] and [Other] shared their album [TargetName]");
_("[ActionOwner] shared [Owner]'s album [TargetName]");
_("[ActionOwner] and [Others] shared[Owner]'s album [TargetName]");
_("[ActionOwner] and [Other] shared [Owner]'s album [TargetName]");
_("[ActionOwner] shared your album [TargetName]");
_("[ActionOwner] and [Others] shared your album [TargetName]");
_("[ActionOwner] and [Other] shared your album [TargetName]");
_("[ActionOwner] shared the review");
_("[ActionOwner] and [Others] shared the review");
_("[ActionOwner] and [Other] shared the review");
_("[ActionOwner] shared his own review");        
_("[ActionOwner] and [Others] shared his own review");    
_("[ActionOwner] and [Other] shared his own review");    
_("[ActionOwner] shared her own review");       
_("[ActionOwner] and [Others] shared her own review");     
_("[ActionOwner] and [Other] shared her own review");     
_("[ActionOwner] shared your review");
_("[ActionOwner] and [Others] shared your review");
_("[ActionOwner] and [Other] shared your review");
_("[ActionOwner] shared [Owner]'s review");
_("[ActionOwner] and [Others] shared [Owner]'s review");
_("[ActionOwner] and [Other] shared [Owner]'s review");
_("[ActionOwner] shared the post");
_("[ActionOwner] and [Others] shared the post");
_("[ActionOwner] and [Other] shared the post");
_("[ActionOwner] shared his own post");                
_("[ActionOwner] and [Others] shared his own post");     
_("[ActionOwner] and [Other] shared his own post");     
_("[ActionOwner] shared her own post");                
_("[ActionOwner] and [Others] shared her own post");   
_("[ActionOwner] and [Other] shared her own post");     
_("[ActionOwner] shared their post");
_("[ActionOwner] and [Others] shared their post");
_("[ActionOwner] and [Other] shared their post");
_("[ActionOwner] shared [Owner]'s post");
_("[ActionOwner] and [Others] shared [Owner]'s post");
_("[ActionOwner] and [Other] shared [Owner]'s post");
_("[ActionOwner] shared your post");
_("[ActionOwner] and [Others] shared your post");
_("[ActionOwner] and [Other] shared your post");
_("[ActionOwner] shared the visited location [TargetName]");
_("[ActionOwner] and [Others] shared the visited location [TargetName]");
_("[ActionOwner] and [Other] shared the visited location [TargetName]");
_("[ActionOwner] shared his own visited location [TargetName]"); 
_("[ActionOwner] and [Others] shared his own visited location [TargetName]"); 
_("[ActionOwner] and [Other] shared his own visited location [TargetName]"); 
_("[ActionOwner] shared her own visited location [TargetName]");
_("[ActionOwner] and [Others] shared her own visited location [TargetName]"); 
_("[ActionOwner] and [Other] shared her own visited location [TargetName]"); 
_("[ActionOwner] shared your visited location [TargetName]");
_("[ActionOwner] and [Others] shared your visited location [TargetName]");
_("[ActionOwner] and [Other] shared your visited location [TargetName]");
_("[ActionOwner] shared [Owner]'s visited location [TargetName]");
_("[ActionOwner] and [Others] shared [Owner]'s visited location [TargetName]");
_("[ActionOwner] and [Other] shared [Owner]'s visited location [TargetName]");
_("[ActionOwner] shared the event [TargetName]");
_("[ActionOwner] and [Others] shared the event [TargetName]");
_("[ActionOwner] and [Other] shared the event [TargetName]");
_("[ActionOwner] shared his own event [TargetName]");  
_("[ActionOwner] and [Others] shared his own event [TargetName]"); 
_("[ActionOwner] and [Other] shared his own event [TargetName]"); 
_("[ActionOwner] shared her own event [TargetName]"); 
_("[ActionOwner] and [Others] shared her own event [TargetName]");   
_("[ActionOwner] and [Other] shared her own event [TargetName]");   
_("[ActionOwner] shared your event [TargetName]");
_("[ActionOwner] and [Others] shared your event [TargetName]");
_("[ActionOwner] and [Other] shared your event [TargetName]");
_("[ActionOwner] shared [Owner]'s event [TargetName]");
_("[ActionOwner] and [Others] shared [Owner]'s event [TargetName]");
_("[ActionOwner] and [Other] shared [Owner]'s event [TargetName]");
_("[ActionOwner] shared their channel");
_("[ActionOwner] and [Others] shared their channel");
_("[ActionOwner] and [Other] shared their channel");
_("[ActionOwner] shared [TargetName]'s channel");
_("[ActionOwner] and [Others] shared [TargetName]'s channel");
_("[ActionOwner] and [Other] shared [TargetName]'s channel");
_("[ActionOwner] shared their news");
_("[ActionOwner] and [Others] shared their news");
_("[ActionOwner] and [Other] shared their news");
_("[ActionOwner] shared [Owner]'s news");
_("[ActionOwner] and [Others] shared [Owner]'s news");
_("[ActionOwner] and [Other] shared [Owner]'s news");
_("[ActionOwner] shared their brochure");
_("[ActionOwner] and [Others] shared their brochure");
_("[ActionOwner] and [Other] shared their brochure");
_("[ActionOwner] shared [Owner]'s brochure");
_("[ActionOwner] and [Others] shared [Owner]'s brochure");
_("[ActionOwner] and [Other] shared [Owner]'s brochure");
_("[ActionOwner] shared their event [TargetName]");
_("[ActionOwner] and [Others] shared their event [TargetName]");
_("[ActionOwner] and [Other] shared their event [TargetName]");
_("[ActionOwner] reechoed your echo");
_("[ActionOwner] and [Others] reechoed your echo");
_("[ActionOwner] and [Other] reechoed your echo");