<?php
_( 'The most elegant way to tell your journey');
_( 'Become a Tourist Tuber');
_( 'And get a huge space to store your pictures and videos');
_('Upload your content');
_( 'And share them with your trusted groups');
_( 'Build your Community');
_( 'Text or Video chat with your friends in real time, anywhere');
_( 'Saved briefcases');
_( 'All');
_( 'From');
_( 'To');
_( 'reset');
_( 'add brochure');
_( 'enable shares & comments');
_( 'remove');
_( 'hide');
_( 'edit');
_( 'report');
_( 'hide');
_( 'click to unhide');
_( 'cancel');
_( 'save');
_( 'Load More...');
_( 'Load Previous...');
_( 'likes');
_( 'comments');
_( 'shares');
_( 'LIKES');
_( 'you need to have a');
_( 'TT account');
_( 'in order to like');
_( 'show more');
_( 'COMMENTS');
_( 'write a comment / @T Tuber to reply');
_( 'you need to have a');
_( 'TT account');
_( 'in order to write a comment');
_( 'write a comment / @T Tuber to reply');
_( 'show more');
_( 'SHARES');
_( 'write something');
_( 'write something...');
_( 'write something...');
_( 'share this entry with...');
_( 'connections');
_( 'friends');
_( 'friends\' connections');
_( 'followers');
_( 'custom');
_( 'by mail');
_( 'add people (T tubers, emails)');
_( 'add more');
_( 'add more');
_( 'send');
_( 'share this entry with...');
_( 'friends');
_( 'friends\' connections');
_( 'followers');
_( 'custom');
_( 'by mail');
_( 'you need to have a');
_( 'TT account');
_( 'in order to share this entry.');
_( 'show more');
_( 'From');
_( 'To');
_( 'reset');
_( 'more >');
_( 'edit');
_( 'remove');
_( 'enable shares & comments');
_( 'like');
_( 'comment');
_( 'share');
_( 'rate');
_( 'report');
_( 'Load More...');
_( 'Load Previous...');
_( 'From');
_( 'To');
_( 'reset');
_( 'add news');
_( 'enable shares & comments');
_( 'remove');
_( 'hide');
_( 'edit');
_( 'report');
_( 'hide');
_( 'click to unhide');
_( 'Load More...');
_( 'Load Previous...');
_( 'likes');
_( 'comments');
_( 'shares');
_( 'LIKES');
_( 'you need to have a');
_( 'TT account');
_( 'in order to like');
_( 'show more');
_( 'COMMENTS');
_( 'write a comment / @T Tuber to reply');
_( 'you need to have a');
_( 'TT account');
_( 'in order to write a comment');
_( 'write a comment / @T Tuber to reply');
_( 'write a comment / @T Tuber to reply');
_( 'show more');
_( 'SHARES');
_( 'write something');
_( 'write something');
_( 'write something...');
_( 'share this entry with...');
_( 'connections');
_( 'friends');
_( 'friends\' connections');
_( 'followers');
_( 'custom');
_( 'by mail');
_( 'add people (T tubers, emails)');
_( 'add more');
_( 'send');
_( 'share this entry with...');
_( 'friends');
_( 'friends\' connections');
_( 'followers');
_( 'custom');
_( 'by mail');
_( 'you need to have a');
_( 'TT account');
_( 'in order to share this entry.');
_( 'show more');
_( 'Who can see my connections?');
_( 'public');
_( 'public');
_( 'connections');
_( 'sponsors');
_( 'private');
_( 'private');
_( 'custom');
_( 'add more');
_( 'save');
_( 'edit privacy');
_( 'CONNECTIONS');
_( 'recent videos');
_( 'Categories');
_( 'recently added');
_( 'connections');
_( 'Load More...');
_( 'Load Previous...');
_( 'cancel');
_( 'VIDEOS');
_( 'more >');
_( 'edit');
_( 'remove');
_( 'enable shares & comments');
_( 'like');
_( 'comment');
_( 'share');
_( 'rate');
_( 'report');
_( 'PHOTOS');
_( 'more >');
_( 'enable shares & comments');
_( 'like');
_( 'comment');
_( 'share');
_( 'rate');
_( 'report');
_( 'ALBUMS');
_( 'more >');
_( 'edit');
_( 'remove');
_( 'enable shares & comments');
_( 'like');
_( 'comment');
_( 'share');
_( 'rate');
_( 'report');
_( 'BROCHURES');
_( 'EVENTS');
_( 'location:');
_( 'view event >');
_( 'SUB CHANNELS');
_( 'view');
_( 'tourist tube');
_( 'home');
_( 'home');
_( 'about');
_( 'about');
_( 'careers');
_( 'careers');
_( '360 videos');
_( '360 videos');
_( 'reviews');
_( 'reviews');
_( 'Back To Top');
_( 'click to expand');
_( 'TT.com');
_( 'Pick your next Outing and Rate it !');
_( 'Pick your next Outing and Rate it !');
_( 'TT discover');
_( 'Plan your next Trip');
_( 'Plan your next Trip');
_( 'TT planner');
_( 'Find hotels');
_( 'Find hotels');
_( 'TT hotels');
_( 'Access our partners\' channels');
_( 'Access our partners\' channels');
_( 'TT channels');
_( 'Find Dates');
_( 'Find Dates');
_( 'TT dating');
_( 'Live Cams of your choosing');
_( 'Live Cams of your choosing');
_( 'TT live');
_( 'Express yourself on the fly');
_( 'Express yourself on the fly');
_( 'TT echoes');
_( 'Legal');
_( 'privacy policy');
_( 'terms & conditions');
_( 'disclaimer');
_( 'support & contact');
_( 'customer support');
_( 'contact');
_( 'feedback');
_( 'help');
_( 'report a bug');
_( 'Content');
_( 'videos');
_( 'photos');
_( 'Account Info');
_( 'register');
_( 'sign in');
_( 'create my channel');
_( 'cancel');
_( 'register');
_( 'email');
_( 'your email address');
_( 'username');
_( 'password');
_( 'should be at least 8 characters long');
_( 'and must be a combination of letters and numbers.');
_( 'confirm password');
_( 'submit');
_( 'cancel');
_( 'sign in');
_( 'your email / username');
_( 'password');
_( 'login');
_( 'cancel');
_( 'upload');
_( 'register');
_( 'Welcome');
_( 'All Media');
_( 'Photos');
_( 'Videos');
_( 'Tubers');
_( 'SIGN IN');
_( 'Account Info');
_( 'Friends');
_( 'feeds');
_( 'Photos');
_( 'Videos');
_( 'Albums');
_( 'events');
_( 'journal');
_( 'add to favorites');
_( 'my privacy');
_( 'sign out');
_( 'cancel');
_( 'register');
_( 'register');
_( 'email');
_( 'your email address');
_( 'your email address');
_( 'username');
_( 'password');
_( 'should be at least 8 characters long');
_( 'and must be a combination of letters and numbers.');
_( 'confirm password');
_( 'submit');
_( 'cancel');
_( 'sign in');
_( 'your email / username');
_( 'password');
_( 'login');
_( 'cancel');
_( 'upload');
_( 'register');
_( 'Welcome');
_( 'All Media');
_( 'Photos');
_( 'Videos');
_( 'Tubers');
_( 'SIGN IN');
_( 'Account Info');
_( 'Friends');
_( 'feeds');
_( 'Photos');
_( 'Videos');
_( 'Albums');
_( 'events');
_( 'journal');
_( 'add to favorites');
_( 'my privacy');
_( 'sign out');
_( 'cancel');
_( 'register');
_( 'VIEW REVIEWS');
_( 'VIEW REVIEWS');
_( 'share link');
_( 'your evaluation for this hotel');
_('Terrible');
_('poor');
_('Average');
_('Very good');
_('Excellent');
_( '(100 character maximum)');
_( 'Your review');
_( 'what was the theme of your trip?');
_( 'With kids');
_( 'Outdoors');
_( 'Best of');
_( 'Business');
_( 'Culture');
_( 'Adventure');
_( 'Romantic');
_( 'Gastronomy');
_( 'When did you travel?');
_( 'select one...');
_('I certify that this review is based on my personal experience and is my genuine opinion of this institution');
_( 'anything you could say about it?');
_( 'Terrible');
_( 'poor');
_( 'Average');
_( 'Very good');
_( 'Excellent');
_( "what's near the hotel?");
_( 'you can select more than one');
_( 'UPLOAD PHOTO');
_( 'optional');
_( 'upload');
_( 'upload');
_( 'Submit your review');
_( 'recent reviews');
_( 'myfriendname');
_('Small map');
_( 'SMALL MAP');
_( 'HALF SCREEN');
_( 'FULLSCREEN');
_( 'TT ADVISOR');
_( 'bag');
_( 'To');
_( 'From');
_( 'Check calendar');
_( 'TODAY');
_( 'TUBERS ECHOES');
_( 'Privacy Policy');
_( 'TouristTube, LLC provides a Privacy Policy to describe for you, as a user of our services (i) the information we collect (ii) How that information can be used (iii) with whom it may be shared (iv) your choices on accessing and updating your personal information. TouristTube LLC respects the privacy of our users and has developed this Privacy Policy to demonstrate its commitment to protecting your privacy.');
_( 'When you share information with us by creating a Tourist Tube Account, we can make those services even better - to show you more relevant search results and ads, to help you connect with people or to make sharing with others quicker and easier. You can use our services in different ways - to search for and share information, to communicate with other people or to create new content. As you use our services, we want you to be aware how we use your information and the ways in which you can protect your privacy.');
_( 'By using our website, you are accepting the practices described in this Privacy Policy. Therefore, we encourage you to read this Privacy Policy carefully when using our services or transacting business with us.');
_( 'If you have any questions about our privacy practices, please refer to details at the end of this Privacy Policy to contact us.');
_( '(i) Information we collect');
_( 'We may collect personal information that can identify you, such as your name and email address, and other information that does not identify you. When you provide personal information through our website, the information may be sent to servers located in the United States and other countries around the world. Information can be collected in two ways:');
_( 'Information you provide to us. For example, many of our services require you to sign up for a Tourist Tube Account. When you do, you will be asked for personal information, such as your name, email address, telephone number or credit card. If you want to take full advantage of the sharing features we offer, you may be asked to create a publicly visible profile which may include your name and photo.');
_( 'Information we get from the use of our services. We may collect information about the services that you use and how you use them, like when you visit a website that uses our advertising services or you view and interact with our ads and content. This information includes:');
_( 'Device information');
_( 'We may collect device-specific information (such as your hardware model, operating system version, unique device identifiers, and mobile network information including phone number). Tourist Tube may associate your device identifiers or phone number with your Tourist Tube Account.');
_( 'Log information');
_( 'When you use our services or view content provided by Tourist Tube, we may automatically collect and store certain information in server logs. This may include:');
_( 'Details of how you used our service, such as your search queries.');
_( 'Telephony log information like your phone number, calling-party number, forwarding numbers, time and date of calls, duration of calls, SMS routing information and types of calls.');
_( 'Internet protocol address.');
_( 'Device event information such as crashes, system activity, hardware settings, browser type, browser language, the date and time of your request and referral URL.');
_( 'Cookies that may uniquely identify your browser or your Tourist Tube Account.');
_( 'Location information');
_( 'When you use a location-enabled Tourist Tube service, we may collect and process information about your actual location, like GPS signals sent by a mobile device. We may also use various technologies to determine location, such as sensor data from your device that may, for example, provide information on nearby Wi-Fi access points and cell towers.');
_( 'Unique application numbers');
_( 'Certain services include a unique application number. This number and information about your installation (for example, the operating system type and application version number) may be sent to Tourist Tube when you install or uninstall that service or when that service periodically contacts our servers, such as for automatic updates.');
_( 'Local storage');
_( 'We may collect and store information (including personal information) locally on your device using mechanisms such as browser web storage (including HTML 5) and application data caches.');
_( 'Cookies and anonymous identifiers');
_( 'We use various technologies to collect and store information when you visit a Tourist Tube service, and this may include sending one or more cookies or anonymous identifiers to your device. We also use cookies and anonymous identifiers when you interact with services we offer to our partners, such as advertising services or Tourist Tube features that may appear on other sites.');
_( '(ii) How we use information we collect');
_( 'We may use information that we collect about you in general to:');
_( 'deliver the products and services that you have requested;');
_( 'manage your account and provide you with customer support;');
_( 'perform research and analysis about your use of, or interest in, our products, services, or content, or products, services or content offered by others;');
_( 'communicate with you by e-mail, postal mail, telephone and/or mobile devices about products or services that may be of interest to you either from us or other third parties;');
_( 'develop and display content and advertising tailored to your interests on our site and other sites;');
_( 'verify your eligibility and deliver prizes in connection with contests and sweepstakes;');
_( 'enforce our terms and conditions;');
_( 'manage our business and');
_( 'perform functions as otherwise described to you at the time of collection.');
_( 'We use the information we collect from all of our services to provide, maintain, protect and improve them, to develop new ones, and to protect Tourist Tube and our users. We also use this information to offer you tailored content - like giving you more relevant search results and ads.');
_( 'We may use the name you provide for your Tourist Tube Profile across all of the services we offer that require a Tourist Tube Account. In addition, we may replace past names associated with your Tourist Tube Account so that you are represented consistently across all our services. If other users already have your email, or other information that identifies you, we may show them your publicly visible Tourist Tube Profile information, such as your name and photo.');
_( 'When you contact Tourist Tube, we may keep a record of your communication to help solve any issues you might be facing. We may use your email address to inform you about our services, such as letting you know about upcoming changes or improvements.');
_( 'We will ask for your consent before using information for a purpose other than those that are set out in this Privacy Policy.');
_( '(iii) With whom we share your information');
_( 'We ask you to be aware when and with whom we may share personal or other information we have collected about you or your activities on our website or while using our services.');
_( 'We do not share your personal information prior to your consent except with the following parties:');
_( 'Authorized service providers: We may share your personal information with our authorized service providers that perform certain services on our behalf. These services may include fulfilling orders, processing credit card payments, delivering packages, providing customer service and marketing assistance, performing business and sales analysis, supporting our website functionality, and supporting contests, sweepstakes, surveys and other features offered through our website. These service providers may have access to personal information needed to perform their functions but are not permitted to share or use such information by themselves for any other purposes.');
_( 'Direct mail partners: From time to time we may share our postal mailing list with selected providers of goods and services that you may be interested in. If you prefer not to receive mailings from these providers, you can notify us at any time.');
_( 'Other Situations: We also may disclose your information:');
_( 'In response to a subpoena or similar investigative demand, a court order, or a request for cooperation from law enforcement or other government agency; to establish or exercise our legal rights; to defend against legal claims; or as otherwise required by law. In such cases, we may raise or waive any legal objection or right available to us, in our sole discretion.');
_( 'When we believe disclosure is appropriate in connection with efforts to investigate, prevent, report or take other action regarding illegal activity, suspected fraud or other wrongdoing; to protect and defend the rights, property or safety of our company, our users, our employees, or others; to comply with applicable law or cooperate with law enforcement; or to enforce our website terms and conditions or other agreements or policies.');
_( 'In connection with a substantial corporate transaction, such as the sale of our business, a divestiture, merger, consolidation, or asset sale, or in the unlikely event of bankruptcy.');
_( 'Any third parties to whom we may disclose personal information may have their own privacy policies which describe how they use and disclose personal information. Those policies will govern use, handling and disclosure of your personal information once we have shared it with those third parties as described in this Privacy Policy. If you want to learn more about their privacy practices, we encourage you to visit the websites of those third parties.');
_( 'We may also share aggregated and non-personal information we collect under any of the above circumstances with third parties companies to develop and deliver targeted advertising on our websites and on websites of third parties. We may combine non-personal information we collect with additional non-personal information collected from other sources. We also may share aggregated information with third parties, including advisors, advertisers and investors, for the purpose of conducting general business analysis. For example, we may tell our advertisers the number of visitors to our website and the most popular features or services accessed. This information does not contain any personal information and may be used to develop website content and services that we hope you and other users will find of interest and to target content and advertising.');
_( '(iv) Your choices on accessing and updating personal information');
_( 'Many of our services let you share information with others. Remember that when you share information publicly, it may be indexable by search engines. Our services provide you with different options on sharing and removing your content.');
_( 'People have different privacy concerns. Our goal is to be clear about what information we collect, so that you can make meaningful choices about how it is used. For example, you can:');
_( 'Review and control certain types of information tied to your Tourist Tube Account.');
_( 'Use our editor to see and adjust how your Tourist Tube Profile appears to particular individuals.');
_( 'Control who you share information with.');
_( 'Take information out of many of our services.');
_( 'Whenever you use our services, we aim to provide you with access to your personal information. If that information is wrong, we strive to give you ways to update it quickly or to delete it - unless we have to keep that information for legitimate business or legal purposes. When updating your personal information, we may ask you to verify your identity before we can act on your request.');
_( 'Where we can provide information access and correction, we will do so for free, except where it would require a disproportionate effort. We aim to maintain our services in a manner that protects information from accidental or malicious destruction. Hence, after you delete information from our services, we may not immediately delete residual copies from our active servers and may not remove information from our backup systems.');
_( 'Security');
_( 'We make sure to protect Tourist Tube and our users from unauthorized access to or unauthorized alteration, disclosure or destruction of information we hold. Therefore, we undertake to:');
_( 'Encrypt many of our services using SSL.');
_( 'Offer you two-step verification when you access your Tourist Tube Account.');
_( 'Review our information collection, storage and processing practices, including physical security measures, to guard against unauthorized access to systems.');
_( 'Restrict access to personal information to Tourist Tube employees, contractors and agents who need to know that information in order to process it for us, and who are subject to strict contractual confidentiality obligations and may be disciplined or terminated if they fail to meet these obligations.');
_( 'Enforcement');
_( 'We regularly review our compliance with our Privacy Policy and we also adhere to several self-regulatory frameworks. Furthermore, when we receive formal written complaints, we will contact the complaining person to follow up. We work with the appropriate regulatory authorities, including local data protection authorities, to resolve any complaints regarding the transfer of personal data that we cannot resolve with our users directly.');
_( 'Changes');
_( 'Our Privacy Policy may change be subject to changes. Albeit, we will not reduce your rights under this Privacy Policy without your explicit consent. Any upcoming privacy policy changes will be posted on the current page. If the changes are significant, we will be providing a more prominent notice (including, for certain services, email notification of privacy policy changes). All the prior versions of this Privacy Policy will be kept for your review.');
_( 'Contact Us');
_( 'If you have any questions about this Privacy Policy or our information-handling practices, or if you would like to request information about our disclosure of personal information to third parties for their direct marketing purposes, please contact us by email or postal mail as follows:');
_('cancel');
_( 'VIEW REVIEWS');
_( 'VIEW REVIEWS');
_( 'share link');
_( 'your evaluation for this restaurant');
_( '(100 character maximum)');
_( 'Your review');
_( 'what was the theme of your trip?');
_( 'With kids');
_( 'Outdoors');
_( 'Best of');
_( 'Business');
_( 'Culture');
_( 'Adventure');
_( 'Romantic');
_( 'Gastronomy');
_( 'When did you travel?');
_( 'select one...');
_('I certify that this review is based on my personal experience and is my genuine opinion of this institution');
_('I certify that this review is based on my personal experience and is my genuine opinion of this institution');
_( 'anything you could say about it?');
_( 'Terrible');
_( 'poor');
_( 'Average');
_( 'Very good');
_( 'Excellent');
_( "what's near the restaurant?" );
_( 'you can select more than one');
_( 'UPLOAD PHOTO');
_( 'optional');
_( 'upload');
_( 'upload');
_( 'Submit your review');
_( 'recent reviews');
_( 'SEARCH');
_( 'time');
_( 'Search');
_( 'Reviews');
_( 'View or add a review about hotel, point of interest, or restaurant you visited.');
_( 'what would you like to review?');
_( 'Enter hotel name');
_( 'Hotel');
_( 'Enter restaurant name');
_( 'Restaurant');
_( 'Enter point of interest name');
_( 'Point of interest');
_( 'Enter hotel name');
_( 'VIEW REVIEWS');
_( 'VIEW REVIEWS');
_( 'share link');
_( 'your evaluation for this point of interest');
_( '(100 character maximum)');
_( 'Your review');
_( 'what was the theme of your trip?');
_( 'With kids');
_( 'Outdoors');
_( 'Best of');
_( 'Business');
_( 'Culture');
_( 'Adventure');
_( 'Romantic');
_( 'Gastronomy');
_( 'When did you travel?');
_( 'select one...');
_('I certify that this review is based on my personal experience and is my genuine opinion of this institution');
_('I certify that this review is based on my personal experience and is my genuine opinion of this institution');
_( 'anything you could say about it?');
_( 'Terrible');
_( 'poor');
_( 'Average');
_( 'Very good');
_( 'Excellent');
_( "what's near the point of interest?");
_( 'you can select more than one');
_( 'UPLOAD PHOTO');
_( 'optional');
_( 'upload');
_( 'upload');
_( 'Submit your review');
_( 'recent reviews');
_( 'REVIEWS');
_( 'Back to results');
_( 'Professional photos');
_( 'uploaded by tubers');
_( 'time');
_( 'selected');
_( 'Search');
_( 'load more');
_( 'Professional photos');
_( 'uploaded by tubers');
_('SEARCH OPTIONS');
_( 'Room Type');
_( 'Max');
_( 'Avg. Price');
_( 'REVIEWS');
_( 'ABOUT');
_( 'more');
_( 'more');
_( 'Tuber Evaluation');
_( 'Terrible');
_( 'poor');
_( 'Average');
_( 'Very good');
_( 'Excellent');
_( 'to');
_( 'followers');
_( 'SEARCH');
_( 'time');
_( 'What is your Budget ?');
_( 'Advanced search');
_( 'Search');
_( 'view');
_( 'SUGGESTED RESTAURANTS');
_( 'In a few words ...');
_( 'REVIEWS');
_('Restaurant, Bar, 24-Hour Front Desk, Newspapers, Terrace, Non-smoking Rooms, Facilities for Disabled Guests, Elevator, Safe, Heating, Baggage Storage, Air Conditioning');
_( 'Services');
_( 'Meeting/Banquet Facilities, Business Center, Babysitting/Child Services, Laundry, Dry Cleaning, Ironing Service, Currency Exchange, Bicycle Rental, Fax/Photocopying, Ticket Service, Concierge Service');
_( 'Internet');
_( 'Free! Wi-Fi is available in the hotel rooms and is free of charge.');
_( 'Parking');
_( 'Public parking is available at a location nearby (reservation is not needed) and costs EUR 19 per day.');
_( 'time');
_( 'selected');
_( 'Search');
_( 'Share This Restaurant');
_( 'write something');
_( 'write something ...');
_( 'add people (T tubers, emails)');
_( 'friends');
_( 'followers');
_( 'cancel');
_( 'save');
_( 'Or add your new');
_( 'or');
_('SMALL MAP');
_('HALF SCREEN');
_('FULLSCREEN');
_('DISCOVER YOUR DESTINATION');
_('search');
_('T Discover');
_('A helpful tool for anyone who is making travel plans.');
_('Discover a new country,');
_('Save your favorite restaurants, hotels and touristic places');
_('Things to do');
_('The best things to do in any desired city, including events, festivals, attractions & tours, free activities and entertainment');
_('Restaurants, bars, hotels, arts & culture, shopping guide, nightlife ...');
_('CITY SEARCH');
_('search');
_('pack your tt bag');
_('Top 8 Things to do in Paris');
_('TOP 8 THINGS TO DO IN PARIS');
_('Here is our suggestion of the top 10 things to do in Paris .');
_('Discover Destinations and Plan your Trip');
_( 'Hotels');
_( 'Restaurants');
_( 'Photos | Videos');
_( 'Channels');
_( 'Search anything to organize your trip');
_( 'Find');
_( 'The best things to do in any desired city, including attractions & tours, free activities and entertainment');
_( 'View or add a review about hotels, points of interest, airports, or restaurants you visited.');
_( 'join our online ACTIVE community');
_( 'join online');
_( 'The best things to do in any desired city, including attractions & tours, free activities and entertainment');
_( 'create channel');
_( 'CREATE YOUR CHANNEL');
_( 'The best things to do in any desired city, including attractions & tours, free activities and entertainment');
_( '...that’s what it takes');
_( 'A helpful tool for anyone who is making travel plans.');
_( 'Discover a new country, save your favorite restaurants, hotels and touristic places');
_( 'plan your trip');
_( 'Get recommendations from your trusted contacts and from experts on best trips with TT Planner .');
_( 'Excursions, eating & drinking, shops, attractions,..everything’s ready; So pack and go!');
_( 'Review and rate');
_( 'Pick your next Outing and Rate it! Choose places for everyday going out with TT Discover and share you appreciations of restaurants, hotels, and venues you visited with Reviews and Ratings.');
_( 'Upload your photos & videos');
_( 'Become a Tourist Tuber');
_( 'Upload your content');
_( 'Build your Community');
_( 'Share your precious moments travel plans.');
_( 'media');
_( 'million of photos and videos by travelers from all over the world');
_( 'Get recommendations from your trusted contacts and from experts on best trips with TT Planner .');
_( 'Excursions, eating & drinking, shops, attractions,..everything’s ready;');
_( 'So pack and go!');
_( 'explore');
_( 'traveler blog');
_( 'the capital of Gastronomy');
_( 'It is difficult to try to define Parisian gastronomy because the capital devours with gourmandise wines and exotic delicacies. However, it is in the bakery that one really feels the beating heart of the capital. Cradle of the “baguette” which was invented in the XVIth century, it will migrate to the province only towards the middle of the XXth century. As to Parisian patisserie, it exalts light pastes...');
_( 'click to read more');
_( 'popular destinations');
_( 'places to stay');
_( 'Your browser does not support the video tag.');
_( 'best food to eat');
_( 'follow us on');
_( 'Copyright Tourist Tube all rights reserved.');
_( 'disclaimer');
_( 'terms & conditions');
_( 'privacy policy');
_( 'contact us');
_( 'about us');
_( 'traveler blog');
_( 'review & rate');
_( 'faq');
_( 'help');
_( 'support');
_( 'live cam');
_( 'tourist Echoes');
_( 'what’s in my');
_( 'tt bag?');
_( 'Destination:');
_( 'support');
_( 'ACCOUNT INFO');
_( 'Who can see this?');
_( 'describe yourself');
_( 'if you have a website, enter the URL in the field below');
_( 'employment');
_( 'education');
_( 'display username instead of full name');
_( 'Interested in');
_( 'do not display day and month');
_( 'do not display year');
_( 'do not display');
_( 'rather not to say');
_( 'hometown');
_( 'current country');
_( 'current city');
_( 'Interested in sharing your Tourist Tube posts with your favorite social networking websites?');
_( 'Just set up a connection between Tourist Tube and your favorite service and let the sharing begins!');
_( 'add live cam');
_( 'most visited cams');
_( 'most searched cams');
_( 'Restaurants, bars, hotels, arts & culture, shopping guide, nightlife …');
_( 'BEST OF TOURIST TUBE');
_( 'Discover a new country, save your favorite restaurants, hotels and touristic places');
_( 'Trending Destinations');
_( 'Search for a friend to chat with….');
_( 'likes');
_( 'the experience you share is highly appreciated by other travelers');
_( 'ADD to my channel');
_( 'MY UPLOADED PHOTOS');
_( 'Best of');
_( 'account settings');
_( 'username (edit)');
_( 'old password');
_( 'learn more');
_( 'Are you sure you want to delete your account? This action cannot be undone.');
_( 'delete my account');
_( 'deactivate my account');
_( 'deactivate temporarily');
_( 'stop receiving future emails from tourist tube ');
_( 'send Invitation');
_( 'recipient email address');
_( 'sent Invitations');
_( 'contact privacy');
_( 'who can look me up?');
_( 'my profile appears in search engines');
_( 'switch on');
_( 'switch off');
_( 'block users');
_( 'Once you block someone, he or she can no longer be your friend on tourist tube or interact with you');
_( 'add tubers to your block list');
_( 'type tuber name');
_( 'content privacy');
_( 'Allow on my TT page');
_( 'Likes and rates');
_( 'shares and comments');
_( 'Show on my TT page');
_( 'channels I created');
_( "My TChannels' events");
_( "Events' privacy");
_( 'Who can post on my TT page?');
_( 'Who can see');
_( 'my friends list?');
_( 'my followers list?');
_( 'my followings list?');
_( 'My visited places');
_( 'hide all from tuber list');
_( "remove tuber(s) or channel(s) you already added to your (hide all from tuber's or channel's list) by clicking on the X next to their name");
_( 'Tubers/Tchannels introuvables');
_( 'pack all what you need for your trip');
_( 'add');