CREATE TABLE `aircraft_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `wake` CHAR(1) NULL,
  `iata_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_iata_code` (`iata_code` ASC));

  
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (1,'Fokker','100','M','100');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (2,'BAe','146-100','M','141');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (3,'BAe','146-200','M','142');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (4,'BAe','146-300','M','143');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (5,'BAe','146','M','146');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (6,'BAe','146 Freighter (-100/200/300QT & QC)','M','14F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (7,'BAe','146 Freighter (-100QT & QC)','M','14X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (8,'BAe','146 Freighter (-200QT & QC)','M','14Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (9,'BAe','146 Freighter (-300QT & QC)','M','14Z');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (10,'Airbus','A310','H','310');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (11,'Airbus','A310-200','H','312');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (12,'Airbus','A310-300','H','313');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (13,'Airbus','A318','M','318');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (14,'Airbus','A319','M','319');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (15,'Airbus','A310F','M','31F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (16,'Airbus','A310-200F','M','31X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (17,'Airbus','A310-300F','M','31Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (18,'Airbus','A320-100/200','M','320');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (19,'Airbus','A321-100/200','M','321');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (20,'Airbus','A320 (sharklets)','M','32A');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (21,'Airbus','A321 (sharklets)','M','32B');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (22,'Airbus','A318 (sharklets)','M','32C');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (23,'Airbus','A319 (sharklets)','M','32D');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (24,'Airbus','A330','H','330');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (25,'Airbus','A330-200','H','332');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (26,'Airbus','A330-300','H','333');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (27,'Airbus','A330 Freighter','H','33F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (28,'Airbus','A330-200 Freighter','H','33X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (29,'Airbus','A340','H','340');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (30,'Airbus','A340-200','H','342');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (31,'Airbus','A340-300','H','343');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (32,'Airbus','A340-500','H','345');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (33,'Airbus','A340-600','H','346');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (34,'Airbus','A350-1000','H','351');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (35,'Airbus','A350-800','H','358');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (36,'Airbus','A350-900','H','359');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (37,'Airbus','A380','H','380');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (38,'Boeing','707-300','H','703');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (39,'Boeing','707/720','H','707');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (40,'Boeing','707 Freighter','H','70F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (41,'Boeing','707 Combi','H','70M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (42,'Boeing','717','M','717');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (43,'Boeing','727-100','M','721');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (44,'Boeing','727-200','M','722');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (45,'Boeing','727','M','727');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (46,'Boeing','727-100 Mixed','M','72B');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (47,'Boeing','727-200 Mixed','M','72C');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (48,'Boeing','727 Freighter (-100/200)','M','72F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (49,'Boeing','727 Combi','M','72M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (50,'Boeing','727-200 Adv.','M','72S');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (51,'Boeing','727-100 Freighter','M','72X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (52,'Boeing','727-200 Freighter','M','72Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (53,'Boeing','737-100','M','731');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (54,'Boeing','737-200','M','732');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (55,'Boeing','737-300','M','733');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (56,'Boeing','737-400','M','734');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (57,'Boeing','737-500','M','735');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (58,'Boeing','737-600','M','736');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (59,'Boeing','737','M','737');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (60,'Boeing','737-800','M','738');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (61,'Boeing','737-900','M','739');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (62,'Boeing','737-300 (winglets)','M','73C');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (63,'Boeing','737 Freighter','M','73F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (64,'Boeing','737-700','M','73G');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (65,'Boeing','737-800 (winglets)','M','73H');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (66,'Boeing','737-900 (winglets)','M','73J');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (67,'Boeing','737-200 Combi','M','73M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (68,'Boeing','737-700 (winglets)','M','73W');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (69,'Boeing','737-200 Freighter','M','73X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (70,'Boeing','737-300 Freighter','M','73Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (71,'Boeing','747-100','H','741');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (72,'Boeing','747-200','H','742');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (73,'Boeing','747-300','H','743');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (74,'Boeing','747-400','H','744');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (75,'Boeing','747','H','747');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (76,'Boeing','747-200 Combi','H','74C');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (77,'Boeing','747-300 Combi','H','74D');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (78,'Boeing','747-400 Combi','H','74E');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (79,'Boeing','747 Freighter','H','74F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (80,'Boeing','747-8i','H','74H');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (81,'Boeing','747-400 (Domestic)','H','74J');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (82,'Boeing','747SP','H','74L');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (83,'Boeing','747 Combi','H','74M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (84,'Boeing','747-8F','H','74N');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (85,'Boeing','747SR','H','74R');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (86,'Boeing','747-100 Freighter','H','74T');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (87,'Boeing','747-300 / 747-200 SUD Freighter','H','74U');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (88,'Boeing','747SR Freighter','H','74V');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (89,'Boeing','747-200 Freighter','H','74X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (90,'Boeing','747-400 Freighter','H','74Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (91,'Boeing','757-200','H','752');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (92,'Boeing','757-300','H','753');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (93,'Boeing','757','H','757');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (94,'Boeing','757 Freighter','H','75F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (95,'Boeing','757 Mixed','H','75M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (96,'Boeing','757-300 (winglets)','H','75T');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (97,'Boeing','757-200 (winglets)','H','75W');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (98,'Boeing','767-200','H','762');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (99,'Boeing','767-300','H','763');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (100,'Boeing','767-400','H','764');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (101,'Boeing','767','H','767');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (102,'Boeing','767 Freighter','H','76F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (103,'Boeing','767-300 (winglets)','H','76W');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (104,'Boeing','767-200 Freighter','H','76X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (105,'Boeing','767-300 Freighter','H','76Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (106,'Boeing','777-200','H','772');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (107,'Boeing','777-300','H','773');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (108,'Boeing','777','H','777');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (109,'Boeing','777 Freighter','H','77F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (110,'Boeing','777-200LR','H','77L');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (111,'Boeing','777-300ER','H','77W');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (112,'Boeing','787-8','H','788');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (113,'Boeing','787-9','H','789');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (114,'Antonow / Antonov','An-26','L','A26');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (115,'Antonow / Antonov','An-28 / PZL Mielec M-28','L','A28');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (116,'Antonow / Antonov','An-30','L','A30');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (117,'Antonow / Antonov','An-32','L','A32');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (118,'Antonow / Antonov','An-140','M','A40');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (119,'Antonow / Antonov','An-124','H','A4F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (120,'Airbus','A300','H','AB3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (121,'Airbus','A300B2/B4/C4','H','AB4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (122,'Airbus','A300-600','H','AB6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (123,'Airbus','A300-600ST Beluga','H','ABB');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (124,'Airbus','A300F','H','ABF');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (125,'Airbus','A300C4/F4 Freighter','H','ABX');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (126,'Airbus','A300-600F','H','ABY');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (127,'Rockwell','Commander/Turbo Commander','L','ACD');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (128,'Rockwell','Commander','L','ACP');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (129,'Agusta / AgustaWestland','A-109',NULL,'AGH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (130,'Antonow / Antonov','An-24','M','AN4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (131,'Antonow / Antonov','An-26 / An-30 / An-32','M','AN6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (132,'Antonow / Antonov','An-72 / An-74','M','AN7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (133,'Antonow / Antonov','An-12','M','ANF');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (134,'Eurocopter','SA330 Puma / AS332 Super Puma',NULL,'APH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (135,'BAe','Avro RJ100','M','AR1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (136,'BAe','Avro RJ70','M','AR7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (137,'BAe','Avro RJ85','M','AR8');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (138,'BAe','Avro RJ70 / RJ85 / RJ100','M','ARJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (139,'ATR','ATR 42-300 / 320','M','AT4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (140,'ATR','ATR 42-500','M','AT5');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (141,'ATR','ATR 72','M','AT7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (142,'BAe','ATP','M','ATP');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (143,'ATR','ATR 42 / ATR 72','M','ATR');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (144,'BAC','One Eleven','M','B11');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (145,'BAC','One Eleven 200','M','B12');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (146,'BAC','One Eleven 300','M','B13');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (147,'BAC','One Eleven 400/47','M','B14');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (148,'BAC','One Eleven 500','M','B15');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (149,'Boeing','720B','M','B72');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (150,'Beech','1900/1900C/1900D','M','BE1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (151,'Beech','Beech twin piston','L','BE2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (152,'Beech','Beech light aircraft','L','BEC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (153,'Beech','1900D','M','BEH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (154,'Beech','Beech singe piston','L','BEP');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (155,'Beech','1900/1900C','M','BES');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (156,'Beech','Beech twin turboprop','L','BET');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (157,'Bell Helicopter','Bell Helicopters',NULL,'BH2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (158,'Britten Norman','BN-2A/B Islander','L','BNI');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (159,'Britten Norman','BN-2A Mk III Trislander','L','BNT');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (160,'Canadair','Challenger','M','CCJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (161,'Bombardier','Global Express','M','CCX');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (162,'GAF','N22B / N24A Nomad','L','CD2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (163,'Canadair','CL-44','M','CL4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (164,'Cessna','Cessna single piston engine','L','CN1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (165,'Cessna','Cessna twin piston engines','L','CN2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (166,'Cessna','Cessna light aircraft','L','CNA');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (167,'Cessna','Cessna single turboprop engine','L','CNC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (168,'Cessna','Citation','L','CNJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (169,'Cessna','Cessna twin turboprop engines','L','CNT');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (170,'Canadair','CRJ 100','M','CR1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (171,'Canadair','CRJ 200','M','CR2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (172,'Canadair','CRJ 700','M','CR7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (173,'Canadair','CRJ 900','M','CR9');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (174,'Canadair','CRJ 705','M','CRA');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (175,'Canadair','CRJ Freighter','M','CRF');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (176,'Canadair','CRJ','M','CRJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (177,'Canadair','CRJ 1000','M','CRK');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (178,'Sud-Est','SE.210 Caravelle','M','CRV');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (179,'Bombardier','CSeries CS100','M','CS1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (180,'CASA','212 Aviocar','M','CS2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (181,'Bombardier','CSeries CS300','M','CS3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (182,'Airtech','CN-235','M','CS5');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (183,'Convair','CV-440 Metropolitan','M','CV4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (184,'Convair','CV-580','M','CV5');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (185,'Convair','CV-240 / 440 / 580 / 600 / 640 Freighter','M','CVF');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (186,'Convair','CV-240 / 440 / 580 / 600 / 640','M','CVR');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (187,'Convair','CV-240 Freighter','M','CVV');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (188,'Convair','CV-440 Freighter','M','CVX');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (189,'Convair','CV-580 / 600 / 640 Freighter','M','CVY');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (190,'Curtiss','C-46 Commando','M','CWC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (191,'Douglas','DC-10','H','D10');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (192,'Douglas','DC-10-10/15','H','D11');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (193,'Douglas','DC-10-30/40','H','D1C');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (194,'Douglas','DC-10 Freighter','H','D1F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (195,'Douglas','DC-10 Combi','H','D1M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (196,'Douglas','DC-10-10 Freighter','H','D1X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (197,'Douglas','DC-10-30 / 40 Freighter','H','D1Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (198,'Dornier','Do 228','L','D28');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (199,'Dornier','Do 328','M','D38');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (200,'Douglas','DC-3 Freighter','M','D3F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (201,'Douglas','DC-6A/B/C Freighter','M','D6F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (202,'Douglas','DC-8 Freighter','H','D8F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (203,'Douglas','DC-8-62','H','D8L');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (204,'Douglas','DC-8 Combi','H','D8M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (205,'Douglas','DC-8-72','H','D8Q');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (206,'Douglas','DC-8-50 Freighter','H','D8T');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (207,'Douglas','DC-8-61 / 62 / 63 Freighter','H','D8X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (208,'Douglas','DC-8-71 / 72 / 73 Freighter','H','D8Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (209,'Douglas','DC-9-10','M','D91');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (210,'Douglas','DC-9-20','M','D92');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (211,'Douglas','DC-9-30','M','D93');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (212,'Douglas','DC-9-40','M','D94');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (213,'Douglas','DC-9-50','M','D95');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (214,'Douglas','DC-9-30 Freighter','M','D9C');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (215,'Douglas','DC-9 Freighter','M','D9F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (216,'Douglas','DC-9-10 Freighter','M','D9X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (217,'Douglas','DC-3','M','DC3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (218,'Douglas','DC-6A/B','M','DC6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (219,'Douglas','DC-8','H','DC8');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (220,'Douglas','DC-9','M','DC9');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (221,'Dassault','Falcon 10 / 100 / 20 / 200 / 2000','M','DF2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (222,'Dassault','Falcon 50 / 900','M','DF3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (223,'Dassault','Falcon','M','DFL');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (224,'De Havilland Canada','DHC-8-100 Dash 8 / 8Q','M','DH1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (225,'De Havilland Canada','DHC-8-200 Dash 8 / 8Q','M','DH2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (226,'De Havilland Canada','DHC-8-300 Dash 8 / 8Q','M','DH3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (227,'De Havilland Canada','DHC-8-400 Dash 8Q','M','DH4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (228,'De Havilland Canada','DHC-7 Dash 7','M','DH7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (229,'De Havilland Canada','DHC-8 Dash 8','M','DH8');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (230,'De Havilland Canada','DHC-2 Beaver / Turbo Beaver','L','DHB');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (231,'De Havilland Canada','DHC-4 Caribou','M','DHC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (232,'De Havilland','DH.104 Dove','L','DHD');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (233,'De Havilland','DH.114 Heron','L','DHH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (234,'De Havilland Canada','DHC-3 Turbo Otter','L','DHL');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (235,'De Havilland Canada','DHC-3 Otter / Turbo Otter','L','DHO');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (236,'De Havilland Canada','DHC-2 Beaver','L','DHP');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (237,'De Havilland Canada','DHC-2 Turbo-Beaver','L','DHR');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (238,'De Havilland Canada','DHC-3 Otter','L','DHS');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (239,'De Havilland Canada','DHC-6 Twin Otter','L','DHT');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (240,'EMBRAER','EMB 170 / EMB 175','M','E70');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (241,'EMBRAER','EMB 190 / EMB 195','M','E90');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (242,'EMBRAER','EMB 120 Brasilia','L','EM2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (243,'EMBRAER','EMB 110 Bandeirante','M','EMB');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (244,'EMBRAER','EMB 170 / EMB 190','M','EMJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (245,'EMBRAER','ERJ 135','M','ER3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (246,'EMBRAER','ERJ 145','M','ER4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (247,'EMBRAER','ERJ 140','M','ERD');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (248,'EMBRAER','ERJ 135 / ERJ 140 / ERJ 145','M','ERJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (249,'Fokker','F28 Fellowship 1000','M','F21');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (250,'Fokker','F28 Fellowship 2000','M','F22');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (251,'Fokker','F28 Fellowship 3000','M','F23');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (252,'Fokker','F28 Fellowship 4000','M','F24');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (253,'Fokker','F27 Friendship','M','F27');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (254,'Fokker','F28 Fellowship','M','F28');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (255,'Fokker','50','M','F50');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (256,'Fokker','70','M','F70');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (257,'Fairchild-Hiller','FH-227','M','FK7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (258,'Dornier','328JET','M','FRJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (259,'Grumman','G-21 Goose','L','GRG');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (260,'Gulfstream','G-1159 Gulfstream II / III / IV / V','M','GRJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (261,'Gulfstream','G-73 Turbo Mallard','L','GRM');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (262,'Gulfstream','G-159 Gulfstream I','M','GRS');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (263,'Hawker-Siddeley','HS.125','M','H25');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (264,'Helio','H-250 Courier / H-295 / 385 Super Courier','L','HEC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (265,'BAe','HS.748','M','HS7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (266,'Ilyushin','IL-114','M','I14');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (267,'Ilyushin','IL-96-300','H','I93');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (268,'Ilyushin','IL-96 Freighter','H','I9F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (269,'Ilyushin','IL-96M','H','I9M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (270,'Ilyushin','IL-96-300 Freighter','H','I9X');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (271,'Ilyushin','IL-96T Freighter','H','I9Y');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (272,'Ilyushin','IL-62','H','IL6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (273,'Ilyushin','IL-76','H','IL7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (274,'Ilyushin','IL-18','M','IL8');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (275,'Ilyushin','IL-96','H','IL9');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (276,'Ilyushin','IL-86','H','ILW');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (277,'BAe','Jetstream 31','L','J31');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (278,'BAe','Jetstream 32','L','J32');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (279,'BAe','Jetstream 41','M','J41');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (280,'BAe','Jetstream 31 / 32 / 41','L','JST');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (281,'Junkers','Ju 52/3M','M','JU5');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (282,'Lockheed','L-1011 Tristar','H','L10');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (283,'Lockheed','L-1011 1 / 50 / 100 / 150 / 200 / 250 Tr','H','L11');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (284,'Lockheed','L-1011 500 Tristar','H','L15');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (285,'Lockheed','L-1011 Tristar Freighter','H','L1F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (286,'Lockheed','L-1049 Super Constellation','M','L49');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (287,'LET','L-410','L','L4T');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (288,'Lockheed','L-188 Electra','M','LOE');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (289,'Lockheed','L-188 Electra Freighter','M','LOF');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (290,'Lockheed','L-182 / 282 / 382 (L-100) Hercules','M','LOH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (291,'Lockheed','L-188 Electra Mixed','M','LOM');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (292,'Learjet','Gates Learjet','M','LRJ');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (293,'McDonnell Douglas','MD-11','H','M11');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (294,'McDonnell Douglas','MD-11 Freighter','H','M1F');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (295,'McDonnell Douglas','MD-11 Mixed','H','M1M');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (296,'McDonnell Douglas','MD-80','M','M80');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (297,'McDonnell Douglas','MD-81','M','M81');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (298,'McDonnell Douglas','MD-82','M','M82');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (299,'McDonnell Douglas','MD-83','M','M83');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (300,'McDonnell Douglas','MD-87','M','M87');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (301,'McDonnell Douglas','MD-88','M','M88');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (302,'McDonnell Douglas','MD-90','M','M90');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (303,'MBB','Bo 105',NULL,'MBH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (304,'MD Helicopters','MD900 Explorer',NULL,'MD9');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (305,'Mil','Mi-8 / Mi-17 / Mi-171 / Mil-172',NULL,'MIH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (306,'Mitsubishi','Mu-2','L','MU2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (307,'Nord / SNCAN','N.262','M','ND2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (308,'Aerospatiale / SNIAS','SN.601 Corvette','L','NDC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (309,'Eurocopter','AS350 Ecureuil / AS355 Ecureuil 2',NULL,'NDE');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (310,'Eurocopter','SA365C / SA365N Dauphin 2',NULL,'NDH');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (311,'Piper','Piper single piston engine','L','PA1');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (312,'Piper','Piper twin piston engines','L','PA2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (313,'Piper','Piper light aircraft','L','PAG');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (314,'Piper','Piper twin turboprop engines','L','PAT');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (315,'Pilatus','PC-12','L','PL2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (316,'Pilatus','PC-6 Turbo Porter','L','PL6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (317,'Partenavia','P.68','L','PN6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (318,'Saab','2000','M','S20');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (319,'Sikorsky','S-58T',NULL,'S58');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (320,'Sikorsky','S-61',NULL,'S61');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (321,'Sikorsky','S-76',NULL,'S76');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (322,'Saab','SF340A/B','M','SF3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (323,'Shorts','SD.330','M','SH3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (324,'Shorts','SD.360','M','SH6');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (325,'Shorts','SC-5 Belfast','M','SHB');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (326,'Shorts','SC-7 Skyvan','L','SHS');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (327,'Aerospatiale / SNIAS','Concorde','H','SSC');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (328,'Fairchild-Swearingen','SA26 / SA226 / SA227 Metro / Merlin','L','SWM');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (329,'Tupolev','Tu-204 / Tu-214','M','T20');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (330,'Tupolev','Tu-134','M','TU3');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (331,'Tupolev','Tu-154','M','TU5');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (332,'Vickers','Viscount','M','VCV');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (333,'IAI','1124 Westwind','M','WWP');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (334,'Yakovlev / Jakovlev','Yak 42','M','YK2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (335,'Yakovlev / Jakovlev','Yak 40','M','YK4');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (336,'HAMC / Harbin','Y12','M','YN2');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (337,'Xian','Yunshuji Y7','M','YN7');
INSERT INTO `aircraft_type` (`id`,`manufacturer`,`model`,`wake`,`iata_code`) VALUES (338,'NAMC','YS-11','M','YS1');
