_rest_deals_proceed_booking_approval:
    path:      "/api/deals/bookings/approval"
    defaults: { _controller: RestBundle:deals\Packages:proceedBookingWithApproval, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        _method: POST

_rest_deals_booking_get_price_quotation:
    path:      "/api/deals/bookings/quote"
    defaults: { _controller: RestBundle:deals\Packages:getQuoteBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_deals_booking_get_price_details:
    path:      "/api/deals/bookings/price-details"
    defaults: { _controller: RestBundle:deals\Packages:getTourPriceDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_deals_get_mandatory_fields:
    path:      "/api/deals/bookings/mandatory-fields"
    defaults: { _controller: RestBundle:deals\Packages:getMandatoryFields, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_deals_save_mandatory_fields:
    path:      "/api/deals/bookings/mandatory-fields-answers"
    defaults: { _controller: RestBundle:deals\Packages:saveMandatoryFieldAnswers, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_deals_booking:
    path:      "/api/deals/bookings"
    defaults: { _controller: RestBundle:deals\Packages:bookings, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_get_deal_images:
    path:      "/api/deals/images/{dealDetailsId}"
    defaults: { _controller: RestBundle:deals\Packages:getDealImages, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_top_deals:
    path:      "/api/deals/top/{dealDetailsId}"
    defaults: { _controller: RestBundle:deals\Packages:getTopDeals, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_find_booking_by_id:
    path:      "/api/deals/bookings/{bookingId}"
    defaults: { _controller: RestBundle:deals\Packages:findBookingById, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_deal_details:
    path:      "/api/deals/activities/{id}"
    defaults: { _controller: RestBundle:deals\Packages:getDealDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_deal_city:
    path:      "/api/deals/cities/{id}"
    defaults: { _controller: RestBundle:deals\Packages:getDealCityById, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_top_activities:
#    host: "www{subdomain_suffix}.{domain}"
    path:      "/api/deals/top-activities/"
    defaults: { _controller: RestBundle:deals\Packages:getTopActivities, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_deal_process_booking:
    path:      "/api/deals/booking/process"
    defaults: { _controller: RestBundle:deals\Packages:processBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_deals_update_booking:
#    host: "www{subdomain_suffix}.{domain}"
    path:      "/api/deals/booking/{id}"
    defaults: { _controller: RestBundle:deals\Packages:updateBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_get_transfer_vehicles:
#    host: "www{subdomain_suffix}.{domain}"
    path:      "/api/deals/transfer/vehicles/"
    defaults: { _controller: RestBundle:deals\Packages:getTransferVehicles, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_get_transfer_airport_listing:
    path:      "/api/deals/transfer/airports/{city}/{country}"
    defaults: { _controller: RestBundle:deals\Packages:getTransferAirportListing, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_transfer_cities_listing:
    path:      "/api/deals/transfer/cities/{country}"
    defaults: { _controller: RestBundle:deals\Packages:getTransferCitiesListing, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_cancel_booking:
    path:      "/api/deals/cancel-booking"
    defaults: { _controller: RestBundle:deals\Packages:cancelBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_check_availability:
    path:      "/api/deals/check-availability/{activityId}"
    defaults: { _controller: RestBundle:deals\Packages:checkAvailability, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_top_attractions:
    path:      "/api/deals/top-attractions"
    defaults: { _controller: RestBundle:deals\Packages:getTopAttractions, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_top_destinations:
    path:      "/api/deals/top-destinations"
    defaults: { _controller: RestBundle:deals\Packages:getTopDestinations, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_get_booking_status:
    path:      "/api/deals/booking/status/{bookingReference}"
    defaults: { _controller: RestBundle:deals\Packages:getBookingStatus, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET

_rest_add_booking:
    path:      "/api/deals/booking"
    defaults: { _controller: RestBundle:deals\Packages:addBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST

_rest_deal_search:
    path:      "/api/deals/search"
    defaults: { _controller: RestBundle:deals\Packages:dealSearch, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: POST


_rest_deal_autocomplete_search:
    path:      "/api/deals/search-suggestion"
    defaults: { _controller: RestBundle:deals\Packages:dealSearchAutoComplete, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", fromalbum: 1, seotitle: "%s-tourist tube", seodescription: "", seokeywords: "", title: "", srch: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
        title: ".*"
        srch: ".*"
        methods: GET