DealBundle\Entity\DealCountry:
    type: entity
    table: deal_country
    repositoryClass: DealBundle\Repository\Deal\PackagesRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        countryCode:
            type: string
            nullable: true
            length: 10
            column: country_code
        countryName:
            type: string
            nullable: true
            length: 100
            column: country_name      
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
    lifecycleCallbacks: {  }
