DealBundle\Entity\DealBookingStatusSupplier:
    type: entity
    table: deal_booking_status_supplier
    repositoryClass: DealBundle\Repository\Deal\PackagesRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ttStatus:
            type: string
            nullable: false
            length: 50
            column: tt_status
        supplierId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: supplier_id
        supplierStatus:
            type: string
            nullable: false
            length: 50
            column: supplier_status
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
    lifecycleCallbacks: {  }
