DealBundle\Entity\TTTransferType:
    type: entity
    table: tt_transfer_type
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            column: name
        description:
            type: string
            nullable: false
            length: 255
            column: description
        image:
            type: string
            nullable: false
            length: 255
            column: image
    lifecycleCallbacks: {  }
