parameters:
    SOCIAL_ENTITY_MEDIA: 1,
    SOCIAL_ENTITY_USER: 2,
    SOCIAL_ENTITY_ALBUM: 3,
    SOCIAL_ENTITY_WEBCAM: 4,
    SOCIAL_ENTITY_LOCATION: 5,
    SOCIAL_ENTITY_JOURNAL: 6,
    SOCIAL_ENTITY_JOURNAL_ITEM: 7,
    SOCIAL_ENTITY_FLASH: 8,
    SOCIAL_ENTITY_COMMENT: 9,
    SOCIAL_ENTITY_SHARE: 10,
    SOCIAL_ENTITY_NEWS: 11,
    SOCIAL_ENTITY_EVENTS: 12,
    SOCIAL_ENTITY_BROCHURE: 13,
    SOCIAL_ENTITY_CHANNEL: 14,
    SOCIAL_ENTITY_POST: 15,
    SOCIAL_ENTITY_EVENTS_LOCATION: 16,
    SOCIAL_ENTITY_EVENTS_DATE: 17,
    SOCIAL_ENTITY_EVENTS_TIME: 18,
    SOCIAL_ENTITY_CHANNEL_COVER: 19,
    SOCIAL_ENTITY_CHANNEL_PROFILE: 20,
    SOCIAL_ENTITY_CHANNEL_SLOGAN: 21,
    SOCIAL_ENTITY_CHANNEL_INFO: 22,
    SOCIAL_ENTITY_USER_PROFILE: 23,
    SOCIAL_ENTITY_USER_EVENTS: 24,
    SOCIAL_ENTITY_PROFILE_FRIENDS: 25,
    SOCIAL_ENTITY_PROFILE_FOLLOWERS: 26,
    SOCIAL_ENTITY_PROFILE_FOLLOWINGS: 27,
    SOCIAL_ENTITY_HOTEL: 28,
    SOCIAL_ENTITY_RESTAURANT: 29,
    SOCIAL_ENTITY_LANDMARK: 30,
    SOCIAL_ENTITY_BAG: 31,
    SOCIAL_ENTITY_PROFILE_ABOUT: 32,
    SOCIAL_ENTITY_PROFILE_ACCOUNT: 33,
    SOCIAL_ENTITY_PROFILE_LOCATION: 34,
    SOCIAL_ENTITY_PROFILE_VISITED_PLACES: 35,
    SOCIAL_ENTITY_HOTEL_REVIEWS: 36,
    SOCIAL_ENTITY_RESTAURANT_REVIEWS: 37,
    SOCIAL_ENTITY_LANDMARK_REVIEWS: 38,
    SOCIAL_ENTITY_RESTAURANT_CUISINE: 39,
    SOCIAL_ENTITY_RESTAURANT_SERVICE: 40,
    SOCIAL_ENTITY_RESTAURANT_ATMOSPHERE: 41,
    SOCIAL_ENTITY_RESTAURANT_PRICE: 42,
    SOCIAL_ENTITY_RESTAURANT_NOISE: 43,
    SOCIAL_ENTITY_RESTAURANT_TIME: 44,
    SOCIAL_ENTITY_REPORT_BUG: 45,
    SOCIAL_ENTITY_VISITED_PLACES: 47,
    SOCIAL_ENTITY_HOTEL_AIRPOT: 48,
    SOCIAL_ENTITY_HOTEL_SERVICE: 49,
    SOCIAL_ENTITY_HOTEL_CLEANLINESS: 50,
    SOCIAL_ENTITY_HOTEL_INTERIOR: 51,
    SOCIAL_ENTITY_HOTEL_PRICE: 52,
    SOCIAL_ENTITY_HOTEL_FOODDRINK: 53,
    SOCIAL_ENTITY_HOTEL_INTERNET: 54,
    SOCIAL_ENTITY_HOTEL_NOISE: 55,
    SOCIAL_ENTITY_LANDMARK_FOODAVAILABLE: 56,
    SOCIAL_ENTITY_LANDMARK_BATHROOMFACILITIES: 57,
    SOCIAL_ENTITY_LANDMARK_STAIRS: 58,
    SOCIAL_ENTITY_LANDMARK_STORAGE: 59,
    SOCIAL_ENTITY_LANDMARK_PARKING: 60,
    SOCIAL_ENTITY_LANDMARK_WHEELCHAIR: 61,
    SOCIAL_ENTITY_CUSTOME_SUPPORT: 62,
    SOCIAL_ENTITY_AIRPORT: 63,
    SOCIAL_ENTITY_AIRPORT_REVIEWS: 64
    SOCIAL_ENTITY_AIRPORT_LUGGAGE: 65,
    SOCIAL_ENTITY_AIRPORT_RECEPTION: 66,
    SOCIAL_ENTITY_AIRPORT_LOUNGE: 67,
    SOCIAL_ENTITY_AIRPORT_FOOD: 68,
    SOCIAL_ENTITY_AIRPORT_DUTYFREE: 69,
    SOCIAL_ENTITY_CITY: 71,
    SOCIAL_ENTITY_COUNTRY: 72,
    SOCIAL_ENTITY_STATE: 73,
    SOCIAL_ENTITY_DOWNTOWN: 74,
    SOCIAL_ENTITY_HOTEL_RESERVATION: 75,
    SOCIAL_ENTITY_FLIGHT: 76,
    SOCIAL_ENTITY_DEAL: 77,
    SOCIAL_ENTITY_REGION: 78,
    SOCIAL_ENTITY_THINGSTODO_CITY: 79,
    SOCIAL_ENTITY_THINGSTODO_DETAILS: 80,
    SOCIAL_ENTITY_DEAL_ATTRACTIONS: 81,
    SOCIAL_ENTITY_HOTEL_SELECTED_CITY: 82,
    SOCIAL_ENTITY_HOTEL_HRS: 83,
    SOCIAL_ACTION_RATE: 1,
    SOCIAL_ACTION_COMMENT: 2,
    SOCIAL_ACTION_LIKE: 3,
    SOCIAL_ACTION_UPLOAD: 4,
    SOCIAL_ACTION_SHARE: 5,
    SOCIAL_ACTION_SPONSOR: 6,
    SOCIAL_ACTION_CONNECT: 7,
    SOCIAL_ACTION_EVENT_CANCEL: 8,
    SOCIAL_ACTION_EVENT_JOIN: 9,
    SOCIAL_ACTION_INVITE: 10,
    SOCIAL_ACTION_REPORT: 11,
    SOCIAL_ACTION_UPDATE: 12,
    SOCIAL_ACTION_FOLLOW: 13,
    SOCIAL_ACTION_FRIEND: 14,
    SOCIAL_ACTION_UNFRIEND: 15,
    SOCIAL_ACTION_UNFOLLOW: 16,
    SOCIAL_ACTION_REPLY: 17,
    SOCIAL_ACTION_REECHOE: 18,
    SOCIAL_ACTION_RELATION_SUB: 19,
    SOCIAL_ACTION_RELATION_PARENT: 20,
    SOCIAL_ACTION_CHAT: 21,
    SOCIAL_ACTION_FRIEND_REQUEST: 22,
    SOCIAL_ACTION_LOCATION_SHARE: 23,
    SOCIAL_ACTION_VOICE_MESSAGE: 24,
    SOCIAL_ACTION_FILE_SHARE: 25,
    SOCIAL_ACTION_CALL: 26,
    SOCIAL_ACTION_DISCONNECT_CALL: 27,
    FRND_STAT_NEW: 0,
    FRND_STAT_PENDING: 2,
    FRND_STAT_ACPT: 1,
    FRND_STAT_RJCT: -1,
    FRND_STAT_BLOCK_BYREC: -2,
    FRND_STAT_BLOCK_BYREQ: -3,
    FRND_STAT_BLOCK_BYBOTH: -4,
    FRND_STAT_IGNORE: -5,
    FRND_STAT_REJECT_REQ: -6,
    FRND_STAT_BLOCK_TUBER: -7,
    USER_PRIVACY_PRIVATE: 0,
    USER_PRIVACY_COMMUNITY: 1,
    USER_PRIVACY_PUBLIC: 2,
    USER_PRIVACY_COMMUNITY_EXTENDED: 3,
    USER_PRIVACY_SELECTED: 4,
    USER_PRIVACY_FOLLOWERS: 5,
    SOCIAL_SHARE_TYPE_SHARE: 1,
    SOCIAL_SHARE_TYPE_INVITE: 2,
    SOCIAL_SHARE_TYPE_SPONSOR: 3,
    SOCIAL_POST_TYPE_TEXT: 1,
    SOCIAL_POST_TYPE_PHOTO: 2,
    SOCIAL_POST_TYPE_VIDEO: 3,
    SOCIAL_POST_TYPE_LINK: 4,
    SOCIAL_POST_TYPE_LOCATION: 5,
    PRIVACY_EXTAND_TYPE_CONNECTIONS: 1,
    PRIVACY_EXTAND_TYPE_SPONSORS: 2,
    PRIVACY_EXTAND_TYPE_LOG: 3,
    PRIVACY_EXTAND_TYPE_EVENTJOIN: 4,
    PRIVACY_EXTAND_KIND_PUBLIC: 1,
    PRIVACY_EXTAND_KIND_CONNECTIONS: 2,
    PRIVACY_EXTAND_KIND_SPONSORS: 3,
    PRIVACY_EXTAND_KIND_PRIVATE: 4,
    PRIVACY_EXTAND_KIND_CUSTOM: 5,
    CHANNEL_DETAIL_COVER: 1,
    CHANNEL_DETAIL_PROFILE: 2,
    CHANNEL_DETAIL_SLOGAN: 3,
    CHANNEL_DETAIL_INFO: 4,
    USER_DETAIL_PROFILE: 1,
    FROM_FRIENDS: 1,
    FROM_FOLLOWINGS: 2,
    FROM_CHANNELS: 3,
    ACTIVITIES_ON_TCHANNELS: 1,
    ACTIVITIES_ON_THOTELS: 2,
    ACTIVITIES_ON_TRESTAURANTS: 3,
    ACTIVITIES_ON_TPLANNER: 4,
    ACTIVITIES_ON_TTPAGE: 5,
    ACTIVITIES_ON_TTPAGE_OTHER: 6,
    ACTIVITIES_ON_TECHOES: 7,
    CORPO_APPROVAL_PENDING: 1,
    CORPO_APPROVAL_APPROVED: 2,
    CORPO_APPROVAL_CANCELED: 3,
    CORPO_APPROVAL_EXPIRED: 4,
    CORPO_APPROVAL_REJECTED: 5,
    ROLE_USER: 1,
    ROLE_ADMIN: 2,
    ROLE_CORPORATE: 3,
    ROLE_SYSTEM: 4,
    ROLE_API: 5,
    WEB_REFERRER: 1,
    CORPORATE_REFERRER: 2,
    MODULE_FLIGHTS: 1,
    MODULE_HOTELS: 2,
    MODULE_DEALS: 3,
    MODULE_DEFAULT: 0,
    MODULE_FINANCE: 4,
    DEAL_TYPE_PACKAGES: 1,
    DEAL_TYPE_TOURS: 2,
    DEAL_TYPE_ACTIVITIES: 3,
    DEAL_TYPE_TRANSFERS: 4,
    DEAL_TYPE_ATTRACTIONS: 5,
    FULL_DATE_FORMAT: "l, F d, Y"
    FULL_NUMBER_FORMAT: 2,
    FLIGHT_LAST_HOUR_TO_CANCEL: 19,
    SOCIAL_HOTEL_RATE_TYPE: 1,
    SOCIAL_HOTEL_RATE_TYPE_CLEANLINESS: 2,
    SOCIAL_HOTEL_RATE_TYPE_CONFORT: 3,
    SOCIAL_HOTEL_RATE_TYPE_LOCATION: 4,
    SOCIAL_HOTEL_RATE_TYPE_FACILITIES: 5,
    SOCIAL_HOTEL_RATE_TYPE_STAFF: 6,
    SOCIAL_HOTEL_RATE_TYPE_MONEY: 7,
    MAX_API_CALL_ATTEMPTS: 3,
    FLIGHT_EXPIRY_TIME: 600,
    HOTEL_EXPIRY_TIME: 86400,
    DEAL_EXPIRY_TIME: 432000,
    TRAVEL_APPROVAL_NUMBER_OF_RECORDS: 20,
    TRAVEL_APPROVAL_PAGINATION_COUNT: 2,
    PAUSE_BETWEEN_RETRIES_US: 500000,
    MAX_RECORD: 200,
    FBC_CODE: "USD"
    SBC_CODE: "AED"
    MEDIA_HOTELS_LOGOS_BASE_PATH: "media/hotels/logos/"
    MEDIA_360_BASE_PATH: "media/360/"
    MEDIA_360_SPHERE_ALLOWED_HOTELS:
        - 85344
        - 1234
    TTD_MEDIA_360_BASE_PATH: "media/360/ttd/"
    GMAP_BASE_PATH: "media/gmap/"
    GMAP_FILENAME: "location_map.png"
    USER_AVATAR_RELATIVE_PATH: "media/tubers/"
    MEDIA_TYPE_IMAGE: 1
    MEDIA_TYPE_360: 2
    PAGE_TYPE_HOME: 1
    PAGE_TYPE_FLIGHT: 2
    PAGE_TYPE_360_PHOTOS_VIRTUAL_TOUR: 3
    PAGE_TYPE_CITY_ACTIVITIES: 4
    PAGE_TYPE_HOTEL_BOOKING: 5
    PAGE_TYPE_BEST_HOTELS_IN_THE_WORLD: 6
    PAGE_TYPE_ATTRACTIONS_SKIP_THE_LINE: 7
    PAGE_TYPE_DEALS: 8
    PAGE_TYPE_LIVE: 9
    hash_salt: "B9JeLcvCWyLuCJ4lgQEA0tq72EMZb5S3RduOPAcqsLtu5J2d4i"
    MAP_STATIC_KEY:
        - "AIzaSyAfeFAzBMMzLavyUA9SvfH7cSRzh_NiVfw"
    MAP_STATIC_URL_SIG_KEY:
        - "_IlE7keUU5va_InDskdl6QiA5fU="
    MAP_STATIC_KEY1:
        - "AIzaSyAAo3hxsZ4jGt8OMyKwBDN0eLrN9zo14hc"
    MAP_STATIC_KEY_LOCAL:
        - "AIzaSyBJPoaOvHnqZ8QTvSdW96y0EMnxfn5Yh80"
    MAP_KEY:
        - "AIzaSyCL53RGsSAL-vteodkWJJZCaRksk3HB02E"
    MAP_KEY1:
        - "AIzaSyCrxIysSaXDyJxGenBvXJIfqIFclyatYfo"
    SALES_PERSON: 14 #sales person user profile ID
    COMPANY: 15 #Company user profile ID
    AGENCY: 16 #Agency user profile ID
    AFFILIATES: 12 #AFFILIATES user profile ID
    USERS: 8 #USERS user profile ID
    RETAIL_AGENCY: 17 #Retail Agency user profile ID

    MENU_ACCESS:
        AFFILIATES:
            - KEY_FLIGHTS, KEY_HOTELS, KEY_SALES_PERSONS, KEY_COMPANIES, KEY_AGENCIES, KEY_RETAIL_AGENCIES, KEY_REPORTS
        SALES_PERSON:
            - KEY_FLIGHTS, KEY_HOTELS, KEY_COMPANIES, KEY_AGENCIES, KEY_RETAIL_AGENCIES, KEY_REPORTS
        COMPANY: 
            - KEY_USERS, KEY_REPORTS
        AGENCY:
            - KEY_USERS, KEY_REPORTS
        RETAIL_AGENCY:
            - KEY_USERS, KEY_REPORTS
        USERS:
            - KEY_FLIGHTS, KEY_HOTELS, KEY_MANAGE_BOOKINGS, KEY_REPORTS
    FIXED_MENUS:
        - KEY_WELCOME, KEY_PROFILE_SETTINGS, KEY_CHANGE_PASSWORD, KEY_LOGOUT, KEY_ABOUT_US, KEY_CONTACT, KEY_TERMS_OF_SERVICE, KEY_PRIVACY_POLICY

    TOURISTTUBE_ACCOUNT: 47