_ajax_account_check_user_lang:
    path:      "/{_locale}/ajax/account-check-user"
    defaults: { _controller: TTBundle:Users:updateAccountCheckUser, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_account_info_lang:
    path:      "/{_locale}/ajax/account-info"
    defaults: { _controller: TTBundle:Users:updateAccountInfo, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_account_settings_lang:
    path:      "/{_locale}/ajax/account-settings"
    defaults: { _controller: TTBundle:Users:updateAccountSettings, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_process_fb_lang:
    path:      "/{_locale}/ajax/process_fb"
    defaults: { _controller: TTBundle:Users:processFB, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_user_report_add_lang:
    path:      "/{_locale}/ajax/user/report/add"
    defaults: { _controller: TTBundle:Users:userReportAdd, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_user_activate_account_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/users/activate-account/{key}"
    defaults: { _controller: TTBundle:Users:activateUsersAccount, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", key: "", seotitle: "Account Activation | Tourist Tube", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_user_reactivate_account_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/users/reactivate-account"
    defaults: { _controller: TTBundle:Users:reactivateUsersAccount, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", key: "", seotitle: "Account Activation | Tourist Tube", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_reactivate_account_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/reactivate"
    defaults: { _controller: TTBundle:Users:reactivateUsersAccount, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", key: "", seotitle: "Account Activation | Tourist Tube", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_user_confirm_login_lang:
    path: "/{_locale}/user/confirm/login"
    defaults: { _controller: TTBundle:Users:userConfirmLogin, _locale: "%locale%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"

_user_add_register_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/users/register/addSubmit"
    defaults: { _controller: TTBundle:Users:addUserSubmit, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "login Tourist Tube", seodescription: "Welcome to touristtube.com. Do not have an account yet? Sign up now!", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_account_info_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/account/info"
    defaults: { _controller: TTBundle:Users:accountInfo, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        
_account_settings_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/account/settings"
    defaults: { _controller: TTBundle:Users:accountSettings, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_account_myprofile_tuber_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/myprofile/{params}"
    defaults: { _controller: TTBundle:Users:accountProfile, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", params: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        params: ".*"

_account_profile_tuber_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/profile/{username}/{params}"
    defaults: { _controller: TTBundle:Users:accountProfile, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", params: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        params: ".*"

_account_upload_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/upload"
    defaults: { _controller: TTBundle:Users:accountUpload, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Upload | Tourist Tube", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_unsubscribe_emails_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/unsubscribe/emails/{key}"
    defaults: { _controller: TTBundle:Users:unsubscribeEmails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", key: "", seotitle: "Unsubscribe | Tourist Tube", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        key: ".*"

_user_unsubscribe_code_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/user-unsubscribe/code/{key}"
    defaults: { _controller: TTBundle:Users:userUnsubscribeCode, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", key: "", seotitle: "User Unsubscribe | Tourist Tube", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        key: ".*"

_user_tt_confirmation_lang:
    path:      "/{_locale}/TT-confirmation/{params}/{key}"
    defaults: { _controller: TTBundle:Users:userTTConfirmation, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", key: "", seotitle: "User Unsubscribe | Tourist Tube", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        key: ".*"

_ajax_reactivate_notifications_lang:
    path:      "/{_locale}/ajax/reactivate_notifications"
    defaults: { _controller: TTBundle:Users:reactivateNotifications, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_user_unsubscribe_delete_lang:
    path:      "/{_locale}/ajax/user_unsubscribe_delete"
    defaults: { _controller: TTBundle:Users:userUnsubscribeDeleteAccount, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_profile_media_data_lang:
    path: "/{_locale}/ajax/profile_media_data"
    defaults: { _controller: TTBundle:Users:getProfileMediaData, _locale: "%locale%", domain: "%domain%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"