_delete_bag_item_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/delete-bag-item"
    defaults: { _controller: TTBundle:Bags:deleteBagItem, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_update_bag_item_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/update-bag-item"
    defaults: { _controller: TTBundle:Bags:updateBagItem, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_add_bag_new_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/add-bag_new"
    defaults: { _controller: TTBundle:Bags:addBagNew, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_edit_bag_new_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/edit-bag_new"
    defaults: { _controller: TTBundle:Bags:editBagNew, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_delete_bag_new_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/delete-bag_new"
    defaults: { _controller: TTBundle:Bags:deleteBagNew, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_get_bag_info_new_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/get-bag-info_new"
    defaults: { _controller: TTBundle:Bags:getBagInfoNew, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_get_bag_item_info_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/get-bag-item-info"
    defaults: { _controller: TTBundle:Bags:getBagItemInfo, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_bags_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/bags"
    defaults: { _controller: TTBundle:Bags:bags, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_bag_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/bag-{id}"
    defaults: { _controller: TTBundle:Bags:bag, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "Most Visited Tourist Attractions Suggested By Best Travel Advisor", seodescription: "Our travel sites are showing you what are the most-visited tourist attractions in the world And can 91 million people be wrong? Read Explanation of our travel advisor.", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_add_to_bag_lang:
    path:      "/{_locale}/ajax/add_to_bag"
    defaults: { _controller: TTBundle:Bags:addToBag, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_add_item_to_bag_lang:
    path:      "/{_locale}/ajax/add_item_to_bag"
    defaults: { _controller: TTBundle:Bags:addItemToBag, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_add_item_to_old_bag_lang:
    path:      "/{_locale}/ajax/add_item_to_old_bag"
    defaults: { _controller: TTBundle:Bags:addItemToOldBag, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"