_ajax_account_check_user_lang:
    path:      "/{_locale}/ajax/account-check-user"
    defaults:  { _controller: TTBundle:Tuber:updateAccountCheckUser, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_account_info_lang:
    path:      "/{_locale}/ajax/account-info"
    defaults:  { _controller: TTBundle:Tuber:updateAccountInfo, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_ajax_account_settings_lang:
    path:      "/{_locale}/ajax/account-settings"
    defaults:  { _controller: TTBundle:Tuber:updateAccountSettings, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"

_account_info_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/account/info"
    defaults:  { _controller: TTBundle:Tuber:accountInfo, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        
_account_settings_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/account/settings"
    defaults:  { _controller: TTBundle:Tuber:accountSettings, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        
_account_sharing_lang:
    host: "www{subdomain_suffix}.{domain}"
    path:      "/{_locale}/account/sharing"
    defaults:  { _controller: TTBundle:Tuber:accountSharing, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
