_api_photos_videos_search:
    path: "/api/photos-videos/search"
    defaults: { _controller: ApiBundle:PhotosVideos:photosVideosSearch, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

_api_categories_list:
    path: "/api/categories"
    defaults: { _controller: ApiBundle:PhotosVideos:categoriesList, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

_api_bag_bags_list:
    path: "/api/bag/bags"
    defaults: { _controller: ApiBundle:Bags:bagsList, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_update_bag_name:
    path: "/api/bag/update_bag_name"
    defaults: { _controller: ApiBundle:Bags:updateBagName, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_update_bag_item_info:
    path: "/api/bag/update_bag_item_info"
    defaults: { _controller: ApiBundle:Bags:updateBagItemInfo, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_delete_bag_item:
    path: "/api/bag/delete_bag_item"
    defaults: { _controller: ApiBundle:Bags:deleteBagItem, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_delete_bag:
    path: "/api/bag/delete_bag"
    defaults: { _controller: ApiBundle:Bags:deleteBag, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_add_to_bag:
    path: "/api/bag/add_to_bag"
    defaults: { _controller: ApiBundle:Bags:addItemToBag, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_create_bag:
    path: "/api/bag/create_bag"
    defaults: { _controller: ApiBundle:Bags:createBag, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements:
        domain: "[^/]+"

_api_bag_bag_items:
    path: "/api/bag/bag_items"
    defaults: { _controller: ApiBundle:Bags:bagItems, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

# List all countries
_api_countries:
    path: "/api/all/countries"
    defaults: { _controller: ApiBundle:Country:getCountryList, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

# List all currencies
_api_currencies:
    path: "/api/all/currencies"
    defaults: { _controller: ApiBundle:Currency:getCurrencyList, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

# convert currency
_api_convert_currency:
    path: "/api/convert/currency"
    defaults: { _controller: ApiBundle:Currency:currencyConversionRate, _locale: "%locale%", domain: "%domain%" }
    methods:  [POST]
    requirements: 
        domain: "[^/]+"

#RabbitMQ Testing
_rabbit_MQ_Send:
    path: "/rabbit/send"
    defaults: { _controller: ApiBundle:Discover:rabbitMqSend, _locale: "%locale%", domain: "%domain%"}
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

 #RabbitMQ Testing
_rabbit_MQ_Receive:
    path: "/rabbit/receive"
    defaults: { _controller: ApiBundle:Discover:rabbitMqReceive, _locale: "%locale%", domain: "%domain%"}
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"

# my flight bookings
_api_my_flight_bookings:
    path: "/api/flight/bookings"
    defaults: { _controller: TTBundle:MyBookings:myFlightBookingApi, _locale: "%locale%", domain: "%domain%" }
    methods:  [POST]
    requirements: 
        domain: "[^/]+"

_hotel_offers_api:
    path:      "/api/hotel-offers-{name}-{id}"
    defaults: { _controller: HotelBundle:HRS:hotelOffers, _locale: "%locale%", domain: "%domain%", name: "", id: "", seotitle: "Hotel Booking Tourist Tube", seodescription: "searching the web for cheap hotels? Want to know more about hotel booking? tourist tube is the perfect site for the best hotels and hotel deals on the web", seokeywords: "" }
    requirements:
        domain: "[^/]+"

_booking_details_api:
    path:      "/api/booking-details-{reference}"
    defaults: { _controller: HotelBundle:HRS:bookingDetails, _locale: "%locale%", domain: "%domain%", seotitle: "Hotel Booking Tourist Tube", seodescription: "searching the web for cheap hotels? Want to know more about hotel booking? tourist tube is the perfect site for the best hotels and hotel deals on the web", seokeywords: "" }
    requirements:
        domain: "[^/]+"
        reference: ".*"

_flight_details_api:
    path:      "/api/flight-details"
    defaults: { _controller: TTBundle:MyBookings:myFlightDetails, page: 1, _locale: "%locale%", domain: "%domain%", seotitle: "flight details Tourist Tube", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"

_flight_cancelation_api:
    path:      "/api/flight-cancelation"
    defaults: { _controller: FlightBundle:Flight:flightCancelation, _locale: "%locale%", domain: "%domain%", seotitle: "flight cancelation | Tourist Tube", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"

_hotel_reservation_api:
    path:      "/api/hotel-reservation"
    defaults: { _controller: HotelBundle:HRS:hotelReservation, _locale: "%locale%", domain: "%domain%", seotitle: "Hotel Booking Tourist Tube", seodescription: "searching the web for cheap hotels? Want to know more about hotel booking? tourist tube is the perfect site for the best hotels and hotel deals on the web", seokeywords: "" }
    requirements:
        domain: "[^/]+"

_hotel_avail_api:
    path:      "/api/hotel-avail"
    defaults: { _controller: HotelBundle:HRS:hotelAvail, _locale: "%locale%", domain: "%domain%", seotitle: "Hotel Booking Tourist Tube", seodescription: "searching the web for cheap hotels? Want to know more about hotel booking? tourist tube is the perfect site for the best hotels and hotel deals on the web", seokeywords: "" }
    requirements:
        domain: "[^/]+"

_hotel_reservation_cancellation_api:
    path:      "/api/hotel-reservation-cancellation-{reference}"
    defaults: { _controller: HotelBundle:HRS:hotelReservationCancellation, _locale: "%locale%", domain: "%domain%", seotitle: "Hotel Booking Tourist Tube", seodescription: "searching the web for cheap hotels? Want to know more about hotel booking? tourist tube is the perfect site for the best hotels and hotel deals on the web", seokeywords: "" }
    requirements:
        domain: "[^/]+"
        reference: ".*"

_my_bookings_search_api:
    path:      "/api/my-bookings-search"
    defaults: { _controller: TTBundle:MyBookings:myBookingsSearch, page: 1, _locale: "%locale%", domain: "%domain%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"

_book_flight_api:
    path:      "/api/book-flight"
    defaults: { _controller: FlightBundle:Flight:bookFlight, _locale: "%locale%", domain: "%domain%", seotitle: "book flight | Tourist Tube", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"

_flight_booking_result_api:
    path: "/api/flight-booking-result"
    defaults: { _controller: FlightBundle:Flight:flightBookingResult, _locale: "%locale%", domain: "%domain%", seotitle: "flight booking result | Tourist Tube", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"

_terms-and-conditions_api:
    path:      "/api/terms-and-conditions-{web}"
    defaults: { _controller: TTBundle:Social:termsAndConditions, _locale: "%locale%", domain: "%domain%", web: "", seotitle: "terms and conditions Tourist Tube", seodescription: "By registering as a member or by using the Tourist Tube services in any way, you accept these Terms of Service ('Agreement')", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        web: ".*"

_disclaimer_api:
    path:      "/api/disclaimer-{web}"
    defaults: { _controller: TTBundle:Social:disclaimer, _locale: "%locale%", domain: "%domain%", web: "", seotitle: "disclaimer Tourist Tube", seodescription: "We provide our Services using a commercially reasonable level of skill and care and we hope that you will benefit from them.", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        web: ".*"

_privacy-policy_api:
    path:      "/api/privacy-policy-{web}"
    defaults: { _controller: TTBundle:Social:privacyPolicy, _locale: "%locale%", domain: "%domain%", web: "", seotitle: "privacy policy Tourist Tube", seodescription: "Tourist Tube LTD has developed this Privacy Policy to demonstrate its commitment to respecting your privacy.", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        web: ".*"

_help_api:
    path:      "/api/help-{web}"
    defaults: { _controller: TTBundle:Social:help, _locale: "%locale%", domain: "%domain%", web: "", seotitle: "tourist help Tourist Tube", seodescription: "You can view content in our public section without registration. However you are required to register to use the full features of Tourist Tube.", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        web: ".*"

_api_publish_video:
    path: "/api/publish/video"
    defaults: { _controller: ApiBundle:Default:publishVideoUpdate, _locale: "%locale%", domain: "%domain%" }
    methods:  [GET, HEAD]
    requirements: 
        domain: "[^/]+"