_hotels_near_lang:
    host: "nearby{subdomain_suffix}.{domain}"
    path:      "/{_locale}/hotels-near-by{dest}/{dest1}"
    defaults: { _controller: TTBundle:Default:hotelsNearBy, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", dest1: "", seotitle: "Hotels Near By %s-tourist tube", seodescription: "searching for hotels near by %1$s For more info about hotels booking visit us on Tourist Tube", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        dest1: ".*"

_hotels_near_redirect_lang:
    path:      "/{_locale}/hotels-near-by{dest}/{dest1}"
    defaults: { _controller: TTBundle:Default:hotelsNearByRedirect, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", dest1: "", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        dest1: ".*"