PaymentBundle\Entity\PaymentDetails:
    type: entity
    table: payment_details
    repositoryClass: PaymentBundle\Repository\PaymentRepository
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            nullable: true
            length: 36
            options:
                fixed: false
            column: uuid 
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
        apiResponse:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: api_response
                 
    lifecycleCallbacks: {  }
