PaymentBundle\Entity\PaymentProvider:
    type: entity
    table: payment_provider
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY 
    fields:
        name:
            type: string
            length: 20
            column: name
    lifecycleCallbacks: {  }
