fos_oauth_server_token_lang:
    path: "/{_locale}/oauth/v2/token"
    defaults: { _controller: RestBundle:oauth\OAuth2Token:token, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        methods: POST

fos_oauth_create_client_lang:
    path: "/{_locale}/api/create-client"
    defaults: { _controller: RestBundle:oauth\OAuth2Token:createClient, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        _locale:  "%config_locales%"
        domain: "[^/]+"
        subdomain_suffix: ".*"
        methods: GET