INSERT INTO amadeus_hotel
            (
                        id,
                        dupe_pool_id,
                        amadeus_city_id,
                        city_id,
                        property_name,
                        address_line_1,
                        address_line_2,
						latitude,
                        longitude,
                        district,
                        zip_code,
                        phone,
                        fax,
                        stars,
                        logo,
                        map_image,
                        self_rating,
                        location,
                        transportation,
                        popularity,
                        published,
                        last_updated,
                        images_downloaded,
                        slug,
                        old_id,
                        description
            )
            VALUES
            (
                        '347906',
                        NULL,
                        '66969',
                        '2330167',
                        'Maximus Hotel Byblos',
                        'Byblos, Blat, Near LAU, Byblos, Lebanon',
                        NULL,
                        '34.116234',
                        '35.676629',
                        NULL,
                        '1401',
                        '+961 70 929777',
                        NULL,
                        '5',
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        '1',
                        '1',
                        CURRENT_TIMESTAMP,
                        '0',
                        'Maximus+Hotel+Byblos',
                        NULL,
                        'Featuring an indoor/outdoor swimming pool, high-tech fitness center and a panoramic sea view, Maximus Hotel Byblos is situated in Jbeil, 1.4 km from Byblos Archeological Site. The hotel has two restaurants, a cigar lounge and a wellness area. Each room is fitted with a flat-screen TV with satellite channels. At the hotel, each room comes with a wardrobe. The rooms are equipped with a private bathroom with free toiletries, while selected rooms also offer a balcony and Jacuzzi. A Buffet or à la carte breakfast is available each morning at the property. The property has a Sauna & Steam Rooms. Maximus Hotel Byblos can conveniently provide information at the reception to help guests to get around the area. Byblos Fossil Museum is 1.3 km from the accommodation while Byblos Castle is 1.4 km from the property. The nearest airport is Beirut Rafic Hariri International Airport, 35km from Maximus Hotel Byblos. Couples particularly like the hotel calm location, especially the Free shuttles to Byblos City This property is rated for the best value in Jbeil! Guests are getting more for their money when compared to other properties in this city. We speak your language!'
            ); 
