INSERT INTO cms_hotel(id, name, description, address, street, district, zip_code, city, city_id, latitude, longitude, iso3_country_code, country_code, stars, logo, map_image, popularity, published, normalized_name, minimized_name, downtown, distance_from_downtown, airport, distance_from_airport, train_station,  distance_from_train_station, pre_20160901, g_submitted) VALUES ('347908', 'Roda Links Al Nasr', NULL, NULL, '10th St - Dubai - United Arab Emirates', NULL, NULL, 'Dubai (Dubai)', '1060078' , '25.237423', '55.309707', 'ARE', 'AE', '4', NULL, '', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0');
INSERT INTO cms_hotel_source(hotel_id, source, source_id, source_code, location_id, location_code, trustyou_id) VALUES ('347908', 'tt', '-1', NULL, '6879', NULL, NULL);


INSERT INTO cms_hotel(id, name, description, address, street, district, zip_code, city, city_id, latitude, longitude, iso3_country_code, country_code, stars, logo, map_image, popularity, published, normalized_name, minimized_name, downtown, distance_from_downtown, airport, distance_from_airport, train_station,  distance_from_train_station, pre_20160901, g_submitted) VALUES ('347907', 'Radisson Blu Bali Uluwatu', NULL, NULL, 'JI Pemutih, Pecatu, Kuta Sel., Pecatu, Bali 80364, Indonesia', NULL, NULL, 'Pecatu (Bali)', '1914368' , '-8.809160', '115.110416', 'IDN', 'ID', '5', NULL, '', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0');
INSERT INTO cms_hotel_source(hotel_id, source, source_id, source_code, location_id, location_code, trustyou_id) VALUES ('347907', 'tt', '-1', NULL, '1796390', NULL, NULL);


INSERT INTO cms_hotel(id, name, description, address, street, district, zip_code, city, city_id, latitude, longitude, iso3_country_code, country_code, stars, logo, map_image, popularity, published, normalized_name, minimized_name, downtown, distance_from_downtown, airport, distance_from_airport, train_station,  distance_from_train_station, pre_20160901, g_submitted) VALUES ('347906', 'Maximus Hotel Byblos', NULL, NULL, 'Byblos, Blat, Near LAU, Byblos, Lebanon', NULL, NULL, 'Jbeil (Mohafazat Mont-Liban)', '2330167' , '34.116234', '35.676629', 'LBN', 'LB', '5', NULL, '', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0');
INSERT INTO cms_hotel_source(hotel_id, source, source_id, source_code, location_id, location_code, trustyou_id) VALUES ('347906', 'tt', '-1', NULL, '1209410', NULL, NULL);

