UPDATE cms_hotel_city SET city_id = 1060078 WHERE location_id = 58133;
UPDATE cms_hotel SET name = 'Mercure Leeds Centre Hotel' WHERE id = 416904;
UPDATE cms_hotel SET name = 'Novotel Qingdao New Hope' WHERE id = 416896;
UPDATE cms_hotel SET name = 'Mercure Nizhny Novgorod Center' WHERE id = 416895;
UPDATE cms_hotel SET name = 'Pullman Abidjan' WHERE id = 12073;
UPDATE cms_hotel SET name = 'ibis Styles Kortrijk Expo' WHERE id = 15077;
UPDATE cms_hotel SET name = 'Hotel Mercure Tirrenia Green Park' WHERE id = 23701;
UPDATE cms_hotel SET name = 'ibis Styles Hyeres Centre Gare' WHERE id = 42348;
UPDATE cms_hotel SET name = 'Novotel New Delhi Aerocity' WHERE id = 172693;
UPDATE cms_hotel SET name = 'Mercure Argentario Hotel Filippo II' WHERE id = 200451;
UPDATE cms_hotel SET name = 'Grand Mercure Bengaluru at Gopalan Mall' WHERE id = 205281;
UPDATE cms_hotel SET name = 'Grand Mercure Yogyakarta Adi Sucipto' WHERE id = 205301;
UPDATE cms_hotel SET name = 'Grand Mercure Guangzhou Zhujiang' WHERE id = 417199;
UPDATE cms_hotel SET name = 'Mercure Civitavecchia Sunbay Park Hotel' WHERE id = 350239;
UPDATE cms_hotel SET name = 'ibis Styles Warszawa Centrum' WHERE id = 356428;
UPDATE cms_hotel SET name = 'ibis Styles Batam Yos Sudarso' WHERE id = 375808;
UPDATE cms_hotel SET name = 'ibis Styles Koh Samui Chaweng Beach' WHERE id = 382184;
UPDATE cms_hotel SET name = 'Novotel Christchurch Airport' WHERE id = 405170;
UPDATE cms_hotel SET name = 'Hotel Öresund Conference & Spa' WHERE id = 405827;
UPDATE cms_hotel SET name = 'ibis Carlos Barbosa' WHERE id = 417194;
UPDATE cms_hotel SET name = 'Mercure Bridgwater Hotel' WHERE id = 406298;
UPDATE cms_hotel SET name = 'Grand Mercure Foshan Country Garden' WHERE id = 408049;
UPDATE cms_hotel SET name = 'Novotel Vijayawada Varun' WHERE id = 408050;
UPDATE cms_hotel SET name = 'ibis Poznan Centrum' WHERE id = 408064;
UPDATE cms_hotel SET name = 'ibis Styles Bamberg' WHERE id = 408400;
UPDATE cms_hotel SET name = 'ibis Styles Brindisi' WHERE id = 408401;
UPDATE cms_hotel SET name = 'SO Sofitel Auckland' WHERE id = 408405;
UPDATE cms_hotel SET name = 'ibis Styles Wien Messe Prater' WHERE id = 416883;
UPDATE cms_hotel SET name = 'Hôtel de la Coupole - MGallery by Sofitel' WHERE id = 416898;
UPDATE cms_hotel SET name = 'ibis budget Knokke' WHERE id = 416906;
UPDATE cms_hotel SET name = 'Mama Shelter Toulouse' WHERE id = 417135;
UPDATE cms_hotel SET name = 'Aparthotel Adagio Bremen' WHERE id = 417136;
UPDATE cms_hotel SET name = 'Pullman Baotou' WHERE id = 417183;