_corporate_attractions:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAttractions, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_dealSearch:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/deals-and-activities"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateDealSearchAll, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_attractions_search:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/attractions-search"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAttractionsSearch, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: "" }
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_activities_and_deals:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/corporate-activities-and-deals"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateActivitiesAndDeals, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_airport_transport:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/transport/airport"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAirportTransport, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_book_now:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/book-now"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateBookNow, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_tourDetails_activities_:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/activities/{city}/{dealName}/{packageId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateTourDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", packageId: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_dealSearch_activities:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/activities"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateSearchActivities, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "activities", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_tourDetails_tours_:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/tours/{city}/{dealName}/{packageId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateTourDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", packageId: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_dealSearch_tours:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/tours"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateSearchTours, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "activities", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_dealSearch_attractions_dealName:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/attractions/{dealName}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateDealNameSearchAttractions, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "activities", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_tourDetails_attractions_:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/attractions/{city}/{dealName}/{packageId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateTourDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", packageId: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_dealSearch_attractions:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/attractions"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateSearchAttractions, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "activities", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_cityDealSearch:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/activities/{city}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateDealSearch, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "all", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_corporateGetLoadMore:
    path: "/corporate/ajax/deals/corporateGetLoadMore"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateGetLoadMore, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", type: "all", city: "", priority: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_tourDetails:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/deals/tourDetails-{packageId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateTourDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", packageId: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_attractionsForm:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/deals/attractions-form"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAttractionsForm, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", packageId: "", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_getTourPriceDetails:
    path: "/corporate/ajax/deals/getTourPriceDetails"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporatePriceDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_getActivityReviews:
    path: "/corporate/ajax/deals/getActivityReviews"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateActivityReviews, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_deals_booking_details:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/booking-details-{bookingId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateDealsBookingDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_deals_booking_process:
    host: "corporate{subdomain_suffix}.{domain}"
    path: "/corporate/deals/processBooking"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateProcessBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_account_waiting_approval:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/account/waiting-approval"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAccountWaitingApproval, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corpo_payment_deals_proceed:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/proceed/payment/{module_id}/{reservation_id}/{user_id}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateProceedPayment, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", reservationId: "", accountId: "", userId: "", transactionUserId: "", requestServicesDetailsId: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_proceed_booking_with_approval:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/reservation/approve/{reservationId}/{accountId}/{userId}/{transactionUserId}/{requestServicesDetailsId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:proceedBookingWithApproval, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", reservationId: "", accountId: "", userId: "", transactionUserId: "", requestServicesDetailsId: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_deals_booking_approval_details:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/reservation/approval/{reservationId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateDealsBookingApprovalDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_airport_cities_listing:
    path:      "/corporate/ajax/deals/cities-listing"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAirportCitiesListing, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_airport_listing:
    path:      "/corporate/ajax/deals/airport-listing"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateAirportListing, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_airport_vehicles_listing:
    path:      "/corporate/ajax/deals/airport-vehicles-listing"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateGetTransportVehicles, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_book_transport:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/book-transport"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateBookTransport, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_dealBookingDetails:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/deals-booking-details-{bookingId}"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateViewBookingDetails, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_quoteBooking:
    path:      "/corporate/ajax/deals/quote-booking"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateQuoteBooking, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"

_corporate_getMandatoryFields:
    host: "corporate{subdomain_suffix}.{domain}"
    path:      "/corporate/deals/get-mandatory-fields"
    defaults: { _controller: CorporateBundle:PackagesCorpo:corporateGetMandatoryFields, _locale: "%locale%", domain: "%domain%", subdomain_suffix: "%subdomain_suffix%", seotitle: "", seodescription: "", seokeywords: ""}
    requirements:
        domain: "[^/]+"
        subdomain_suffix: ".*"
