HotelBundle\Entity\CmsHotelCity:
    type: entity
    table: cms_hotel_city
    repositoryClass: HotelBundle\Repository\HRSRepository
    indexes:
        source:
            columns:
                - source
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cityName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: city_name        
        locationId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: location_id
        popularity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        cityId:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
            column: city_id
        source:
            type: string
            nullable: false
            length: 20
    lifecycleCallbacks: {  }
