HotelBundle\Entity\HotelToHotelDivisions:
    type: entity
    table: hotel_to_hotel_divisions
    repositoryClass: HotelBundle\Repository\HotelRepository
        
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 50
            column: name
        hotelId:
            type: integer
            nullable: false
            column: hotel_id
        hotelDivisionId:
            type: integer
            nullable: false
            column: hotel_division_id
        sortOrder:
            type: integer
            nullable: false
            column: sort_order
    lifecycleCallbacks: {  }