HotelBundle\Entity\HotelDivisions:
    type: entity
    table: hotel_divisions
    repositoryClass: HotelBundle\Repository\HotelRepository
        
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            column: name
        hotelDivisionCategoryId:
            type: integer
            nullable: false
            column: hotel_division_category_id
        parentId:
            type: integer
            nullable: true
            column: parent_id
        otaId:
            type: integer
            nullable: true
            column: ota_id
        sortOrder:
            type: integer
            nullable: false
            column: sort_order
    lifecycleCallbacks: {  }