HotelBundle\Entity\MlFacilityType:
    type: entity
    table: ml_facility_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        langCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lang_code
    lifecycleCallbacks: {  }
