HotelBundle\Entity\MlHotel:
    type: entity
    table: ml_hotel
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        hotelId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: hotel_id
        langCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lang_code
    lifecycleCallbacks: {  }
