HotelBundle\Entity\OtaCodes:
    type: entity
    table: ota_codes
    repositoryClass: HotelBundle\Repository\HotelRepository

    indexes:
        category_code:
            columns:
                - category
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        category:
            type: string
            nullable: false
            length: 3
            options:
                fixed: true
        code:
            type: integer
            nullable: false
            options:
                unsigned: true
        value:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
