TTBundle\Entity\Airline:
    type: entity
    table: airline
    indexes:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 4
            options:
                fixed: false
        alternativeBusinessName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: alternative_business_name
        logo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
