TTBundle\Entity\Alias:
    type: entity
    table: alias
    repositoryClass: TTBundle\Repository\TTRepository
    uniqueConstraints:
        alias:
            columns:
                - alias
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        alias:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        entityType:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: entity_type
        entityId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: entity_id
    lifecycleCallbacks: {  }
