TTBundle\Entity\AliasSeo:
    type: entity
    table: alias_seo
    repositoryClass: TTBundle\Repository\TTRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        keywords:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        published:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
