TTBundle\Entity\CmsAllcategories:
    type: entity
    table: cms_allcategories
    repositoryClass: TTBundle\Repository\PhotosVideosRepository
    indexes:
        show_home:
            columns:
                - show_home
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        itemOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: item_order
        showHome:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: show_home
    lifecycleCallbacks: {  }
