TTBundle\Entity\CmsBagitem:
    type: entity
    table: cms_bagitem
    repositoryClass: TTBundle\Repository\UserLoginRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        type:
            type: integer
            nullable: false
            options:
                unsigned: false
        bagId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: bag_id
        itemId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: item_id
    lifecycleCallbacks: {  }
