TTBundle\Entity\CmsChannelLinks:
    type: entity
    table: cms_channel_links
    repositoryClass: TTBundle\Repository\ChannelRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        channelid:
            type: integer
            nullable: false
            options:
                unsigned: false
        link:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        isSocial:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: is_social
    lifecycleCallbacks: {  }
