TTBundle\Entity\CmsChannelBrochure:
    type: entity
    table: cms_channel_brochure
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        channelid:
            type: integer
            nullable: false
            options:
                unsigned: false
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        photo:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        pdf:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        createTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: create_ts
        published:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        likeValue:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: like_value
        upVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: up_votes
        downVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: down_votes
        nbShares:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_shares
        isVisible:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: is_visible
        enableShareComment:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: enable_share_comment
        nbComments:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: nb_comments
    lifecycleCallbacks: {  }
