TTBundle\Entity\CmsChannelNews:
    type: entity
    table: cms_channel_news
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        channelid:
            type: integer
            nullable: false
            options:
                unsigned: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: create_ts
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        likeValue:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: like_value
        upVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: up_votes
        downVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: down_votes
        nbShares:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_shares
        nbComments:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: nb_comments
        enableShareComment:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: enable_share_comment
        isVisible:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: is_visible
    lifecycleCallbacks: {  }
