TTBundle\Entity\CmsChannelPrivacyExtand:
    type: entity
    table: cms_channel_privacy_extand
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        channelid:
            type: integer
            nullable: false
            options:
                unsigned: false
        privacyType:
            type: boolean
            nullable: false
            column: privacy_type
        kindType:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: kind_type
        connections:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        sponsors:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
