TTBundle\Entity\CmsEntityDescription:
    type: entity
    table: cms_entity_description
    repositoryClass: TTBundle\Repository\CitiesRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityType:
            type: integer
            nullable: false
            options:
                fixed: false
            column: entity_type
        entityId:
            type: integer
            nullable: false
            options:
                fixed: false
            column: entity_id
        description:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
