TTBundle\Entity\CmsEventThemes:
    type: entity
    table: cms_event_themes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        photo:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
    lifecycleCallbacks: {  }
