TTBundle\Entity\CmsFlashReechoe:
    type: entity
    table: cms_flash_reechoe
    indexes:
        share_fk:
            columns:
                - entity_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        entityType:
            type: integer
            nullable: false
            column: entity_type
        createTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: create_ts
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
