TTBundle\Entity\CmsHomeWhereIs:
    type: entity
    table: cms_home_whereis
    repositoryClass: TTBundle\Repository\TTRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: name
        cityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: city_id
    lifecycleCallbacks: {  }
