TTBundle\Entity\CmsInvite:
    type: entity
    table: cms_invite
    indexes:
        from_id:
            columns:
                - from_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fromId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: from_id
        toName:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: to_name
        toEmail:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: to_email
        inviteTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: invite_ts
        path:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
