TTBundle\Entity\CmsIntrestedin:
    type: entity
    table: cms_intrestedin
    repositoryClass: TTBundle\Repository\UserRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
