TTBundle\Entity\CmsMobileRequest:
    type: entity
    table: cms_mobile_request
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        mac:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
            options:
                default: '0'
        createTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: create_ts
        action:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
