TTBundle\Entity\CmsPushNotification:
    type: entity
    table: cms_push_notification
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        msg:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        actionUserId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: action_user_id
        actionType:
            type: boolean
            nullable: true
            column: action_type
        entityId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: entity_id
        entityType:
            type: integer
            nullable: false
            column: entity_type
    lifecycleCallbacks: {  }
