TTBundle\Entity\CmsSocialComments:
    type: entity
    table: cms_social_comments
    indexes:
        user_id:
            columns:
                - user_id
        comment_fk:
            columns:
                - entity_id
        channel_id:
            columns:
                - channel_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        entityType:
            type: integer
            nullable: false
            column: entity_type
        commentText:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: comment_text
        commentDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: comment_date
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        likeValue:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'up_votes - down_votes'
                default: '0'
            column: like_value
        upVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: up_votes
        downVotes:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: down_votes
        isVisible:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: is_visible
        channelId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: channel_id
    lifecycleCallbacks: {  }
