TTBundle\Entity\CmsSocialSharesEmails:
    type: entity
    table: cms_social_shares_emails
    indexes:
        share_id:
            columns:
                - share_id
    id:
        shareId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: share_id
        userEmail:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            id: true
            column: user_email
    lifecycleCallbacks: {  }
