TTBundle\Entity\CmsSocialRatings:
    type: entity
    table: cms_social_ratings
    repositoryClass: TTBundle\Repository\ReviewsRepository
    indexes:
        channel_id:
            columns:
                - channel_id
        single_rate:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        entityType:
            type: integer
            nullable: false
            column: entity_type
        rateType:
            type: integer
            nullable: false
            column: rate_type
        ratingValue:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: rating_value
        ratingTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: rating_ts
        ratingStatus:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: rating_status
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        channelId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: channel_id
    lifecycleCallbacks: {  }
