TTBundle\Entity\CmsSocialFavorites:
    type: entity
    table: cms_social_favorites
    indexes:
        channel_id:
            columns:
                - channel_id
        single_favorite:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        entityType:
            type: integer
            nullable: false
            column: entity_type
        favoriteTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: favorite_ts
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        channelId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: channel_id
    lifecycleCallbacks: {  }
