TTBundle\Entity\CmsSocialSharesUsers:
    type: entity
    table: cms_social_shares_users
    indexes:
        share_id:
            columns:
                - share_id
                - user_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        shareId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: share_id
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
