TTBundle\Entity\CmsTrends:
    type: entity
    table: cms_trends
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: city_id
        cityName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: city_name
    lifecycleCallbacks: {  }
