TTBundle\Entity\Coupon:
    type: entity
    table: coupon
    repositoryClass: TTBundle\Repository\TTRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        campaignId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: campaign_id
        couponCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: coupon_code
        entityId:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: entity_id
        entityTypeId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: entity_type_id
        creationDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: creation_date      
    lifecycleCallbacks: {  }
