TTBundle\Entity\CurrencyRate:
    type: entity
    table: currency_rate
    repositoryClass: TTBundle\Repository\CurrencyRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        currencyName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: currency_name
        currencyCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: currency_code
        symbol:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        currencyRate:
            type: float
            nullable: false
            options:
                unsigned: false
            column: currency_rate
        lastUpdate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: last_update
        topCurrency:
            type: boolean
            nullable: false
        used:
            type: boolean
            nullable: false
        displayOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: display_order
           
    lifecycleCallbacks: {  }
