TTBundle\Entity\DatastellarCountrySubType:
    type: entity
    table: datastellar_country_sub_type
    indexes:
        country_id:
            columns:
                - country_id
    uniqueConstraints:
        title:
            columns:
                - title
                - country_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        countryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: country_id
    lifecycleCallbacks: {  }
