TTBundle\Entity\DatastellarCountrySub:
    type: entity
    table: datastellar_country_sub
    indexes:
        country_id:
            columns:
                - country_id
        type:
            columns:
                - type
                - country_id
        title:
            columns:
                - title
                - country_id
    uniqueConstraints:
        slug:
            columns:
                - slug
                - country_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        countryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: country_id
        count:
            type: integer
            nullable: false
            options:
                unsigned: false
        cityId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: city_id
    lifecycleCallbacks: {  }
