TTBundle\Entity\DatastellarPlaceOfInterestName:
    type: entity
    table: datastellar_place_of_interest_name
    uniqueConstraints:
        title:
            columns:
                - title
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
