TTBundle\Entity\DatastellarCountrySubSubSub:
    type: entity
    table: datastellar_country_sub_sub_sub
    indexes:
        country_sub_sub_id:
            columns:
                - country_sub_sub_id
                - country_sub_id
                - country_id
        country_sub_id:
            columns:
                - country_sub_id
                - country_id
        country_id:
            columns:
                - country_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        countrySubSubId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: country_sub_sub_id
        countrySubId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: country_sub_id
        countryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: country_id
        count:
            type: integer
            nullable: false
            options:
                unsigned: false
        cityId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: city_id
    lifecycleCallbacks: {  }
