TTBundle\Entity\DatastellarChain:
    type: entity
    table: datastellar_chain
    uniqueConstraints:
        slug:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
