TTBundle\Entity\DealDay:
    type: entity
    table: deal_day
    indexes:
        deal_id:
            columns:
                - deal_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dealId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: deal_id
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
