TTBundle\Entity\DealDestination:
    type: entity
    table: deal_destination
    indexes:
        deal_id:
            columns:
                - deal_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dealId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: deal_id
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        longitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
        latitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
