TTBundle\Entity\DiscoverHotelsImages:
    type: entity
    table: discover_hotels_images
    repositoryClass: TTBundle\Repository\ReviewsRepository
    indexes:
        hotel_id:
            columns:
                - hotel_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        filename:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        hotelId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: hotel_id
        defaultPic:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: default_pic
    lifecycleCallbacks: {  }
