TTBundle\Entity\DiscoverRestaurantsReviews:
    type: entity
    table: discover_restaurants_reviews
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        restaurantId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: restaurant_id
        oldId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: old_id
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '42'
            column: user_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createTs:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: create_ts
        hideUser:
            type: integer
            nullable: false
            options:
                default: '0'
            column: hide_user
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
