TTBundle\Entity\DiscoverHotelsRooms:
    type: entity
    table: discover_hotels_rooms
    indexes:
        hotel_id:
            columns:
                - hotel_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hotelId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: hotel_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        numPerson:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: num_person
        price:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        pic1:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        pic2:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        pic3:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
