TTBundle\Entity\DiscountType:
    type: entity
    table: discount_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        discountSpecs:
            type: string
            nullable: true
            options:
                fixed: false
            column: discount_specs
    lifecycleCallbacks: {  }
