TTBundle\Entity\DiscoverFacilities:
    type: entity
    table: discover_facilities
    id:
        id:
            type: float
            nullable: false
            precision: 10
            scale: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 510
            options:
                fixed: false
    lifecycleCallbacks: {  }
