TTBundle\Entity\EntityType:
    type: entity
    table: entity_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityTypeKey:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: entity_type_key
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        label:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
