TTBundle\Entity\GlobalRestaurantsLocation:
    type: entity
    table: global_restaurants_location
    indexes:
        city_id:
            columns:
                - city_id
        locality:
            columns:
                - locality
        region:
            columns:
                - region
        country:
            columns:
                - country
        admin_region:
            columns:
                - admin_region
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cityId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: city_id
        locality:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        region:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        adminRegion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: admin_region
        stateCode:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: state_code
    lifecycleCallbacks: {  }
