TTBundle\Entity\MlChannelCategory:
    type: entity
    table: ml_channel_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        langCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lang_code
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
