TTBundle\Entity\MlHomeWhereis:
    type: entity
    table: ml_home_whereis
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        parentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: parent_id
        langCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lang_code
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
