TTBundle\Entity\MlIntrestedin:
    type: entity
    table: ml_intrestedin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        parentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: parent_id
        language:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
