TTBundle\Entity\MlLanguages:
    type: entity
    table: ml_languages
    id:
        code:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
