TTBundle\Entity\MlVideos:
    type: entity
    table: ml_videos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        videoId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: video_id
        langCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lang_code
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        placetakenat:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        keywords:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        lastModified:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: last_modified
        published:
            type: integer
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
