TTBundle\Entity\PageNotFound:
    type: entity
    table: page_not_found
    repositoryClass: TTBundle\Repository\TTRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        lastSeen:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: last_seen
        published:
            type: integer
            nullable: false
            options:
                default: '1'
        n:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 1
    lifecycleCallbacks:
        prePersist: [ onPrePersistSetLastSeen ]
