TTBundle\Entity\PoiGps:
    type: entity
    table: poi_gps
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        poiName:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: poi_name
        category:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        countryCode:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: country_code
        countryName:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: country_name
        poiLatitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: poi_latitude
        poiLongitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: poi_longitude
        status:
            type: boolean
            nullable: true
            options:
                default: '0'
    lifecycleCallbacks: {  }
