TTBundle\Entity\RestaurantUae:
    type: entity
    table: restaurant_uae
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        resName:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: res_name
        resDescription:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: res_description
        resAbout:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
            column: res_about
        resWebsite:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: res_website
        resAddress:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: res_address
        city:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        countryName:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: country_name
        countryCode:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: country_code
        resContact:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: res_contact
        resLatitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: res_latitude
        resLongitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: res_longitude
        resImagelink:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: res_imagelink
        resLink:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: res_link
        resCost:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: res_cost
        resFeature:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: res_feature
        openingHr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: opening_hr
        resFax:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: res_fax
        status:
            type: boolean
            nullable: true
            options:
                default: '0'
    lifecycleCallbacks: {  }
