TTBundle\Entity\States:
    type: entity
    table: states
    repositoryClass: TTBundle\Repository\CitiesRepository
    indexes:
        country_code:
            columns:
                - country_code
        state_code:
            columns:
                - state_code
        state_name:
            columns:
                - state_name
        country_code_2:
            columns:
                - country_code
                - state_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        countryCode:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
                default: ''
            column: country_code
        stateCode:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: ''
            column: state_code
        stateName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: state_name
        popularity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
