TTBundle\Entity\Test1:
    type: entity
    table: test1
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        factualId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: factual_id
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
