TTBundle\Entity\TransactionSource:
    type: entity
    table: transaction_source
    
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY       
    fields:
        code:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
            column: code
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: name
    lifecycleCallbacks: {  }