TTBundle\Entity\TTMediaTypes:
    type: entity
    table: tt_media_types
        
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            column: name    
    lifecycleCallbacks: {  }