NewFlightBundle\Entity\FlightBaggageInfo:
    type: entity
    table: flight_baggage_info
    indexes:
        flight_selected_details_id:
            columns:
                - flight_selected_details_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        flightSelectedDetailsId:
            type: integer
            nullable: false
        pieces:
            type: integer
            nullable: true
        weight:
            type: integer
            nullable: true
        unit:
            type: string
            nullable: true
            length: 5
        description:
            type: string
            nullable: true
            length: 255
    lifecycleCallbacks: {  }
