CorporateBundle\Entity\CorpoNotificationUsers:
    type: entity
    table: corpo_notification_users
    repositoryClass: CorporateBundle\Repository\Admin\CorpoNotificationUsersRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accountId:
            type: integer
            nullable: false
            column: account_id  
        userId:
            type: integer
            nullable: false
            column: user_id 
        notificationId:
            type: integer
            nullable: false
            column: notification_id        
    lifecycleCallbacks: {  }
