CorporateBundle\Entity\CorpoDefineServices:
    type: entity
    table: corpo_define_services
    repositoryClass: CorporateBundle\Repository\Admin\CorpoDefineServicesRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            column: name
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: active         
    lifecycleCallbacks: {  }
