CorporateBundle\Entity\CorpoAdminMenuRoles:
    type: entity
    table: corpo_admin_menu_roles
    repositoryClass: CorporateBundle\Repository\Admin\CorpoAdminMenuRolesRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cmsUserGroupId:
            type: integer
            nullable: false
            column: cms_user_group_id 
        corpoAdminMenuId:
            type: integer
            nullable: false
            column: corpo_admin_menu_id
    lifecycleCallbacks: {  }
