CorporateBundle\Entity\CorpoAgencies.orm:
    type: entity
    table: corpo_agencies
    repositoryClass: CorporateBundle\Repository\Admin\CorpoAgenciesRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            column: name
        countryId:
            type: integer
            nullable: false
            column: country_id            
    lifecycleCallbacks: {  }
