CorporateBundle\Entity\corpoAccountType:
    type: entity
    table: corpo_user_profile_menus_permission
    repositoryClass: CorporateBundle\Repository\Admin\CorpoProfilePermissionsRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        profileid:
            type: integer
            nullable: false
            column: user_profile_id
        menuId:
            type: integer
            nullable: false
            column: corpo_menu_id
        updatedBy:
            type: integer
            nullable: false
            column: updated_by
        updateOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: update_on
    lifecycleCallbacks: {  }