CorporateBundle\Entity\CorpoRequestServicesEmployee:
    type: entity
    table: corpo_request_services_employee
    repositoryClass: CorporateBundle\Repository\Admin\CorpoRequestServicesEmployeeRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        employeeId:
            type: integer
            nullable: false
            column: employee_id
        requestId:
            type: integer
            nullable: false
            column: request_id    
    lifecycleCallbacks: {  }
