CorporateBundle\Entity\CorpoAdminUsers:
    type: entity
    table: corpo_admin_users
    repositoryClass: CorporateBundle\Repository\Admin\CorpoAdminUsersRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fname:
            type: string
            nullable: false
            length: 20
            column: fname
        lname:
            type: string
            nullable: false
            length: 20
            column: lname
        password:
            type: string
            nullable: false
            length: 255
            column: password        
        salt:
            type: string
            nullable: false
            length: 255
            column: salt     
        email:
            type: string
            nullable: false
            length: 100
            column: email      
    lifecycleCallbacks: {  }
