CorporateBundle\Entity\CorpoDepartments.orm:
    type: entity
    table: corpo_departments
    repositoryClass: CorporateBundle\Repository\Admin\CorpoDepartmentsRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            column: name
        accountId:
            type: integer
            nullable: false
            column: account_id            
    lifecycleCallbacks: {  }
