CorporateBundle\Entity\CorpoPaymentType:
    type: entity
    table: corpo_payment_type
    repositoryClass: CorporateBundle\Repository\Admin\CorpoPaymentTypeRepository
    indexes:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            column: name  
        code:
            type: string
            nullable: false
            length: 5
            column: code      
    lifecycleCallbacks: {  }
