INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Jekyll Island', '12114', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kadyny, Gmina Tolkmicko (Warmian-Masurian Voivodeship)', '12330', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kühtai, Silz (Tyrol)', '13347', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Licheń Stary, Gmina Ślesin (Greater Poland Voivodeship)', '14544', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neustift im Mühlkreis (Upper Austria)', '18415', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Providencia', '20640', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schönberg bei Niederwölz, Schönberg-Lachtal (Styria)', '23304', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schörfling am Attersee (Upper Austria)', '23328', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'St. Croix', '24645', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wald im Pinzgau (Salzburg)', '27902', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wilkasy, Gmina Giżycko (Warmian-Masurian Voivodeship)', '28713', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oléron', '29534', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Koh Phuket (Changwat Phuket)', '29667', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Fischbach (Styria)', '71576', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mühlbachl (Tyrol)', '74724', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mühlheim am Inn (Upper Austria)', '74754', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Altenberg an der Rax (Styria)', '74844', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Georgen am Längsee (Carinthia)', '87506', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Yokohama-shi (Kanagawa Prefecture)', '98352', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Donnersbach (Styria)', '102354', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Horní Branná (Liberecký)', '115535', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rohrberg (Tyrol)', '159372', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Limas (Rhône-Alpes)', '159634', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Krakauhintermühlen (Styria)', '160179', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Großklein (Styria)', '164239', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Châtel-Guyon (Auvergne)', '164469', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Juelsminde, Hedensted (Central Denmark Region)', '169913', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Feldkirchen an der Donau (Upper Austria)', '170575', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Möggers (Vorarlberg)', '171936', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberwölz Stadt (Styria)', '173996', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'île - Saint-Barthélemy', '177784', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Marienkirchen bei Schärding (Upper Austria)', '179506', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Eschenau (Lower Austria)', '179807', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Karrösten (Tyrol)', '184038', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Großlobming (Styria)', '186661', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Julbach (Upper Austria)', '189408', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Groß Sankt Florian (Styria)', '189569', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hüttenberg (Carinthia)', '192860', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rietz (Tyrol)', '196236', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Röthis (Vorarlberg)', '196764', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Stetten (Lower Austria)', '199027', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Lorenzen im Mürztal (Styria)', '199156', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Martin im Mühlkreis (Upper Austria)', '199160', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schlierbach (Upper Austria)', '199708', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Johnsbach (Styria)', '202601', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zöblen (Tyrol)', '205899', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kirchberg an der Pielach (Lower Austria)', '206411', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Andorf (Upper Austria)', '207772', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Angern an der March (Lower Austria)', '207775', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ardagger Markt, Ardagger (Lower Austria)', '207784', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Arzl im Pitztal (Tyrol)', '207788', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Aschach an der Donau (Upper Austria)', '207789', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Aurach bei Kitzbühel (Tyrol)', '207802', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Bad Waltersdorf (Styria)', '207816', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Berg im Attergau (Upper Austria)', '207827', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Bizau (Vorarlberg)', '207840', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Blons (Vorarlberg)', '207843', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Breitenwang (Tyrol)', '207853', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Bruck am Ziller (Tyrol)', '207858', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Buch in Tirol (Tyrol)', '207862', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Dellach im Drautal (Carinthia)', '207869', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ebenthal in Kärnten (Carinthia)', '207894', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Eidenberg (Upper Austria)', '207920', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ellbögen (Tyrol)', '207927', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Elmen (Tyrol)', '207928', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Engerwitzdorf (Upper Austria)', '207933', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Enzersdorf an der Fischa (Lower Austria)', '207936', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ernsthofen (Lower Austria)', '207941', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Feistritz im Rosental (Carinthia)', '207951', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Feldkirchen bei Graz (Styria)', '207954', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Fels am Wagram (Lower Austria)', '207956', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Fischamend (Lower Austria)', '207962', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Frankenburg am Hausruck (Upper Austria)', '207978', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gaal (Styria)', '208002', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gabersdorf (Styria)', '208003', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Garanas (Styria)', '208013', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Geboltskirchen (Upper Austria)', '208021', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gnesau (Carinthia)', '208044', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gramatneusiedl (Lower Austria)', '208064', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Grünbach am Schneeberg (Lower Austria)', '208080', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hardegg (Lower Austria)', '208120', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hart bei Graz (Styria)', '208124', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Heimschuh (Styria)', '208142', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Heinfels (Tyrol)', '208143', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hohenthurn (Carinthia)', '208183', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hollenstein an der Ybbs (Lower Austria)', '208187', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Imsterberg (Tyrol)', '208202', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Innerbraz (Vorarlberg)', '208203', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Innerschwand am Mondsee (Upper Austria)', '208204', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Inzing (Tyrol)', '208208', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Iselsberg, Iselsberg-Stronach (Tyrol)', '208213', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Köstendorf (Salzburg)', '208231', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kapfenstein (Styria)', '208249', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kirchschlag in der Buckligen Welt (Lower Austria)', '208287', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kitzeck im Sausal (Styria)', '208292', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kleinsölk (Styria)', '208305', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Koppl (Salzburg)', '208320', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kottingbrunn (Lower Austria)', '208322', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Lannach (Styria)', '208366', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Lechaschau (Tyrol)', '208377', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Leisach (Tyrol)', '208379', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mannersdorf an der Rabnitz (Burgenland)', '208423', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Maria Lankowitz (Styria)', '208428', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Maria-Lanzendorf (Lower Austria)', '208429', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Maria Rain (Carinthia)', '208431', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mariahof (Styria)', '208436', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Florian (Upper Austria)', '208443', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Marz (Burgenland)', '208446', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mautern in Steiermark (Styria)', '208453', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mitterkirchen im Machland (Upper Austria)', '208475', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mogersdorf (Burgenland)', '208479', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Molln (Upper Austria)', '208480', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Münchendorf (Lower Austria)', '208488', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Musau (Tyrol)', '208493', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Natternbach (Upper Austria)', '208501', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neidling (Lower Austria)', '208504', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neuhaus am Klausenbach (Burgenland)', '208515', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neuhofen im Innkreis (Upper Austria)', '208518', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neukirchen am Großvenediger (Salzburg)', '208519', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neukirchen bei Lambach (Upper Austria)', '208523', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neutal (Burgenland)', '208533', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Niederthalheim (Upper Austria)', '208540', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Nußbach (Upper Austria)', '208548', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberhaag (Styria)', '208558', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberhofen am Irrsee (Upper Austria)', '208559', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Obernberg am Brenner (Tyrol)', '208564', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberndorf in Tirol (Tyrol)', '208569', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberschützen (Burgenland)', '208572', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Opponitz (Lower Austria)', '208591', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Parndorf (Burgenland)', '208616', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pernegg an der Mur (Styria)', '208630', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pflach (Tyrol)', '208642', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Polling im Innkreis (Upper Austria)', '208667', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pusterwald (Styria)', '208694', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Raggal (Vorarlberg)', '208709', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Raiding (Burgenland)', '208711', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rainbach im Mühlkreis (Upper Austria)', '208713', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ranten (Styria)', '208718', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Riefensberg (Vorarlberg)', '208753', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ritzing (Burgenland)', '208756', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Roßleithen (Upper Austria)', '208767', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Aegyd am Neuwalde (Lower Austria)', '208780', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Blasen (Styria)', '208787', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Florian am Inn (Upper Austria)', '208789', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Gerold (Vorarlberg)', '208803', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Jakob im Walde (Styria)', '208806', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Jakob in Haus (Tyrol)', '208808', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Johann im Walde (Tyrol)', '208815', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Kathrein am Offenegg (Styria)', '208819', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Lorenz (Upper Austria)', '208824', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Martin am Grimming (Styria)', '208839', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Martin an der Raab (Burgenland)', '208840', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Martin im Sulmtal (Styria)', '208843', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Michael in Obersteiermark (Styria)', '208847', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Oswald (Lower Austria)', '208856', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Peter am Kammersberg (Styria)', '208859', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Sigmund im Sellrain (Tyrol)', '208871', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Stefan ob Leoben (Styria)', '208874', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Stefan ob Stainz (Styria)', '208875', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Ulrich bei Steyr (Upper Austria)', '208880', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Veit im Pongau (Salzburg)', '208882', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sattledt (Upper Austria)', '208888', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schöder (Styria)', '208891', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schönberg im Stubaital (Tyrol)', '208894', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schönwies (Tyrol)', '208896', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sigmundsherberg (Lower Austria)', '208963', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Spielfeld (Styria)', '208977', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Stambach (Styria)', '208992', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Stattegg (Styria)', '208997', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Steinbach am Attersee (Upper Austria)', '209001', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Stoob (Burgenland)', '209014', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Straß im Attergau (Upper Austria)', '209018', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Strengen (Tyrol)', '209024', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Suben (Upper Austria)', '209032', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tarsdorf (Upper Austria)', '209038', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Thurn (Tyrol)', '209058', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tieschen (Styria)', '209060', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Timelkam (Upper Austria)', '209061', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tobaj (Burgenland)', '209063', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tristach (Tyrol)', '209079', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tulfes (Tyrol)', '209085', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tweng (Salzburg)', '209088', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Unternberg (Salzburg)', '209101', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Untertilliach (Tyrol)', '209105', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Veitsch (Styria)', '209115', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Viktorsberg (Vorarlberg)', '209120', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wörschach (Styria)', '209132', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Waldkirchen am Wesen (Upper Austria)', '209148', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Weißkirchen in Steiermark (Styria)', '209184', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Werfen (Salzburg)', '209189', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wiener Neudorf (Lower Austria)', '209197', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wolfurt (Vorarlberg)', '209218', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zellerndorf (Lower Austria)', '209237', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zeutschach (Styria)', '209241', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Achau (Lower Austria)', '234163', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Aflenz Land (Styria)', '234170', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Aigen im Ennstal (Styria)', '234177', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Albeck (Carinthia)', '234181', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Außervillgraten (Tyrol)', '234213', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Bürs (Vorarlberg)', '234242', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Euratsfeld (Lower Austria)', '234262', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Clovelly, Fish Hoek (Western Cape)', '235117', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Allerheiligen im Mürztal (Styria)', '236985', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Albufeira (Faro)', '237312', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gallbrunn, Trautmannsdorf an der Leitha (Lower Austria)', '288705', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Steeg, Bad Goisern am Hallstättersee (Upper Austria)', '289091', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kritzendorf, Klosterneuburg (Lower Austria)', '289694', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Euboea', '290479', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Syros', '290546', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Thēra', '290548', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Georgen ob Murau (Styria)', '291029', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Long Island', '291058', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sal, Cape Verde', '291073', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Miyakejima', '291181', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sułkowice, Gmina Andrychów (Lesser Poland Voivodeship)', '294320', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zakrzów, Gmina Gogolin (Opole Voivodeship)', '295508', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Krzywaczka, Gmina Sułkowice (Lesser Poland Voivodeship)', '298593', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Łąka Prudnicka, Gmina Prudnik (Opole Voivodeship)', '299428', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zgłobice, Gmina Tarnów (Lesser Poland Voivodeship)', '300145', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Żukczyn, Gmina Pruszcz Gdański (Pomeranian Voivodeship)', '301161', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kanie, Gmina Brwinów (Masovian Voivodeship)', '310013', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Koszuty, Gmina Środa Wielkopolska (Greater Poland Voivodeship)', '312066', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Chobot, Gmina Halinów (Masovian Voivodeship)', '312210', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Charzykowy, Gmina Chojnice (Pomeranian Voivodeship)', '320394', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Grzybowo, Gmina Kołobrzeg (West Pomeranian Voivodeship)', '327610', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ludwikowice Kłodzkie, Gmina Nowa Ruda (Lower Silesian Voivodeship)', '333476', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Grębiszew, Gmina Mińsk Mazowiecki (Masovian Voivodeship)', '333980', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Dźwirzyno, Gmina Kołobrzeg (West Pomeranian Voivodeship)', '335535', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mrzeżyno, Gmina Trzebiatów (West Pomeranian Voivodeship)', '337285', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Seefeld, Seefeld-Kadolz (Lower Austria)', '338024', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Egg, Hermagor-Pressegger See (Carinthia)', '338051', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Radnig, Hermagor-Pressegger See (Carinthia)', '338054', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Jormannsdorf, Bad Tatzmannsdorf (Burgenland)', '338204', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ried, Sankt Gilgen (Salzburg)', '338219', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Matzing, Seeham (Salzburg)', '338222', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neuseß, Mauterndorf (Salzburg)', '338233', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pfarrkirchen im Mühlkreis (Upper Austria)', '338247', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Karlsbach, Pfarrkirchen im Mühlkreis (Upper Austria)', '338250', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Lämmerbach, Hintersee (Salzburg)', '338308', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rems, Sankt Valentin (Lower Austria)', '338324', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sagritz, Großkirchheim (Carinthia)', '338368', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tiffen, Steindorf am Ossiacher See (Carinthia)', '338400', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ardagger Stift, Ardagger (Lower Austria)', '338556', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Laubendorf, Millstatt (Carinthia)', '338781', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mühldorf (Carinthia)', '338787', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neudauberg, Burgauberg-Neudauberg (Burgenland)', '338899', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Sebastian (Styria)', '339056', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wesenufer, Waldkirchen am Wesen (Upper Austria)', '339179', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gruben, Thomatal (Salzburg)', '339220', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sattelbach, Heiligenkreuz (Lower Austria)', '339289', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Nebersdorf, Großwarasdorf (Burgenland)', '339297', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hagensdorf im Burgenland, Heiligenbrunn (Burgenland)', '339311', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Petschnitzen, Finkenstein am Faaker See (Carinthia)', '339347', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hinterberg, Texingtal (Lower Austria)', '339396', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Texing, Texingtal (Lower Austria)', '339400', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Birnbaum, Lesachtal (Carinthia)', '339443', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Liesing, Lesachtal (Carinthia)', '339447', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Obersammelsdorf, Sankt Kanzian am Klopeiner See (Carinthia)', '339511', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Verditz, Treffen am Ossiacher See (Carinthia)', '339615', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Annenheim, Treffen am Ossiacher See (Carinthia)', '339620', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Alt-Nagelberg, Brand-Nagelberg (Lower Austria)', '339692', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Greuth, Villach (Carinthia)', '339718', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Watschig, Hermagor-Pressegger See (Carinthia)', '339732', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Paßriach, Hermagor-Pressegger See (Carinthia)', '339739', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Emmersdorf, Nötsch im Gailtal (Carinthia)', '339748', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Unterbildein, Bildein (Burgenland)', '339874', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Techendorf, Weißensee (Carinthia)', '340039', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neusach, Weißensee (Carinthia)', '340040', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Eisentratten, Krems in Kärnten (Carinthia)', '340049', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Thalgauberg, Thalgau (Salzburg)', '340165', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Annarotte, Annaberg (Lower Austria)', '340351', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tschau, Arnoldstein (Carinthia)', '340595', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rauth, Feld am See (Carinthia)', '340613', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mallenitzen, Finkenstein am Faaker See (Carinthia)', '340620', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Untergreuth, Finkenstein am Faaker See (Carinthia)', '340621', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Harbach, Moorbad Harbach (Lower Austria)', '340644', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kroatisch Minihof, Nikitsch (Burgenland)', '340842', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Edlach an der Rax, Reichenau an der Rax (Lower Austria)', '340939', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Georgen im Lavanttal (Carinthia)', '341022', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kogl, Sankt Georgen im Attergau (Upper Austria)', '341140', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wiesenegg, Saalbach-Hinterglemm (Salzburg)', '341150', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Ach, Hochburg-Ach (Upper Austria)', '341250', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neukirchen, Altmünster (Upper Austria)', '341267', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rußbachsaag, Rußbach am Paß Gschütt (Salzburg)', '341458', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Neu-Anif, Anif (Salzburg)', '341464', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Guggenberg, Tiefgraben (Upper Austria)', '342715', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hof, Tiefgraben (Upper Austria)', '342716', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schattbach, Eben im Pongau (Salzburg)', '343134', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Jakob-Breitenau, Breitenau am Hochlantsch (Styria)', '343435', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Viechtau, Traunkirchen (Upper Austria)', '343478', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Au an der Donau, Naarn im Machlande (Upper Austria)', '343636', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Aufhausen, Piesendorf (Salzburg)', '343676', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Leopoldschlag Markt, Leopoldschlag (Upper Austria)', '343745', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Weitenegg, Leiben (Lower Austria)', '343880', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Buchen, Telfs (Tyrol)', '344222', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tumpen, Umhausen (Tyrol)', '344289', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kosten, Assling (Tyrol)', '344392', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sonnseite, Ellmau (Tyrol)', '344425', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberried, Längenfeld (Tyrol)', '344533', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Feistritz, Sankt Jakob in Defereggen (Tyrol)', '344605', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Erlsbach, Sankt Jakob in Defereggen (Tyrol)', '344608', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Arnbach, Sillian (Tyrol)', '344617', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schrottendorf, Assling (Tyrol)', '344756', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'St Wolfgang, Sankt Wolfgang-Kienberg (Styria)', '344793', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Dörfla, Gössendorf (Styria)', '344805', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Maria Luggau, Lesachtal (Carinthia)', '344886', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pill (Tyrol)', '344977', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Heiligenbrunn (Burgenland)', '345033', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Stein (Styria)', '345104', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Groß Meinharts, Groß Gerungs (Lower Austria)', '345124', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Katsch an der Mur, Frojach-Katsch (Styria)', '345173', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Vasoldsberg (Styria)', '345315', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Au, Großarl (Salzburg)', '345627', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Landscha bei Weiz, Thannhausen (Styria)', '345840', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberperfuss (Tyrol)', '345865', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Itter (Tyrol)', '345944', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Aberg, Maria Alm am Steinernen Meer (Salzburg)', '346021', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schwendt (Tyrol)', '346104', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mantscha, Attendorf (Styria)', '346114', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Miklauzhof, Sittersdorf (Carinthia)', '346164', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Haller, Nesselwängle (Tyrol)', '346247', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Klaunz, Matrei in Osttirol (Tyrol)', '346306', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Nußdorf, Nußdorf-Debant (Tyrol)', '346316', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Otting, Leogang (Salzburg)', '346350', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pühret, Neustift im Mühlkreis (Upper Austria)', '346412', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Lorenzen im Lesachtal, Lesachtal (Carinthia)', '346419', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Tröpolach, Hermagor-Pressegger See (Carinthia)', '346427', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wagerberg, Bad Waltersdorf (Styria)', '346501', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Prarath, Gleinstätten (Styria)', '346522', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Völlegg, Fischbach (Styria)', '346549', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Alexenau, Weyregg am Attersee (Upper Austria)', '346622', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Holz, Wängle (Tyrol)', '346629', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pöllauberg (Styria)', '346636', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Fressenberg, Sankt Marein bei Knittelfeld (Styria)', '346674', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gaisbichl, Niedernsill (Salzburg)', '346746', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberlangkampfen, Langkampfen (Tyrol)', '346760', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Angerberg (Tyrol)', '346761', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Schützenberg, Sankt Martin (Lower Austria)', '346777', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hetzendorf, Fohnsdorf (Styria)', '346891', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pogöriach, Finkenstein am Faaker See (Carinthia)', '346935', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kumitz, Villach (Carinthia)', '346943', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kellerberg, Weißenstein (Carinthia)', '346945', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Bösenlacken, Feldkirchen in Kärnten (Carinthia)', '346950', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Eisenerz (Styria)', '347018', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sonntag Garsella, Sonntag (Vorarlberg)', '347112', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberrotte, Sankt Jakob in Defereggen (Tyrol)', '347312', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Krakauebene, Krakauhintermühlen (Styria)', '347428', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hietzing, Vienna (Vienna)', '347510', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mitterding, Antiesenhofen (Upper Austria)', '347520', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Plangeross, Sankt Leonhard im Pitztal (Tyrol)', '347534', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mühlgraben, Erl (Tyrol)', '347567', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Deutsch Ehrensdorf, Strem (Burgenland)', '347678', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Grieselstein, Jennersdorf (Burgenland)', '347679', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Naggl, Weißensee (Carinthia)', '347694', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zedlach, Matrei in Osttirol (Tyrol)', '347761', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Manhartsbrunn, Großebersdorf (Lower Austria)', '347796', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Rotheau, Eschenau (Lower Austria)', '347799', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Unterberg, Steindorf am Ossiacher See (Carinthia)', '347832', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gai (Styria)', '347873', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kühnsdorf, Eberndorf (Carinthia)', '347927', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Ulrich, Villach (Carinthia)', '348010', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Unterferlach, Finkenstein am Faaker See (Carinthia)', '348024', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Katschberghöhe, Rennweg am Katschberg (Carinthia)', '348071', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Welten, Sankt Martin an der Raab (Burgenland)', '348165', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Moorbad Harbach (Lower Austria)', '348227', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Stuben am Arlberg, Klösterle (Vorarlberg)', '348327', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wolfern (Upper Austria)', '348435', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Untermöschach, Hermagor-Pressegger See (Carinthia)', '348489', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Unterkirchbach, Sankt Andrä-Wördern (Lower Austria)', '348539', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Strebersdorf, Lutzmannsburg (Burgenland)', '348745', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Stefan im Gailtal (Carinthia)', '348776', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sirnitz, Albeck (Carinthia)', '348794', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kreuth ob Rattendorf, Hermagor-Pressegger See (Carinthia)', '348837', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberdorf, Weißensee (Carinthia)', '348900', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Egg, Thalgau (Salzburg)', '348929', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hirschenwies, Moorbad Harbach (Lower Austria)', '349027', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Oswald, Eberstein (Carinthia)', '349102', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sitzenberg, Sitzenberg-Reidling (Lower Austria)', '349126', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Außerbraz, Bludenz (Vorarlberg)', '349186', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Oberndorf bei Salzburg (Salzburg)', '349231', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Almdorf Königsleiten, Wald im Pinzgau (Salzburg)', '349323', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sonnberg, Maria Alm am Steinernen Meer (Salzburg)', '349343', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Unterrettenbach, Sinabelkirchen (Styria)', '349347', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Gosau-Hintertal, Gosau (Upper Austria)', '349487', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Jochbergthurn, Mittersill (Salzburg)', '349659', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wilfersdorf (Lower Austria)', '349865', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Palfen, Altenmarkt im Pongau (Salzburg)', '349867', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Untergaimberg, Gaimberg (Tyrol)', '349883', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Magdalena am Lemberg (Styria)', '349917', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Steirisch Laßnitz, Laßnitz bei Murau (Styria)', '349963', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Huben, Matrei in Osttirol (Tyrol)', '350184', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Hohenbrugg an der Raab, Hohenbrugg-Weinberg (Styria)', '350189', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sankt Marein bei Graz (Styria)', '350215', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Sonnenalpe Naßfeld, Hermagor-Pressegger See (Carinthia)', '350459', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Wolfsthal (Lower Austria)', '350467', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Bach, Nötsch im Gailtal (Carinthia)', '350523', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Menstrup, Næstved (Region Zealand)', '439887', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Belvedere, Tezze sul Brenta (Veneto)', '575662', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Porto Cervo, Arzachena  (Sardinia)', '575747', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'South Yarra, Melbourne (State of Victoria)', '619459', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Torre da Medronheira, Albufeira (Faro)', '918793', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Beer Yaaqov (Central District)', '1192301', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Phi Phi Islands', '1250438', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Zanzibar Island', '1252587', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Kradan Island', '1383390', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Frantschach-Sankt Gertraud (Carinthia)', '1827420', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Pemba Island (Zanzibar)', '3052785', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Dujiangyan, Chengdu (Sichuan Province)', '3054087', '1', NULL, 'hrs');
INSERT INTO `cms_hotel_city` (`id`, `city_name`, `location_id`, `popularity`, `city_id`, `source`) VALUES (NULL, 'Mukim 12 (Barat Daya, Pulau Pinang)', '3157052', '1', NULL, 'hrs');