INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Selma (Indiana)', 786620, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pilot Mountain (North Carolina)', 194285, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Poulainville (Picardie)', 175970, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Van Bibber, Edgewood (Maryland)', 795143, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hidden Valley (Colorado)', 783936, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Livingston (Alabama)', 842898, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Spring Valley (New York)', 209815, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Montpelier (Mississippi)', 800731, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Szeghalom (Békés)', 156558, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Newport East (Rhode Island)', 848981, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Gordonsville (Tennessee)', 182364, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Watertown (Tennessee)', 833085, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Shām Churāsi (State of Punjab)', 590160, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Eastman (Georgia)', 838661, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Comstock Park (Michigan)', 841392, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Penfield (State of South Australia)', 36257, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lewisburg (Mississippi)', 831306, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Grand Prairie (Louisiana)', 835826, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Paw Paw (Michigan)', 193752, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pottsville (Tennessee)', 813920, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hyde Park (Dutchess, New York)', 830966, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Big Water (Utah)', 850442, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Fairview (Erie, Pennsylvania)', 814572, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Montgomeryville (Pennsylvania)', 812464, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Oxford (North Carolina)', 193276, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Corfu (New York)', 188240, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Westminster (Massachusetts)', 28501, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Clayton (North Carolina)', 180514, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Allanton (Florida)', 779524, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Adamsburg (Alabama)', 842241, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Helena (Huron, Michigan)', 791118, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Orlinda (Tennessee)', 193013, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Drouin (State of Victoria)', 622915, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Loveday (State of South Australia)', 620600, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bolivar (Ohio)', 181550, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Higashimatsuyama-shi (Saitama Prefecture)', 3057595, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Buzzards Bay (Massachusetts)', 830714, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Candelaria de La Frontera (Departamento de Santa Ana)', 955664, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Edgewood (Luzerne, Pennsylvania)', 811908, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Forestville (Québec)', 652033, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Vernal (Illinois)', 781863, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Washington, Maysville (Kentucky)', 790433, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Virden (Manitoba)', 665477, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ban Sarachit (Changwat Sukhothai)', 1138640, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Wormleysburg (Pennsylvania)', 194839, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Londonderry (New Hampshire)', 287824, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ledgewood (New Jersey)', 14240, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Newcastle (Oklahoma)', 191851, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Shamokin Dam (Pennsylvania)', 838876, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lewisport (Kentucky)', 195341, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Onerahi', 1216200, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hoisington (Kansas)', 785598, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Arab (Alabama)', 245554, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Colón, Irapuato (Guanajuato)', 3237016, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Magna (Utah)', 209600, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Allegany Grove, La Vale (Maryland)', 832171, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Douglassville (Pennsylvania)', 829335, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Stafford (California)', 828316, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Encino, Los Angeles (California)', 780993, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Midlothian (Virginia)', 289510, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Clairton (Pennsylvania)', 246974, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Tioga (West Virginia)', 840767, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mooresville (Kentucky)', 829636, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Johor', 12230, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('São Miguel do Oeste (Santa Catarina)', 3201703, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Plano (Alabama)', 777372, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Stevenson (Washington)', 817656, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Brunswick (Ohio)', 31983, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rockport (Indiana)', 196509, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Johnson (Arkansas)', 169839, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jasionka, Trzebownisko (Podkarpackie)', 292317, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Payson (Utah)', 19513, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Blackshear (Georgia)', 782072, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Granite City (Illinois)', 181301, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dahlgren (Virginia)', 816864, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Niamey', 18046, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ramsey (Minnesota)', 195796, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Gurzelen (Bern)', 677665, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hoquiam (Washington)', 818915, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mountville (Pennsylvania)', 190938, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Raphine (Virginia)', 21053, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Richburg (New York)', 21404, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Levittown (Sabana Seca, Puerto Rico)', 614537, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Vrtište', 926390, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Georgetown (St. Joseph, Indiana)', 788541, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('St Joseph (Minnesota)', 795751, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bellflower (Illinois)', 167326, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bluewater (California)', 3063210, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Shellsville (Pennsylvania)', 820905, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Kathu (Northern Cape)', 12556, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Russellville (Kentucky)', 177508, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hebron (Indiana)', 159505, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hillsboro (Henry, Indiana)', 785374, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Drizzona (Lombardia)', 534059, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Arden Hills (Minnesota)', 245562, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bando-shi (Ibaraki Prefecture)', 3057688, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mason (Virginia)', 833847, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Denmark (Tennessee)', 815358, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mount Pleasant, Hawthorne (New York)', 831507, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Moundsville (West Virginia)', 823102, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hobbs (Maryland)', 838073, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Middletown (Illinois)', 37591, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cutoff, New Orleans (Louisiana)', 837027, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Union City (West Virginia)', 825100, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Big Stone Gap (Virginia)', 850751, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Etrelles (Bretagne)', 240506, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('High Point (Maryland)', 851339, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cameron Park (California)', 844476, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Tampa (Kansas)', 829070, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Girdwood, Anchorage (Alaska)', 9251, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('St Albans Bay (Vermont)', 827310, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Valencia (Pennsylvania)', 170367, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Goldsby (Oklahoma)', 808643, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rock (Massachusetts)', 831110, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Fuquay-Varina (North Carolina)', 192625, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cahokia (Illinois)', 161590, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jamestown (Elkhart, Indiana)', 836819, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Terrell (Georgia)', 835644, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Marion (Alabama)', 163630, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Haines City (Florida)', 183691, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dillsburg (Pennsylvania)', 247491, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Riverview (South Carolina)', 822736, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Frogmore (South Carolina)', 826689, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mars Hill (North Carolina)', 170342, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bidwell Hill (Pennsylvania)', 820720, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Edgewood (New Mexico)', 804810, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Halls Gap (Victoria)', 162479, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Happy Valley (New Mexico)', 3064735, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('East Liverpool (Ohio)', 180861, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Charmey (Fribourg)', 206798, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('North Liberty (Iowa)', 173702, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bailey (New York)', 830751, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Berwick (Louisiana)', 795003, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Anderson (Missouri)', 165549, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pleasant View (Cheatham, Tennessee)', 827909, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Triadelphia (Ohio)', 853250, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hirao-cho (Yamaguchi Prefecture)', 1195707, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Emmitsburg (Maryland)', 247800, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ontario (Pennsylvania)', 825514, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rockville (Manitowoc, Wisconsin)', 841833, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Barkeyville (Pennsylvania)', 813688, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lachenaie, Terrebonne (Québec)', 228226, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cartersville (Kentucky)', 852526, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Middletown (New Jersey)', 807694, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Glen Morgan (West Virginia)', 821614, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('West Ossipee (New Hampshire)', 847856, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Shorewood (Illinois)', 199089, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ubstadt-Weiher (Baden-Württemberg)', 3103707, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Plankinton (South Dakota)', 812100, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hollywood (Michigan)', 789665, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Greater Napanee (Ontario)', 3083963, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Williamsburg (Massachusetts)', 837213, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Waterford (Michigan)', 209879, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sansha (Hainan Province)', 3054208, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Everett (Massachusetts)', 170682, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Shepparton (Victoria)', 169384, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Windward, Savannah (Georgia)', 781444, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Marietta (Iowa)', 830115, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mount Gambier (South Australia)', 150836, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Plainfield, Plainfield Village (Connecticut)', 784648, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Parkway Hills, Fort Wayne (Indiana)', 839011, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Weil der Stadt (Baden-Württemberg)', 35282, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dar el Beïda (Wilaya d\' Alger)', 760187, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Summerdale (Pennsylvania)', 851723, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('La Unión (Departamento de La Unión)', 63811, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sand Point, Lakeville (New York)', 830227, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('St. Thomas (Ontario)', 228628, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Kimmswick (Missouri)', 190781, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lovington (New Mexico)', 809285, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jequiá da Praia (Alagoas)', 3201577, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Caineville (Utah)', 815598, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Yorkton (Saskatchewan)', 183704, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Yankton (Oregon)', 833218, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Arlington (Oregon)', 809280, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Vandalūr (State of Tamil Nādu)', 590866, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('North Vernon (Indiana)', 192221, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Saint-Fargeau-Ponthierry (Ile-de-France)', 147353, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ali, Vitoria-Gasteiz (País Vasco)', 489972, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hanceville (Alabama)', 778672, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Shivwits (Utah)', 815595, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Trzebinia (Małopolskie)', 3034752, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pickering (Ontario)', 228437, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Purcell (Oklahoma)', 195471, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Barnesville (Pennsylvania)', 839553, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Nellis AFB (Nevada)', 807671, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Parkersburg (Indiana)', 785701, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Indio (Texas)', 824448, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Daleville (Alabama)', 187096, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Savage (Minnesota)', 199614, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dutch Town (Louisiana)', 789231, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jefferson (Jackson, Georgia)', 161094, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rainbow (Connecticut)', 844127, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hixson, Chattanooga (Tennessee)', 1383050, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Appleton (New York)', 851559, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Gundagai (State of New South Wales)', 10126, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Falling Waters (West Virginia)', 821643, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Goddard (Kansas)', 184705, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Coopersville (Michigan)', 247015, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bowling Green (Virginia)', 165677, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('West Pea Ridge, Pea Ridge (West Virginia)', 818853, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Woodward (Iowa)', 168634, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mount Olive (North Carolina)', 190882, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Clarington (Ontario)', 656666, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bruce (Washington)', 817447, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mount Vernon (Iowa)', 190908, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Weeki Wachee (Florida)', 822896, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ferdinand (Indiana)', 788176, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Whitehall (Montana)', 832728, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Blovice (Plzeňský)', 114001, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Kingston Springs (Tennessee)', 194694, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Grain Valley (Missouri)', 170692, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Parsons (Mississippi)', 846868, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Muskegon (Mississippi)', 801917, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Laurel Bay (South Carolina)', 810514, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Seneca (Pennsylvania)', 811768, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Leander (Louisiana)', 845576, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Middletown (Virginia)', 287735, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Graham Heights (West Virginia)', 823081, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Conley (Georgia)', 782672, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ulstein (Møre og Romsdal)', 186065, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Whiteville (North Carolina)', 168109, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Plainwell (Michigan)', 194464, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('McAfee (New Jersey)', 807925, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Whitney (Nevada)', 803692, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Taylors Lakes', 287748, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Newberry (Michigan)', 191844, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Norman (California)', 781265, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rescue (Virginia)', 814670, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('St Johnsbury (Vermont)', 818514, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Allensburg (Ohio)', 803291, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lytle, Fort Worth (Texas)', 812983, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Malden (Massachusetts)', 136060, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Schoharie (New York)', 805379, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('St Stephen (South Carolina)', 815852, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Gold Camp, Gold Canyon (Arizona)', 780986, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Norton (Kansas)', 788241, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jeffersonville (Ohio)', 803555, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Willington (Connecticut)', 287812, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sunland Park (New Mexico)', 187532, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('High Level (Alberta)', 197577, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sergeant Bluff (Iowa)', 851681, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Miravalle, Monterrey (Nuevo León)', 3274496, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('New Westville (Ohio)', 834081, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Schefferville (Québec)', 659653, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rowlett (Texas)', 196831, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Momauguin, East Haven (Connecticut)', 850692, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Caputa (South Dakota)', 853875, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Fresnes-lès-Montauban (Nord-Pas-de-Calais)', 181016, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hackberry (Louisiana)', 791740, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Westover, Augusta-Richmond County consolidated government (Georgia)', 787376, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lake City (Kansas)', 852139, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bogart (Georgia)', 246085, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('George Town (Tasmania)', 61734, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Centerville (Hickman, Tennessee)', 244753, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Paterson (New Jersey)', 138471, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Citrus Hills (Florida)', 835461, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dolní Břežany (Středočeský)', 114953, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('South Blooming Grove (New York)', 3061954, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bluefield (Virginia)', 3059755, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lane Cove', 287752, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pikogan (Québec)', 3089003, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Little Meadows (Pennsylvania)', 161869, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bradley (Illinois)', 181289, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Tuba City (Arizona)', 777407, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Stansted, East Hampshire (England)', 364539, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Southampton (New Brunswick)', 652174, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bluffton (Ohio)', 840971, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Belmont (Wisconsin)', 850073, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Waterford (State of Queensland)', 620525, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Elkton (Florida)', 837797, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Stawell (Victoria)', 206232, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Linconia (Pennsylvania)', 809433, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pottsboro (Texas)', 195085, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jerome (Illinois)', 199310, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Foristell (Missouri)', 165274, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mount Pleasant (Utah)', 824430, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Edgerton (Wisconsin)', 827910, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Duncanwood Brookemead, Nashville (Tennessee)', 3062612, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('South Toms River (New Jersey)', 161527, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Myerstown (Pennsylvania)', 191194, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lieser (Rheinland-Pfalz)', 112555, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Grayslake (Illinois)', 168285, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Farmington (Mississippi)', 795954, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Châtillon (Auvergne)', 161171, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lemon Grove (California)', 192243, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sherbrooke, St. Mary\'s (Nova Scotia)', 23798, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Wardlaw (Texas)', 840213, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Snead, Evans (Georgia)', 853395, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ulceby, East Lindsey (England)', 370925, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Seaman (Ohio)', 808239, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Fresno (Arkansas)', 836623, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Purcell (Pennsylvania)', 839995, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Brimfield (Ohio)', 839676, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Artichoke (Minnesota)', 829682, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Saint-Georges (Québec)', 651021, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cyberjaya, Dengkil (Selangor)', 3158953, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hackettstown (New Jersey)', 169889, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('White Deer (Pennsylvania)', 813408, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Eagle Nest (New Mexico)', 807090, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Grays Knob (Kentucky)', 793516, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Oregon (Wisconsin)', 192960, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Firestone (Colorado)', 193000, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Riverton (New Jersey)', 196378, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Johnstown (Colorado)', 169802, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bethel (Berks, Pennsylvania)', 806088, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Chesterfield (New Hampshire)', 820249, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Morey (Colorado)', 843748, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Beaver Dam (Arizona)', 3067230, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Kushinagar (State of Uttar Pradesh)', 3324987, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pine River (Minnesota)', 799602, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Plainfield Village (Connecticut)', 838990, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Belmont (Michigan)', 788412, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Miner (Missouri)', 794228, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Maple Bluff (Wisconsin)', 192465, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hoopers Creek (North Carolina)', 800426, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('New Prague (Minnesota)', 191805, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Stiles, Seneca Knolls (New York)', 804743, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Newby (Texas)', 810856, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Goldendale (Washington)', 817835, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lawrence (Utah)', 818799, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Donalsonville (Georgia)', 833495, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Deel, Vansant (Virginia)', 833376, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Thornton (Michigan)', 846378, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Willow Park (Texas)', 162531, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Gloucester City (New Jersey)', 185434, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Farr West (Utah)', 184528, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Oftringen (Aargau)', 203690, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ellenboro (West Virginia)', 255473, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Uniontown (Stark, Ohio)', 808857, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Maple Grove (Wayne, Pennsylvania)', 839145, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Du Bois (Pennsylvania)', 192967, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Rockmart (Georgia)', 196506, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('McNary, Umatilla (Oregon)', 807706, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Arcadia Park, Dallas (Texas)', 810799, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Kent (Virginia)', 817986, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ontinyent (Comunidad Valenciana)', 138110, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Durand (Michigan)', 160859, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Andrews (North Carolina)', 801718, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Brooklyn Park (Maryland)', 209384, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Decherd (Tennessee)', 812627, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Imperial (California)', 189723, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Clintwood (Virginia)', 833103, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Saxon (South Carolina)', 821822, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Willow Grove (Virginia)', 821192, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cockeysville (Maryland)', 794042, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Boucherville (Québec)', 227794, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Wilkinsonville (Massachusetts)', 795122, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Oxon Hill (Maryland)', 798355, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('West Bloomfield (New York)', 804751, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Abergele, Conwy (Wales)', 109201, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hawkesbury (Ontario)', 10614, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bayswater (State of Victoria)', 621892, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pumpkin Center (Onslow, North Carolina)', 801144, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Atkins (Virginia)', 1323, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Blaine (Ohio)', 841247, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Goffs, Halifax (Nova Scotia)', 649273, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Fayetteville (West Virginia)', 184716, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mabank (Texas)', 824252, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Gothenburg (Nebraska)', 840893, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bucksnort (Tennessee)', 813598, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ardmore (Indiana)', 835673, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Plano (Illinois)', 41923, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dalton (Wisconsin)', 834539, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Solomons (Maryland)', 24199, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Oakdale (Allegheny, Pennsylvania)', 192531, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Campbellton (New Brunswick)', 666887, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Foxy Creek Indian Reserve 6, Bulkley-Nechako B (British Columbia)', 646360, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Waterford (Connecticut)', 782593, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cookstown (New Jersey)', 5687, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Boldon, South Tyneside (England)', 235666, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lawrenceville (Ohio)', 824727, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hobart (Indiana)', 171654, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sawmill (Arizona)', 209787, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Willow Springs (Missouri)', 160584, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Allendale (Michigan)', 269540, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Little Ferry (New Jersey)', 164200, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Royal Blue, Caryville (Tennessee)', 814599, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cairo Junction (Illinois)', 828451, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Worthington (Iowa)', 791356, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jackson (Wisconsin)', 161407, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Akron (Pennsylvania)', 245386, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mandeville (Missouri)', 793999, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sainte-Anne-de-Beaupré (Québec)', 228689, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Ban Bo Nok', 1138072, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Guaíba (Rio Grande do Sul)', 232084, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mapleview (Minnesota)', 852866, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Selah (Washington)', 850607, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Milesburg (Pennsylvania)', 189830, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Galveston (Virginia)', 823676, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hartville (Missouri)', 796549, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Evanston (Tennessee)', 815067, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Eutaw (Alabama)', 198823, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hannibal (Texas)', 811344, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Brick Church (Tennessee)', 833274, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Oak Grove (Lewis, Tennessee)', 816361, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Pryor (Montana)', 204153, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Mansfield (Arkansas)', 842444, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Saint-Patrice, Rivière-du-Loup (Québec)', 659862, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Cuba (New York)', 180467, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Tipton, Atoka (Tennessee)', 814981, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Takaishi-shi (Osaka Prefecture)', 141324, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Whitsett (North Carolina)', 205807, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Piney Point (Maryland)', 798400, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Columbia (Pennsylvania)', 191303, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Tilton (Kentucky)', 837556, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Boaz (Alabama)', 2914, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Robertson, Hazelwood (Missouri)', 792664, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Milan (Michigan)', 36539, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('St Ann (Missouri)', 209760, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sacramento (Nebraska)', 835151, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Attawaugan (Connecticut)', 844631, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Jasper (Tennessee)', 167821, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('New Kensington (Pennsylvania)', 191772, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Huntingburg (Indiana)', 167614, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Sullivan (Wisconsin)', 161334, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Lodi (Ohio)', 803544, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Hope (Wisconsin)', 817660, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Palmona Park (Florida)', 780290, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Northborough (Massachusetts)', 209680, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Melton South (State of Victoria)', 617510, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Weißenfels - Pettstädt (Sachsen-Anhalt)', 97387, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Leopoldina (Minas Gerais)', 598502, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Longview (Colorado)', 783943, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Etra (New Jersey)', 805147, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Faycelles (Midi-Pyrénées)', 240560, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Chaitén (Región de Los Lagos)', 602454, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Chiloquin (Oregon)', 812236, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bradford Woods (Pennsylvania)', 159735, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bethlehem Center (New York)', 796535, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Bedford (Illinois)', 786750, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Antelope (South Dakota)', 811071, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Dapoli (Maharashtra)', 3324514, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('South Mansfield (Louisiana)', 792629, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('New Liskeard (Ontario)', 228371, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Burkeville (Virginia)', 832947, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Blue Mound (Texas)', 191203, NULL, 'hrs');
INSERT INTO cms_hotel_city(city_name, location_id, city_id, source) VALUES('Perry (Vermont)', 839591, NULL, 'hrs');